- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
- src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Parent PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1996
> Merge IBX-1356

- src/bundle/Resources/translations/content.en.xliff
- src/bundle/Resources/translations/content_preview.en.xliff
- src/bundle/Resources/translations/menu.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
> Updated translation messages

- src/bundle/Resources/public/js/scripts/admin.notifications.js
- src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/public/scss/_notifications.scss
- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
- src/bundle/Resources/views/themes/admin/ui/notification.html.twig
- src/bundle/ui-dev/src/modules/common/services/notification.service.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1453
> IBX-1453: Redesigned notification bars

- src/bundle/Resources/public/scss/mixins/_modals.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_drop.area.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_progress.bar.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.list.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.popup.scss
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/multi_file_upload.en.xliff
- src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/progress-bar/progress.bar.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.item.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1333
> IBX-1333: Redesigned multi file upload

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | [IBX-1544](https://issues.ibexa.co/browse/IBX-1544)
> IBX-1544: Parse tooltip also on baseElement

- src/bundle/Resources/public/js/scripts/admin.content.tree.js
https://issues.ibexa.co/browse/IBX-1559
It's improvement connected to taxonomy view
> IBX-1559: Add safeguard to rendering Content Tree if no root DOM element avaiable

- src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss
- src/bundle/Resources/translations/content_tree.en.xliff
- src/bundle/Resources/translations/ezplatform_content_forms_content.en.xliff
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1332
> IBX-1332: Updated ezimageasset fieldtype

- src/lib/Behat/Component/UpperMenu.php
Adapting tests to the changes done in https://github.com/ibexa/admin-ui/pull/76
> [Behat] Adapted tests to user menu changes

- src/bundle/Resources/public/scss/_search-links-form.scss
- src/bundle/Resources/public/scss/ezplatform.scss
- src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
- src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1562
> IBX-1562: Redesigned url management

- src/bundle/Resources/public/scss/_alerts.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1567
> IBX-1567: Added word break to alerts

- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/public/scss/ezplatform.scss
- src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1558
> IBX-1558: Redesigned details view

- src/bundle/Resources/translations/content_edit.en.xliff
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1529
> IBX-1529: Added language in content edit header

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1637
> IBX-1637: Removed beckground from secondary button on hover

- src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1602
> IBX-1602: Show first goup in content type create if all are empty

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
- src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
- src/bundle/Resources/views/themes/admin/content_type/edit_section.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_base.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-1385
> IBX-1385: scenario edit redesign

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1642
> IBX-1642: Added check if transition event was on width

- src/bundle/Resources/public/scss/_edit-header.scss
- src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
JIRA: https://issues.ibexa.co/browse/IBX-1386
> IBX-1386: Model edit redesign

- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/base.html.twig
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/create.html.twig
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/edit.html.twig
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1402
> IBX-1402: Changed layout in content type group create and edit

- src/bundle/Resources/translations/language.en.xliff
- src/bundle/Resources/views/themes/admin/language/base.html.twig
- src/bundle/Resources/views/themes/admin/language/create.html.twig
- src/bundle/Resources/views/themes/admin/language/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1422
> Langague edit

- src/bundle/Resources/public/scss/_general.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1503
> IBX-1503: Removed max-heigh on scrollable tables

- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
- src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
- src/bundle/Resources/views/themes/admin/section/view.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
- src/lib/Behat/Page/ContentTypePage.php
- src/lib/Behat/Page/SectionPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1551
- https://github.com/ibexa/system-info/pull/12
> IBX-1551: Redesigned details view in various places

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1501
> IBX-1501: Disable remove group if not empty

- src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1409
- [ x] Coding standards (`$ composer fix-cs`)
> IBX-1409: Added search icon to filter in content type edit

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
- src/bundle/Resources/public/scss/_anchor-navigation.scss
- src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
- src/lib/Behat/Page/ContentUpdateItemPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1403
> IBX-1403: Removed grayed parts when scrolling in content type edit

- src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1703
> IBX-1703: Added default width to content tree

- src/bundle/Resources/public/scss/_content-type-edit.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1499
> IBX-1499: Inaccessible fields toolbar while creating a content type

- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/views/themes/admin/ui/component/dropdown.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/dropdown_item.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1707
| Doc needed?   | ?
> IBX-1707: Redesign Price and Stock Management to Shipping Management

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
> Fixed placeholder is not defined

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1753
> IBX-1753: Fix ibexa tooltips not working on SVG

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1766
> IBX-1766: UDW preview panel resizing

- src/bundle/Resources/public/scss/_extra-actions.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1713
> IBX-1713: Removed modificator from product catalog

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1733
> IBX-1733: UDW - Resized window - text on buttons

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | (see description)
JIRA: 
- https://issues.ibexa.co/browse/IBX-1659
- https://issues.ibexa.co/browse/IBX-1658
> IBX-1659: Models & Scenarios tables redesign -- add small dropdown option to component

- src/bundle/Resources/translations/messages.en.xliff
> Fix translations on login screen

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1425
> IBX-1425: Changed icon color in content preview

- src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1621
> IBX-1621: Changed main menu background color

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1679
> IBX-1679: Added border to UDW

- src/bundle/Resources/public/scss/ui/modules/content-tree/_list.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1719
> IBX-1719: Content tree - helper text

- src/bundle/Resources/public/scss/_alerts.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1675
> IBX-1675: Notifications text wrapping

- src/bundle/Resources/public/scss/_content-tree.scss
- src/bundle/Resources/public/scss/ui/modules/content-tree/_header.scss
- src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
- src/bundle/ui-dev/src/modules/content-tree/components/header/header.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1605
> IBX-1605: Content tree hide button

- src/bundle/Resources/public/scss/_tabs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1785
> IBX-1785: Fix ibexa-tabs styling

- src/bundle/Resources/public/scss/ui/modules/content-tree/_header.scss
- src/bundle/ui-dev/src/modules/content-tree/components/header/header.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1685
> IBX-1685: content tree headline - resize

- src/bundle/Resources/public/scss/_autosave.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1350
> IBX-1350: autosave icon color

- src/bundle/Resources/public/scss/_dashboard.scss
- src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
- src/lib/Behat/Page/DashboardPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1537
> IBX-1537: Cutted dashboard

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tree.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/toggle-selection/toggle.selection.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1806
> IBX-1806: Updated single select in UDW

- src/bundle/Resources/public/scss/_general.scss
| Tickets       | [](https://issues.ibexa.co/browse/IBX-1801)
- https://github.com/ibexa/commerce-admin-ui/pull/28
> IBX-1801: Updated ibexa container styles

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.create.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.edit.scss
- src/bundle/Resources/translations/content_edit.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
- src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1798
> IBX-1789: Moved actions inside iframe in COTF

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1152
> IBX-1152: Added back label in anchor navigation

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1807
> IBX-1807: Moved border from left to right in UDW panel view

- src/bundle/Resources/translations/locationview.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
> Fix missing translations in locations tab

- src/bundle/Resources/config/universal_discovery_widget.yaml
- src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
- src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
| Tickets       | [IBX-1514](https://jira.ez.no/browse/IBX-1799)
Parent PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/2025
> Merge IBX-1799: Added new UDW configuration for Subtree filter

- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/public/scss/_login.scss
- src/bundle/Resources/views/themes/admin/account/login/index.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1816
> IBX-1816: Updated errors in login screen

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1813
> IBX-1813: Added disabled state to dropdown

- src/bundle/Resources/translations/linkmanager.en.xliff
> Fixed translations in link edit

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1825
> IBX-1825: Updated change password tab

- src/bundle/Resources/public/scss/_custom.scss
- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/views/themes/admin/ui/component/table/empty_table_body_row.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1814
> IBX-1814: Empty product catalog hints

- src/bundle/Resources/translations/bookmark.en.xliff
- src/bundle/Resources/translations/drafts.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/section.en.xliff
- src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
- src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
- src/bundle/Resources/views/themes/admin/content_type/list.html.twig
- src/bundle/Resources/views/themes/admin/language/index.html.twig
- src/bundle/Resources/views/themes/admin/object_state/list.html.twig
- src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
- src/bundle/Resources/views/themes/admin/section/view.html.twig
- src/bundle/Resources/views/themes/admin/trash/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/form/assign_section_widget.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
- src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
- src/lib/Behat/Page/RolePage.php
- src/lib/Behat/Page/SectionPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1812
| Tests pass?   | yes/
- https://github.com/ibexa/scheduler/pull/34
- https://github.com/ibexa/segmentation/pull/16
> IBX-1812: Added labels in table buttons

- src/bundle/Resources/public/js/scripts/admin.contenttype.selection.js
- src/bundle/Resources/public/scss/_selection-table.scss
- src/bundle/Resources/public/scss/ibexa.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1869
> IBX-1869: Fixed unable to add options in selection field type

- src/bundle/Resources/public/js/scripts/login.js
- src/bundle/Resources/views/themes/admin/account/login/index.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1866
> IBX-1866: Disable login when fields are empty

- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
JIRA ref: https://issues.ibexa.co/browse/IBX-1880
Related PR: https://github.com/ibexa/taxonomy/pull/25
> IBX-1880: [Taxonomy] Remove subitems from location view

- src/bundle/Resources/public/js/scripts/edit.header.js
- src/bundle/Resources/public/scss/_edit-header.scss
- src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1908 https://issues.ibexa.co/browse/IBX-1844
> IBX-1844/1908: Moved info icon to header in content create/edit

- src/bundle/Resources/views/themes/admin/user/create.html.twig
- src/bundle/Resources/views/themes/admin/user/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1909
> IBX-1909: Hide autosave status in user create/edit

- src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1873
> IBX-1873: Fixed remove location in objectrelation field type

- src/bundle/Resources/public/scss/_edit-header.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1907
> IBX-1907: Set max width for create/edit headline

- src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1888
> IBX-1888: Hide tooltip after bookmark content

- features/standard/Roles.feature
- src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/scss/_assign.scss
- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/translations/menu.en.xliff
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/base.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
- src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1865
> IBX-1865: Redesigned assigning users and groups

- src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1938
- https://github.com/ibexa/calendar/pull/19
> IBX-1938: Fixed checkbox placement in tables

- src/bundle/Resources/public/scss/_extra-actions.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1858
> IBX-1858: Added backdrop in COTF

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/js/scripts/admin.contenttype.selection.js
- src/bundle/Resources/public/js/scripts/core/draggable.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1318
> IBX-1318: Prevented dragging on child elements

- src/lib/Behat/Page/SystemInfoPage.php
Adapted tests to https://github.com/ibexa/system-info/pull/17
> [Behat] Adapted tests to System Info redesign

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/role.en.xliff
- src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
> Updated translations

- src/bundle/Resources/public/scss/_anchor-navigation.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1850
> IBX-1850: Updated anchor navigation hover state

- src/bundle/Resources/public/scss/_main-container.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1928
> IBX-1928: Changed side menu width in content edit

- src/bundle/Resources/views/themes/admin/ui/tab/url_management.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1929
- https://github.com/ibexa/system-info/pull/18
> IBX-1929: Hide collapse button in url manager

- src/bundle/Resources/public/scss/_collapse.scss
- src/bundle/Resources/views/themes/admin/ui/component/collapse.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1872
> IBX-1872: Added ellipsis to field type header

- src/bundle/Resources/public/js/scripts/login.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1956
> IBX-1956: Detect username/password automatic autofill on login page

- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1720
> IBX-1720: Changed resize calculation in subitems

- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
- src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1824
> IBX-1824: Added back button in cotf

- src/bundle/Resources/public/scss/_content-type-edit.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1787
> IBX-1787: Added margin to checkboxes in content edit

- src/lib/Menu/UserCreateRightSidebarBuilder.php
- src/lib/Menu/UserEditRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1033
> IBX-1033: Removed icons in user create/edit

- src/bundle/Resources/public/js/scripts/core/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1848
> IBX-1848: Fixed count number of hidden items in dropdowns

- src/bundle/Resources/public/scss/_forms.scss
- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1426
> IBX-1426: Fixed displaying of errors in contet edit

- src/bundle/Resources/public/scss/_general.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1757
> IBX-1757: remove ibexa-standalone-page css class (Perso Welcome page redesign)

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/views/themes/admin/account/login/index.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1165
> IBX-1165: Added clear button in login screen

- src/bundle/Resources/public/scss/_notifications-modal.scss
- src/bundle/Resources/views/themes/admin/account/notifications/list_item.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1843
> IBX-1843: Fixed background in notification table

- src/bundle/Resources/translations/draft_conflict.en.xliff
- src/bundle/Resources/views/themes/admin/content/modal/draft_conflict.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1137
> IBX-1137: Added label to button in draft conflict

- src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1500
> IBX-1500: Fixed checkboxes in tables

- src/bundle/Resources/public/scss/_tabs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1611
> IBX-1611: Updated tabs hover state

- src/bundle/Resources/public/scss/_field-group.scss
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2002
> IBX-2002: Redesigned language switcher in content structure

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2029
> IBX-2029: Fixed error in content type edit validation

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_custom.tooltip.scss
- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1725
remarks: 
6. - something to clarify with design team
8. - locally cannot reproduce, seems like platform.sh blocking cookies?
10. - the proposed border is not visible if surrounded content is light
> IBX-1725: Updated main navigation

- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1355
> IBX-1355: Fixed shadow under main box

- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.columns.toggler.list.element.scss
- src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.columns.toggler.list.element.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1170
> IBX-1170: Fixed margins in column toggler in subitems

- src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1614
> IBX-1614: Fixed styling for keyword fieldtype

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1169
> IBX-1169: Fixed hover state in secondary button

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1359
> IBX-1359: Added hover state to group name in drad on drop

- src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1710
> IBX-1710: Removed hide/show from dashboard

- src/bundle/Resources/public/scss/_forms.scss
- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2047
> IBX-2047: Fixed misaligned errors with icon

- src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1527
> IBX-1527: Fix dropdown truncating too much of a selected text

- src/bundle/Resources/public/scss/_grid-view-item.scss
- src/bundle/Resources/public/scss/_grid-view.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1424
> IBX-1424: UDW- bookmarks- Grid view

- src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
- src/bundle/Resources/views/themes/admin/user/policy/create_with_limitation.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2052
> IBX-2052: Fixed dropdown visbility when original input is hidden

- src/bundle/Resources/config/services/rest.yaml
- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
- src/bundle/Resources/public/js/scripts/admin.search.filters.js
- src/bundle/Resources/public/js/scripts/admin.trash.list.js
- src/bundle/Resources/public/js/scripts/helpers/location.helper.js
- src/bundle/Resources/public/js/scripts/udw/select.location.js
- src/bundle/ui-dev/src/modules/common/services/common.service.js
- src/bundle/ui-dev/src/modules/common/services/content.type.service.js
- src/bundle/ui-dev/src/modules/content-tree/content.tree.module.js
- src/bundle/ui-dev/src/modules/content-tree/services/content.tree.service.js
- src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
- src/bundle/ui-dev/src/modules/sub-items/services/bulk.service.js
- src/bundle/ui-dev/src/modules/sub-items/services/endpoints.js
- src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
- src/lib/REST/Input/Parser/BulkOperation.php
> IBX-2007: Rebranded REST media types in ibexa/admin-ui repository

- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1841
> IBX-1841: Added missing frame in richtext

- src/bundle/Resources/public/scss/_content-tree.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1686
> IBX-1686: Added shadow in content tree

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
- src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
- src/bundle/Resources/public/js/scripts/admin.search.filters.js
- src/bundle/Resources/public/js/scripts/admin.trash.list.js
- src/bundle/Resources/public/js/scripts/helpers/location.helper.js
- src/bundle/Resources/public/js/scripts/udw/select.location.js
- src/bundle/ui-dev/src/modules/common/services/common.service.js
- src/bundle/ui-dev/src/modules/content-tree/services/content.tree.service.js
- src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
- src/bundle/ui-dev/src/modules/sub-items/services/endpoints.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
> IBX-2061: Rebranded REST route prefix in ibexa/admin-ui repository

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1747
> IBX-1747: Fixed double selected item if value is empty in dropdown

- src/bundle/Resources/config/admin_ui_forms.yaml
- src/bundle/Resources/config/default_parameters.yaml
- src/bundle/Resources/config/ezplatform_default_settings.yaml
- src/bundle/Resources/config/role.yaml
- src/bundle/Resources/config/services/components.yaml
- src/bundle/Resources/config/services/dashboard.yaml
- src/bundle/Resources/config/services/tabs/content_type.yaml
- src/bundle/Resources/config/services/tabs/locationview.yaml
- src/bundle/Resources/config/services/tabs/url_management.yaml
- src/bundle/Resources/config/services/user_settings.yaml
- src/bundle/Resources/config/views.yaml
> IBX-1210: Rebranded @ezdesign ibexa/admin-ui repository

- src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2087
> IBX-2087: Fixed error in user settings

- src/bundle/Resources/public/scss/_general.scss
| Tickets       | <https://issues.ibexa.co/browse/IBX-2085
> IBX-2085: Added border to table in richtext

- src/bundle/Resources/public/js/scripts/core/tag.view.select.js
- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1338
> IBX-1338: UDW - label truncation in tag

- src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2089
> IBX-2089: Hide menu toggler if level is collapsed

- src/bundle/Resources/views/themes/admin/section/view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2124
> IBX-2124: Set disabled state on delete button in section view

- src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2114
> IBX-2114: Added min-width to dropdown

- src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1156
> IBX-1156: Wrong size all inputs/dropdowns, etc. in table

- src/bundle/Resources/public/js/scripts/udw/locations.tab.js
- src/bundle/Resources/public/js/scripts/udw/swap.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2127
> IBX-2127: Cant edit taxonomy

- src/bundle/Resources/config/views.yaml
> IBX-1853: Used rebranded namespaces and services names

- src/bundle/Resources/public/scss/_instant-filter.scss
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1183
> IBX-1183: Click area

- src/bundle/Resources/public/js/scripts/admin.trash.list.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2129
> IBX-2129: Added guard if trash is empty

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1601
> IBX-1601: Moved arrows in input number to the right

- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1890
> IBX-1890: Added actions block to alerts

- src/bundle/Resources/public/scss/_extra-actions.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_translation.selector.scss
- src/bundle/Resources/translations/universal_discovery_widget.en.xliff
- src/bundle/ui-dev/src/modules/universal-discovery/components/translation-selector/translation.selector.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2133
> IBX-2133: Styling for translation select

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1842
> IBX-1842: Double message in Button setting in Form Builder

- src/bundle/Resources/public/js/scripts/admin.content.tree.js
- src/bundle/Resources/public/js/scripts/admin.context.menu.js
- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2122
> IBX-2122: Subitem table is narrowed when content tree is collapsed

- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2123
https://github.com/ibexa/taxonomy/pull/57
> IBX-2123: Added hide_bookmarks variable

- src/bundle/ui-dev/src/modules/sub-items/components/no-items/no.items.component.js
- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
- src/lib/Behat/Component/SubItemsList.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1354
> IBX-1354: Styled empty subitems

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/search.en.xliff
- src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2144
| Bug fix?      | yes/
> IBX-2144: Fix translations in main search

- src/bundle/Controller/ContentOnTheFlyController.php
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
- src/contracts/Event/ContentOnTheFlyEvents.php
- src/contracts/Event/UserOnTheFlyEvents.php
- src/lib/Form/Processor/User/UserOnTheFlyProcessor.php
- src/lib/View/ContentTranslateSuccessView.php
https://issues.ibexa.co/browse/IBX-2139
> IBX-2139: Reverted event name change

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-922
> IBX-922: Edit button on the policy list should be grayed out when the user is not able to edit policy

- src/bundle/Resources/public/scss/_add-translation.scss
…
| Tickets       | https://issues.ibexa.co/browse/IBX-2143
> IBX-2143: Misaligned arrow when adding translation to Product/Attribute Group

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1103
> IBX-1103: Remove tooltips when unneeded

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2166
> IBX-2166: Added icon fill in button ghost focus state

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2159
> IBX-2159: Page Builder: add notification/feedback to user about invalid fields/layout

- src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
- https://github.com/ibexa/product-catalog/pull/379
> Hide content type in cotf which are hidden by config

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2165
> IBX-2165: Search in UDW

- src/bundle/Resources/public/scss/_content-type-edit.scss
- src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1408
> IBX-1408: Number input

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2167
> IBX-2167: Filter in field types in content type edit

- src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2164
> IBX-2164: Added tooltips in bookmarks list in udw

- src/bundle/Resources/public/scss/_main-header.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2163
> IBX-2163: Changed placeholder color in global search

- src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2179
> IBX-2179: Error in bookmarks JS on taxonomy page

- src/bundle/Resources/public/scss/fieldType/edit/_ezselection.scss
- src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2108
| Tests pass?   | yes/
Related PRs:
- https://github.com/ibexa/product-catalog/pull/384
> IBX-2108: Adjust fields' width in edit views

- src/bundle/Resources/public/js/scripts/admin.content.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2189
> IBX-2189: Disable autosave JS when autosave not rendered

- src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2190
> IBX-2190: Fix ezgmaplocation field

- src/bundle/DependencyInjection/Compiler/SecurityLoginPass.php
- src/bundle/Resources/config/default_parameters.yaml
- src/bundle/Resources/config/ezplatform_default_settings.yaml
- src/bundle/Resources/config/role.yaml
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/events.yaml
- src/bundle/Resources/config/services/form_processors.yaml
- src/bundle/Resources/config/services/forms.yaml
- src/bundle/Resources/config/services/rest.yaml
- src/bundle/Resources/config/services/role_form_mappers.yaml
- src/bundle/Resources/config/services/siteaccess.yaml
- src/bundle/Resources/config/services/translation.yaml
- src/bundle/Resources/config/services/ui_config/common.yaml
- src/bundle/Resources/config/services/user_settings.yaml
- src/bundle/Resources/config/services/views.yaml
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

- src/bundle/Resources/public/scss/_content-type-edit.scss
- src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
- src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php
| Tickets       | [](https://issues.ibexa.co/browse/IBX-2172)
> IBX-2172: Added options to disable fields in FieldDefinitionType

- src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations_reverse.html.twig
- src/lib/Form/Data/FormMapper/ContentCreateMapper.php
- src/lib/Form/Type/ContentType/ContentTypeGroupType.php
- src/lib/Form/Type/Role/LimitationType.php
> IBX-1853: Used rebranded namespaces in code

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2092
> IBX-2092: Add trigger tooltip option (data-attribute)

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_filters.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2200
> IBX-220: UDW search improvements

- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.list.scss
- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.popup.scss
- src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2210
> IBX-2210: Removed close button from multi file upload

- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| Tickets       | https://issues.ibexa.co/browse/IBX-511
> IBX-511: Add event for closing extra actions

- src/bundle/Resources/public/scss/_forms.scss
- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2217
> IBX-2217: Moved ibexa-form-help margin to global scope

- src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2218
> IBX-2218: Fixed richtext validation if only one character

- src/bundle/Resources/views/themes/admin/content_type/part/field_definition_form.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2231
> IBX-2231: Added field identifier in content type create

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2235
> IBX-2235: CT edit - set first field definition group to active on load

- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2241
> IBX-2241: Add extra content to ibexa input text

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.table.item.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2242
> IBX-2242: [UDW] Change border in search to primary

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/public/js/scripts/autogenerate.identifier.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2270
| Related to | https://github.com/ibexa/taxonomy/pull/100
|| https://github.com/ibexa/product-catalog/pull/410
> As a developer, I would like to be able to automatically generate an id based on a given field

- src/bundle/Resources/public/js/scripts/admin.context.menu.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2285
https://github.com/ibexa/scheduler/pull/50
> IBX-2285: If content is hidden, user can still click Hide button and nothing happens

- src/lib/Menu/MainMenuBuilder.php
| Tickets       |   [IBX-1728](https://issues.ibexa.co/browse/IBX-1728)
Wrong navigation structure
> IBX-1728: Wrong navigation structure

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2178
> IBX-2178 drag&drop sidebar does not hide elements properly when searching

- src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1045
> IBX-1045: Author field type margins

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/public/scss/_grid-view-item.scss
- src/bundle/Resources/public/scss/_icon-tag.scss
- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/public/scss/mixins/_tags.scss
- src/bundle/Resources/public/scss/ui/modules/content-tree/_popup.actions.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1376
| Related to | https://github.com/ibexa/page-builder/pull/89
|| https://github.com/ibexa/personalization/pull/118
> IBX-1376: Delete unnecessary letter-spacing 0.12px in CSS

- src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2406
> IBX-2406: Fix main menu buttons text vertical alignemnt

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2405
> IBX-2405: Fix ibexa-toggle disabled state - needless grey horizontal line (checkbox input)

- src/bundle/Resources/public/scss/_custom.scss
- src/bundle/Resources/public/scss/functions/_calculate.rem.scss
- src/bundle/Resources/public/scss/mixins/_modals.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2403
| New feature?  | o
> IBX-2403: Fix SCSS calculateRem to return proper rem

- src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2422
> IBX-2422: Cannot Select from library in ImageAsset field

- behat_suites.yml
- composer.json
- features/standard/ContentTypeFields.feature
- src/bundle/DependencyInjection/IbexaAdminUiExtension.php
- src/lib/Behat/BrowserContext/ContentViewContext.php
- src/lib/Behat/BrowserContext/NavigationContext.php
- src/lib/Behat/BrowserContext/NotificationContext.php
- src/lib/Behat/BrowserContext/UDWContext.php
- src/lib/Behat/Page/ContentViewPage.php
JIRA: https://issues.ibexa.co/browse/IBX-2322
> Rebrand behatbundle

- src/bundle/DependencyInjection/IbexaAdminUiExtension.php
- src/bundle/Resources/encore/ibexa.config.setup.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2413
- https://github.com/ibexa/recipes/pull/100
- https://github.com/ibexa/fieldtype-richtext/pull/36
- https://github.com/ibexa/calendar/pull/31
- https://github.com/ibexa/content-tree/pull/30
- https://github.com/ibexa/form-builder/pull/53
- https://github.com/ibexa/image-editor/pull/64
- https://github.com/ibexa/page-builder/pull/93
- https://github.com/ibexa/segmentation/pull/37
- https://github.com/ibexa/taxonomy/pull/105
- https://github.com/ibexa/tree-builder/pull/72
> IBX-2413: Changed relative paths to encore aliases

- src/bundle/Resources/public/scss/_admin.section-view.scss
- src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
- src/bundle/Resources/views/themes/admin/section/view.html.twig
- src/lib/Behat/Page/SectionPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2380
> IBX-2380: Layout of Section page need to be updated

- src/bundle/Resources/public/scss/_anchor-navigation.scss
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/universal_discovery_widget.en.xliff
- src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
- src/bundle/ui-dev/src/modules/universal-discovery/components/top-menu/top.menu.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
- src/lib/Behat/Page/ContentUpdateItemPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2064
| Related to | https://github.com/ibexa/page-builder/pull/96
> IBX-2064: Rename label Back to Close in editing and creating

- features/standard/ObjectStates.feature
- src/bundle/Resources/public/scss/_object-state-group-view.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/translations/object_state.en.xliff
- src/bundle/Resources/views/themes/admin/object_state/list.html.twig
- src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
- src/bundle/Resources/views/themes/admin/object_state/view.html.twig
- src/lib/Behat/Page/ObjectStateGroupPage.php
- src/lib/Behat/Page/ObjectStatePage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2450
> IBX-2450: Object state group view design improvements

- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2494
> IBX-2494: No icon with custom content type in location view

- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2412
> IBX-2412: Improve checkbox styling

- src/bundle/Resources/public/scss/mixins/_modals.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2427
> IBX-2427: Reschedule modal - calendar popup is not fully visible

- src/bundle/Resources/public/scss/_header-user-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2415
> IBX-2415: Fix bell icon alignment in the header

- src/bundle/Resources/public/js/scripts/admin.context.menu.js
- src/bundle/Resources/public/scss/_context-menu.scss
- src/bundle/Resources/public/scss/_header.scss
- src/bundle/Resources/views/themes/admin/ui/component/context_menu/context_menu.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2520
> IBX-2520: Fix action buttons from the header overlapping with other things before adaptive items is initialized

- src/bundle/Resources/views/themes/admin/account/notifications/modal.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2529
> IBX-2529: Unnecessary subtitle in Notifications popup

- src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
- src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2540
> IBX-2540: MFU - changing window width triggers file upload

- src/bundle/Resources/public/js/scripts/core/adaptive.items.js
- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/public/scss/_popup-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/first_level_popup_menu_item.html.twig
- src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
- src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig
- src/lib/Menu/MainMenuBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2418
> Menu on small screen

- src/lib/Behat/BrowserContext/ContentTypeContext.php
- src/lib/Behat/Page/ContentTypeUpdatePage.php
JIRA: https://issues.ibexa.co/browse/IBX-1313
This PR is a continuation of https://issues.ibexa.co/browse/IBX-671.
Related PR: https://github.com/ibexa/page-builder/pull/105
> [WiP][Behat] IBX-1313 Added selection of editor launch mode in content type

- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-414
> IBX-414: Added ghost version of dropdown

- src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2591
> IBX-2591: Main menu - list button from 2nd stage not opening

- src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
> Fixed deprecated ez_render_component_group usage

- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2459
> IBX-2459: Fixed error when selecting bookmarked content in UDW

- src/bundle/Resources/public/js/scripts/sidebar/btn/content.edit.js
- src/bundle/Resources/public/js/scripts/sidebar/btn/location.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2744
> IBX-2744: Fixed edit button in location view

- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2735
> IBX-2735: cannot add tag

- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2746
Related PRs:
- https://github.com/ibexa/page-builder/pull/118
> IBX-2746: Page builder - double scroll in block settings panel

- src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
- src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
- src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
- tests/lib/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
- tests/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypesTest.php
Cross merge PR of https://github.com/ezsystems/ezplatform-admin-ui/pull/2039
> Merge IBX-2275: Refactor UDW configuration subscribers

- src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
- src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
- src/bundle/Resources/public/js/scripts/fieldType/eztime.js
| Tickets       | [IBX-2796](https://issues.ibexa.co/browse/IBX-2796)
> IBX-2796: reference correct property

- src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Follow up for https://github.com/ibexa/admin-ui/pull/377 as issues from Kuba and Łukasz weren't implemented due to release and the fact that QA was already done
> IBX-2603: Content Tree actions: followup for code standards

- src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2826
> IBX-2826: Search input should be hidden when less than 5 items are in dropdown

- src/lib/Behat/Page/ContentUpdateItemPage.php
This PR's is created to prevent errors like https://github.com/ibexa/commerce/runs/6360222003?check_suite_focus=true. 
https://res.cloudinary.com/ezplatformtravis/image/upload/v1652136545/screenshots/62799a615e4ae042469311-vendor_ibexa_workflow_features_browser_workflowlimitation_feature_5_bfyjts.png
> [Behat] Fixed selector in workflowLimitation.feature

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2673
> IBX-2673: Unable to scroll grid view in UDW

- src/bundle/Resources/public/scss/_header-user-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2417
Related PRs:
- https://github.com/ibexa/user/pull/36
> IBX-2417: Size of avatar in header

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/public/scss/_popup-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2775
> IBX-2775: Fixed main menu selection

- src/bundle/Resources/public/scss/_content-type-edit.scss
- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
- src/bundle/Resources/views/themes/admin/content_type/field_definitions_empty_group.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2777
> IBX-2777: Personalization - model edit fixes

- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/public/scss/_popup-menu.scss
> IBX-2775: Fix prettier styling

- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/public/scss/_page-title.scss
- src/bundle/Resources/public/scss/_popup-menu.scss
- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/public/scss/_tag.scss
- src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
- src/bundle/Resources/views/themes/admin/ui/search_tag.html.twig
- src/bundle/Resources/views/themes/admin/ui/tag.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2653
Related PRs:
- https://github.com/ibexa/personalization/pull/132
> IBX-2653: Introduce colorful ibexa-tag and ibexa-tag-view-select

- src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js
- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2837
> IBX-2837: Missing spinner when content is loaded in meta data in search

- src/bundle/Resources/public/scss/_header.scss
- src/bundle/Resources/public/scss/_tabs.scss
- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
- src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
- src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig
- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
- src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
- src/bundle/Resources/views/themes/admin/trash/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
- src/bundle/Resources/views/themes/admin/ui/tab/content_type.html.twig
- src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
- src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
- src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
- src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2871
https://github.com/ibexa/system-info/pull/34
https://github.com/ibexa/taxonomy/pull/131
https://github.com/ibexa/workflow/pull/49
> IBX-2871: Wrong spacing on some admin pages

- src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
- src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
- src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
- src/lib/Menu/Admin/ObjectState/ObjectStateCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/ObjectState/ObjectStateEditRightSidebarBuilder.php
- src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
- src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
- src/lib/Menu/SectionCreateRightSidebarBuilder.php
- src/lib/Menu/SectionEditRightSidebarBuilder.php
- src/lib/Menu/URLEditRightSidebarBuilder.php
- src/lib/Menu/URLWildcardEditRightSidebarBuilder.php
- src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2414
> IBX-2414: Button "create" - wrong priority

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2869
> IBX-2869: [Navigation menu] Field groups navigation menu cannot unselect 2nd choice

- src/bundle/ui-dev/src/modules/common/popup/popup.component.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1129
https://github.com/ibexa/page-builder/pull/129
> IBX-1129: As a developer I want to get rid of deprecated React lifecycle methods

- src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js
> Fixed eslint error

- src/bundle/DependencyInjection/Compiler/SecurityLoginPass.php
- src/lib/Security/Authentication/RedirectToDashboardAuthenticationSuccessHandler.php
https://issues.ibexa.co/browse/IBX-2955
https://github.com/ezsystems/ezplatform-admin-ui/pull/2051
FYI: This commit was cherry-picked from 2.3 branch, as 4.0 is EOM
> IBX-2995: Mergeup

- src/lib/Behat/Component/IbexaDropdown.php
- src/lib/Behat/Page/ContentTypeUpdatePage.php
Fix for builds such as: https://github.com/ibexa/fieldtype-page/actions/runs/2414166821
> [Behat] Disabled ElementTransitionHasEndedCondition conditions

- src/bundle/Resources/public/scss/_custom.scss
> Fixed dart-sass failing in compiling by encore

- src/bundle/Resources/public/scss/_edit-header.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2965
> IBX-2965: Added min-height to header title

- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2913
> IBX-2913: Changed type of filter button in fieldtypes widget

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2924
> IBX-2924: [Content types] An exception occurred when user replace position of field 'Content query' in content field definition section.

- src/bundle/Resources/views/themes/admin/content/modal/hide_confirmation.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3007
> IBX-3007: [Content Tree] As a user, I want to have warning modal about hiding content with reverse relations

- behat_suites.yml
| Bug fix?      | tests fix
Fix for problem like in https://github.com/ibexa/commerce-price-engine/runs/6875296560?check_suite_focus=true:
```
--- Use --snippets-for CLI option to generate snippets for following admin-ui suite steps:
And I create a role "autosaveEnabledTestRole" with policies
And I create a role "autosaveDisabledTestRole" with policies
```
> [Behat] Fixed commerce price engine tests

- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2996
> IBX-2996: Hide group if all items are hidden in dropdown

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/js/scripts/core/draggable.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2912
> IBX-2912: Placeholder in D&D blinks when user doesn't move mouse

- src/bundle/Resources/public/scss/mixins/_type-icon.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2821
> IBX-2821: Fixed icon background in read notification

- src/bundle/Resources/public/scss/_header-user-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3070
Related PRs:
- https://github.com/ibexa/user/pull/43
> IBX-3070: User thumbnail should not be rendered with border and other minor bugs

- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3086
| Doc needed?   | ?
> IBX-3086: Vertical view in details UI component

- src/bundle/Resources/public/scss/_adaptive-filters.scss
- src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3071
> IBX-3071: As a Developer, I want to have adaptive filters inside tab

- src/bundle/Resources/public/scss/_header-user-menu.scss
- src/bundle/Resources/public/scss/_user-thumbnail.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
- src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3085
| Doc needed?   | ?
> IBX-3085: As a Developer, I want to have thumbnail twig component

- src/bundle/DependencyInjection/IbexaAdminUiExtension.php
> Changed name of configuration for translation extraction

- src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2381
> IBX-2381: The distance between items and label (Settings) in the menu is incorrect

- src/lib/Behat/Component/IbexaDropdown.php
- src/lib/Behat/Page/SectionsPage.php
Failures:
https://github.com/ibexa/commerce/runs/7187288112?check_suite_focus=true
```
When I start assigning to "Test Section" from Sections page           # Ibexa\AdminUi\Behat\BrowserContext\SectionsContext::iAssignContentItems()
And I select content "root/TestSection" through UDW                   # Ibexa\AdminUi\Behat\BrowserContext\UDWContext::iSelectContent()
Ibexa\Behat\Browser\Exception\TimeoutException: CSS selector 'udw': '.m-ud' not found in 1 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79
Stack trace:
#0 vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php(103): Ibexa\Behat\Browser\Element\BaseElement->waitUntil()
#1 vendor/ibexa/admin-ui/src/lib/Behat/Component/UniversalDiscoveryWidget.php(62): Ibexa\Behat\Browser\Element\BaseElement->find() …
```
> Behat stability fixes

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/public/js/scripts/helpers/pagination.helper.js
- src/bundle/ui-dev/src/modules/common/pagination/pagination.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3114
> IBX-3114: Add Pagination helper

- src/bundle/Resources/public/js/scripts/admin.input.text.js
- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3132
> IBX-3132: Added possibility to change clear button type in inputs

- src/lib/Behat/Component/Fields/RichText.php
Tested in https://github.com/ibexa/experience/pull/51
Failure is described in https://issues.ibexa.co/browse/IBX-3097
> [Behat] Improved stability of selecting Richtext style

- src/bundle/Controller/AssetController.php
- src/bundle/Controller/ObjectStateController.php
- src/bundle/Controller/SectionController.php
- src/lib/EventListener/AdminExceptionListener.php
- src/lib/Form/SubmitHandler.php
- src/lib/Form/Type/ChoiceList/Loader/DatePeriodChoiceLoader.php
- src/lib/Form/Type/ContentType/FieldTypeChoiceType.php
- src/lib/Form/Type/ContentType/SortFieldChoiceType.php
- src/lib/Form/Type/ContentType/SortOrderChoiceType.php
- src/lib/Form/Type/Search/SearchType.php
- src/lib/Form/Type/URL/URLListType.php
- src/lib/Limitation/Mapper/GroupLimitationMapper.php
- src/lib/Limitation/Mapper/OwnerLimitationMapper.php
- src/lib/Menu/Admin/Role/RoleCopyRightSidebarBuilder.php
- src/lib/Notification/TranslatableNotificationHandler.php
- src/lib/UI/Module/FieldTypeToolbar/FieldTypeToolbarFactory.php
> Code style fixes after upgrading PHP-CS-Fixer to 3.9.x

- src/bundle/Resources/public/js/scripts/core/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3243
> IBX-3243: don't trigger change on same option select; trigger change on clearCurrentSelection

- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
- src/lib/Form/Type/URLWildcard/URLWildcardListType.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3251
> IBX-3251: Changed textarea to search type in url wildcards

- src/bundle/Resources/public/scss/_page-title.scss
- src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3090
1. Fixed styles for .ibexa-badge in header
2. Added possibility to add extra classes to tag in page title
> IBX-3090: Added possibility to add extra classes to tag in page title

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3358
> IBX-3358: Set font white color for :focus primary button

- src/bundle/Resources/public/scss/_icon-tag.scss
- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3324
> IBX-3324: Fixed font size and color of description in header

- src/bundle/Resources/public/scss/_trash-search-form.scss
- src/bundle/Resources/views/themes/admin/trash/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3270
> IBX-3270: Fixed styling for select user in trash

- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
- src/bundle/Resources/translations/ezplatform_content_forms_role.en.xliff
- src/bundle/Resources/translations/ezplatform_url_wildcard.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
> Updated translations 

- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_custom.tooltip.scss
- src/lib/Behat/Component/LeftMenu.php
- src/lib/Behat/Component/Table/TableRow.php
- src/lib/Behat/Component/UniversalDiscoveryWidget.php
- src/lib/Behat/Page/ContentTypeGroupPage.php
- src/lib/Behat/Page/ContentTypeGroupsPage.php
- src/lib/Behat/Page/LanguagePage.php
- src/lib/Behat/Page/LanguagesPage.php
- src/lib/Behat/Page/SectionsPage.php
- src/lib/Behat/Page/UserSettingsPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3391
**Requires**
https://github.com/ibexa/tree-builder/pull/86
https://github.com/ibexa/product-catalog/pull/698
https://github.com/ibexa/page-builder/pull/138
> IBX-3391: Changed bs-original-title to original-title

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3393
> IBX-3393: Remove checkmark icon form multiple dropdown

- src/bundle/Resources/public/scss/_field-group.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3375
> IBX-3375: Fixed margin and padding for section header

- src/lib/Behat/Component/Dialog.php
- src/lib/Behat/Component/Table/TableRow.php
> JIRA: [IBX-3048](https://issues.ibexa.co/browse/IBX-3048)
I've added new test scenarios for adding, publishing, archiving, copying, editing and removing catalogs in product catalog.
Related PRs:
https://github.com/ibexa/product-catalog/pull/706
https://github.com/ibexa/behat/pull/26
> [Behat] IBX-3048 Added tests for catalogs

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3426
> IBX-3426: Hide tooltips when switching items in main menu

- features/standard/Languages.feature
- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/translations/language.en.xliff
- src/bundle/Resources/views/themes/admin/language/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table_body_cell.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table_body_row.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table_head_cell.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table_head_row.html.twig
- src/lib/Behat/BrowserContext/LanguageContext.php
- src/lib/Behat/Page/LanguagesPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3381
> IBX-3381: languages list screen update

- src/bundle/Resources/public/js/scripts/button.trigger.js
- src/bundle/Resources/public/js/scripts/user_password.change.js
- src/bundle/Resources/public/scss/_forms.scss
- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3218
> IBX-3218: Fix user password validation, small css fixes etc

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
- src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3344
> IBX-3344: Improvement of mark icon for dropdown

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3427
> IBX-3427: Removed border from disabled state in tertiary buttons

- src/bundle/Resources/views/themes/admin/user/invitation/modal.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3201
> IBX-3201: handled custom form action in invitation modal

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3496
> IBX-3496: Removed unnecessary border from button on hover

- src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3596
| Bug fix?      | yes/
> IBX-3596: Fix bronken validation messages in CI edit

- src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3596
> [Merge-up PR] IBX-3596: Fix bronken validation messages in CI edit

- src/bundle/Resources/public/js/scripts/core/dropdown.js
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3608
> IBX-3608: Added items_class and html to selected item label

- src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3364
> IBX-3364: Increased right padding for --ghost dropdown

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3530
> IBX-3530: Added border color for toolbox item on hover

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
- src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
- src/lib/EventListener/SetViewParametersListener.php
- tests/lib/EventListener/SetViewParametersListenerTest.php
> Fixed fallback HTML structure for content edit sections

- src/bundle/Resources/public/scss/_trash-search-form.scss
- src/bundle/Resources/views/themes/admin/trash/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3471
> IBX-3471: Updated trash view

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3643
> IBX-3643: Fix ibexa-toggle width, cursors, nonselect

- src/bundle/Resources/public/js/scripts/core/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3640
> IBX-3640: Cannot search by partial name in catalog filters

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3493
**Requires:** https://github.com/ibexa/page-builder/pull/147
> IBX-3493: Fixed hover state in button info

- src/bundle/Resources/public/scss/_extra-actions.scss
| Tickets       | [IBX-2559](https://issues.ibexa.co/browse/IBX-2559)
When creating the public ticket, I was sure that the problem only affects v3.3, however, it turned out that version 4.1+ also has this problem, so the solution has been moved from v3.3
> IBX-2559: Added new style to ez-extra-actions__content class to allow scrolling language list

- src/bundle/Resources/public/scss/_field-group.scss
- src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
| ----------------------------------------- | ------------------
| **JIRA issue**                            | https://issues.ibexa.co/browse/IBX-3022
| **Releated to** | https://github.com/ibexa/product-catalog/pull/732
| **Type**                                  | improvement
| **Target Ibexa DXP version**              | `v4.2` 
| **BC breaks**                             | no
> IBX-3022: Improved language selector

- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3707
It could probably wait for @dew326 , as even though I wasn't able to find any case for this particular fragment of css, maybe there's some niche case for it to exist.
> IBX-3707: Tag view select items are incorrectly ellipsized

- src/bundle/Resources/views/themes/admin/account/register/index.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3409
> IBX-3409: Dropped whole form_widget form rendering for user registration

- src/bundle/Resources/config/services/test/components.yaml
- src/lib/Behat/Component/ContentItemAdminPreview.php
- src/lib/Behat/Component/CreateNewPopup.php
- src/lib/Behat/Page/ContentUpdateItemPage.php
This PR adjusts tests to work in the product catalog.
I have added a CreateNewPopup component that can be used to handle the popup for adding a new Product and Attribute in the Product Catalog.
JIRA: https://issues.ibexa.co/browse/IBX-2741 
Related: https://github.com/ibexa/product-catalog/pull/775
> [Behat] IBX-2741: Adjusted tests to work in the product catalog

- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/translations/section.en.xliff
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
- src/bundle/Resources/views/themes/admin/content_type/list.html.twig
- src/bundle/Resources/views/themes/admin/section/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/table/table_header.html.twig
- src/lib/Behat/Page/ContentTypeGroupPage.php
- src/lib/Behat/Page/ContentTypeGroupsPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3408
https://github.com/ibexa/product-catalog/pull/771
https://github.com/ibexa/site-factory/pull/51
> IBX-3408: Added notice to table

- src/bundle/Resources/public/scss/_forms.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3561
> IBX-3561: Removed readonly state for flatpickr inputs

- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3761
> IBX-3761: Fixed toast notification text

- src/lib/Behat/Component/UniversalDiscoveryWidget.php
JIRA: https://issues.ibexa.co/browse/IBX-3099
This should fix the erorr described in the ticket
> [Behat] Fixed UDW bookmarks editing

- src/bundle/Resources/translations/section.en.xliff
- src/bundle/Resources/views/themes/admin/section/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3833
> IBX-3833: Fixed helper text labels in the table headers

- src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3873
> IBX-3873: Create/edit content - unnecessary content switcher on left menu

- src/lib/Behat/Component/Fields/Matrix.php
- src/lib/Behat/Component/IbexaDropdown.php
> Version comparison 4.2

- .github/workflows/frontend-ci.yaml
JIRA ref: https://issues.ibexa.co/browse/IBX-3919
> IBX-3919: Frontend CI doesn't run when there are no changes in frontend files

- src/lib/Behat/Page/ContentUpdateItemPage.php
> JIRA: [IBX-3048](https://issues.ibexa.co/browse/IBX-3479)
Related PR:
https://github.com/ibexa/product-catalog/pull/776
I have added new test scenarios for adding, editing and removing catalog filters in product catalog.
> [Behat] IBX-3479: Added tests for catalog filters

- src/bundle/Resources/public/scss/_back-to-top.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3969
Follow-up of:
- https://github.com/ibexa/admin-ui/pull/578
> IBX-3969: Fix back to top btn styling after bootstrap update

- src/bundle/Resources/public/scss/_extra-actions.scss
- src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
- src/bundle/Resources/views/themes/admin/content/widget/content_edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3475
**Requires:**
https://github.com/ibexa/workflow/pull/57
https://github.com/ibexa/taxonomy/pull/160
https://github.com/ibexa/scheduler/pull/68
https://github.com/ibexa/product-catalog/pull/819
> IBX-3475: Fixed close button padding in extra actions

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
…
| Tickets       | https://issues.ibexa.co/browse/IBX-3981
> IBX-3981: information on how many selected elements hide some functionalities

- src/bundle/Resources/public/js/scripts/admin.back.to.top.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3987
> IBX-3987: Go to top button overlaps with pagination in subitems list when using grid view

- src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4017
> IBX-4017: Fix meta_fields rendering

- src/bundle/Resources/views/themes/admin/ui/component/context_menu/context_menu.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4023
> IBX-4023: Hide 'more' menu button from context menu by default

- src/bundle/Resources/public/js/scripts/admin.input.text.js
- src/bundle/Resources/public/js/scripts/core/date.time.picker.js
- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4048
> IBX-4048: Restore clear button and calendar icon in date time input

- src/bundle/Resources/public/scss/_badges.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4060
**Requires:** https://github.com/ibexa/personalization/pull/189
> IBX-4060: Added nowrap to badges to avoid breaking line

- src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.selector.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_top.menu.search.input.scss
- src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3884
> IBX-3884: Missing hovers in Dropdowns - Top Bar UDW

- src/bundle/Resources/public/scss/_grid-view.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.js
| Tickets       | [IBX-4002](https://issues.ibexa.co/browse/IBX-4002)
> IBX-4002: Changed styles to show scroll on the correct element

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
- src/bundle/Resources/public/scss/_content-edit.scss
- src/bundle/Resources/public/scss/_content-type-edit.scss
- src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
- src/lib/Menu/ContentEditAnchorMenuBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4012
> IBX-4012: Moving to a form section does not show chosen section as active

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4120
> IBX-4120: fixed margin and padding for UDW list view

- src/bundle/Resources/translations/content_type.en.xliff
- src/bundle/Resources/translations/dropdown.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | -
Moved new translations from messages to more suitable domain. See https://github.com/ibexa/i18n/pull/20
> Fixed translations in ibexa/admin-ui

- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4183
> IBX-4183: Added more precise selector for hover efect of subitems view select

- src/lib/Behat/BrowserContext/ContentViewContext.php
- src/lib/Behat/Page/ContentViewPage.php
| Tickets       | [IBX-3729](https://issues.ibexa.co/browse/IBX-3729)
| Bug fix?      | tests
CommerceUserCreation scenario needs updating after changes from https://github.com/ibexa/installer/pull/85.
Companion PR: https://github.com/ibexa/commerce-admin-ui/pull/60
> [Behat] IBX-3729: Updated CommerceUserCreation scenario

- src/bundle/Resources/public/scss/_alerts.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4164
> IBX-4164: Fixed fill color for notifications icons

- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3177
> IBX-3177: Fixed margin left in location details view

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/js/scripts/core/draggable.js
| Tickets       | https://issues.ibexa.co/browse/IBX-4256
> IBX-4256: Drag and drop issues

- src/bundle/Resources/public/scss/_adaptive-filters.scss
- src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | (https://issues.ibexa.co/browse/IBX-3552)
Fix for focus box shadow of dropdown
> IBX-3552: updated focus for dropdown button

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4278
> IBX-4278: Missing hover on input text while hovering over icons inside

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| Tickets       |  [IBX-3562](https://issues.ibexa.co/browse/IBX-3562)
Added class `.ibexa-dropdown--expanded` and animation do caret icon
> IBX-3562: calendar day arrows

- src/lib/Behat/Component/Fields/User.php
Fixed error in userCreation.feature, which tend to occur during clicking 'Enabled' checkbox.
Example build with this error: https://github.com/ibexa/content/actions/runs/3483381711/jobs/5826807380
> [Behat] Added wait in userCreation.feature during user enabling

- src/lib/Behat/Page/ContentUpdateItemPage.php
- src/lib/Behat/Page/ContentViewPage.php
JIRA: https://issues.ibexa.co/browse/IBX-3842
Related: https://github.com/ibexa/product-catalog/pull/808 
This PR adjusts tests to work in the product catalog.
> [Behat] IBX-3842: Extend test scenarios for Products 

- src/bundle/Resources/public/scss/_links.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4061
Changes for link color to make it more precise
> IBX-4061: Added new modifiers to ibexa-link

- src/lib/Behat/Page/ContentTypeUpdatePage.php
This pr replaces closed https://github.com/ibexa/admin-ui/pull/650. It is possible that increased timeout might help with drag&drop errors.
> [Behat] Increased timeout for transition condition

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
- src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
- src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/view-switcher/view.switcher.js
| Tickets       | https://issues.ibexa.co/browse/IBX-4214
I added an additional css modifier `--switcher` for `<SimpleDropdown />` component.
 I extended the `<SimpleDropdown />` component with the `isSwitcher` parameter which allows to assign a css class with `--switcher` modifier
> IBX-4214: Fixed hover style

- src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
| Tickets       | [IBX-4439)](https://issues.ibexa.co/browse/IBX-4439)
fixed tooltip title change after expand & collapse
> IBX-4439: fixed tooltip title change after expand & collapse

- src/lib/Behat/Component/Table/TableRow.php
JIRA: https://issues.ibexa.co/browse/IBX-4409
This PR adds getCell method for usage in Currencies tests in https://github.com/ibexa/product-catalog/pull/861
> [Behat] IBX-4409: Implemented test scenarios for Currencies

- src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4734
> IBX-4734: Cannot close panel in PB by clicking on selected button

- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/translations/multi_file_upload.en.xliff
> Added missing translations

- src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4661
> IBX-4661: Double file upload in Image/ImageAsset/File

- src/bundle/Resources/public/js/scripts/core/date.time.picker.js
| Tickets       | https://issues.ibexa.co/browse/IBX-4834, https://issues.ibexa.co/browse/IBX-4846
**Note for QA**
This PR fixes two issues, please test both of them.
> IBX-4834: Fixed minute and hour listeners in flatpickr

- src/lib/Specification/AbstractSpecification.php
- src/lib/Specification/AndSpecification.php
- src/lib/Specification/NotSpecification.php
- src/lib/Specification/OrSpecification.php
- src/lib/Specification/SpecificationInterface.php
| Tickets       | [IBX-4918](https://issues.ibexa.co/browse/IBX-4918)
> IBX-4918: Moved Specification abstraction from AdminUi to Core

- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| Tickets       | [IBX-4925](https://issues.ibexa.co/browse/IBX-4925)
Udw fetched version if fast clicked button
> IBX-4925: Udw fetched version if fast clicked button

- src/bundle/Resources/public/js/scripts/admin.input.text.js
| Tickets       |  [IBX-4913](https://issues.ibexa.co/browse/IBX-4913)
Blank space cannot be added to product collection search
> IBX-4913: Blank space cannot be added to product collection search

- src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5013
> IBX-5013: Removed mergin from header in objectrelation fieldtype

- src/lib/Menu/ContentRightSidebarBuilder.php
- src/lib/Specification/Location/IsWithinCopySubtreeLimit.php
- tests/lib/Validator/Constraint/LocationIsWithinCopySubtreeLimitValidatorTest.php
Looks like bot failed to create a PR
Cross merge of https://github.com/ezsystems/ezplatform-admin-ui/pull/2085
> Merged branch '2.3' of ezsystems/ezplatform-admin-ui into 4.3

- src/bundle/Resources/public/scss/_backdrop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4343
> IBX-4343: PB timeline grey backdrop

- src/lib/Behat/Page/ContentUpdateItemPage.php
- src/lib/Behat/Page/UserUpdatePage.php
JIRA: https://issues.ibexa.co/browse/IBX-4889 
This PR changes the getRoute method of ContentUpdateItemPage to use `ibexa.content.create.proxy`
> [Behat] IBX-4889: Cover file upload with a Visual Test

- src/bundle/Resources/public/js/scripts/user_password.change.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5197
> IBX-5197: [Change password] Error messages stack on submit

- src/bundle/Resources/public/scss/_extra-actions.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_translation.selector.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5240
> IBX-5240: Fixed translation edit widget

- src/bundle/Resources/public/scss/_adaptive-filters.scss
- src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4945
> IBX-4945: Orders list filtering

- src/bundle/Resources/public/scss/_badges.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4953
> IBX-4953: badge custom color style

- src/bundle/Resources/public/scss/_summary-tile.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/views/themes/admin/ui/component/summary-tile/summary-tile.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/summary_tile/summary_tile.html.twig
| Question                 | Answer                                              |
|--------------------------|-----------------------------------------------------|
| **JIRA issue**           | https://issues.ibexa.co/browse/IBX-5357 |
| **Type**                 | improvement                             |
| **Target Ibexa version** | 4.5          |
| **BC breaks**            | no                                              |
Related PRs:
- https://github.com/ibexa/order-management/pull/12
> IBX-5357: Introduce summary tile component

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
- src/bundle/Resources/public/scss/_anchor-navigation.scss
- src/bundle/Resources/public/scss/_badges.scss
- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5416
These are same changes as in https://github.com/ibexa/admin-ui/pull/736 but on different branch name (changed ticket id)
> IBX-5416: Added ghost badge modifier; Fix navigation scroll height

- src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1961
> IBX-1961: Added extensibility point to edit header

- src/bundle/Resources/public/scss/_details.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3482
> IBX-3482: Fixed position of actions in details header

- src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5518
> IBX-5518: Add tag block in page_title twig component

- src/bundle/Resources/public/js/scripts/admin.picker.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5561
> IBX-5561: [Payments] Cannot use Created at/Updated at filter

- src/bundle/Resources/public/scss/_double-input-range-filter.scss
- src/bundle/Resources/public/scss/_double-input-range.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/views/themes/admin/ui/component/double_input_range/double_input_range.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5546
> IBX-5546: Add double input range filter

- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | [IBX-5633](https://issues.ibexa.co/browse/IBX-5633)
Dropdown classes trim fix
> IBX-5633: Dropdown classes trim fix

- src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5653
> IBX-5653: [Search] Theres JS error on Select subtree UDW confirm action

- src/bundle/Resources/translations/dropdown.en.xliff
- src/bundle/Resources/translations/trash.en.xliff
- src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
- src/lib/Form/Type/Search/TrashSearchType.php
| Tickets       | https://issues.ibexa.co/browse/IBX-5697
> IBX-5697: [Dropdown] Change default placeholder to "All"

- src/lib/Behat/Page/ContentTypeUpdatePage.php
Failure: https://github.com/ibexa/commerce/actions/runs/4855245728/jobs/8653777155
JIRA: https://issues.ibexa.co/browse/IBX-3098
Tested in https://github.com/ibexa/experience/pull/170
This solution will try to expand the fieldtype until it succeeds - making the test more stable, as currently it's failing too often.
> [Behat] Retry expanding the last fieldtype

- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5660
> IBX-5660: Added option to position headline items

- src/bundle/Resources/public/scss/_collapse.scss
- src/bundle/Resources/views/themes/admin/ui/component/collapse.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3528
> IBX-3528: Fixed collapse toggler rotation

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_filters.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/content-type-selector/content.type.selector.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5717
> IBX-5717: Content type filter values in UDW have minor CSS issues

- src/bundle/Resources/public/scss/_extra-actions.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5737
> IBX-5737: Scroll in extra actions is in wrong place

- src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5789
> IBX-5789: [BO]: checkbox display broken when language is set to french

- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/views/themes/admin/language/index.html.twig
- src/bundle/Resources/views/themes/admin/language/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5455
> IBX-5455: Checkboxes are not aligned with other data in Languages & Currencies tabs

- features/personas/AddLocation.feature
- features/personas/ChangePassword.feature
- features/personas/SubtreeEditor.feature
- features/standard/Authentication.feature
- features/standard/Autosave.feature
- features/standard/Bookmark.feature
- features/standard/ContentDraft.feature
- features/standard/ContentManagement.feature
- features/standard/ContentPreview.feature
- features/standard/ContentTranslation.feature
- features/standard/ContentType.feature
- features/standard/ContentTypeGroup.feature
- features/standard/Languages.feature
- features/standard/ObjectStates.feature
- features/standard/Roles.feature
- features/standard/SearchContent.feature
- features/standard/Sections.feature
- features/standard/SystemInfo.feature
- features/standard/Trash.feature
- features/standard/UserCreation.feature
- features/standard/fields/contentQuery.feature
- features/standard/fields/date.feature
- features/standard/fields/map.feature
- features/standard/fields/media.feature
- features/standard/fields/other.feature
- features/standard/fields/relations.feature
- features/standard/fields/text.feature
| Tickets       | [IBX-5798](https://issues.ibexa.co/browse/IBX-5798)
| Bug fix?      | tests
> [Behat] IBX-5798: Ibexa Headless regression tests

- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5879
> IBX-5879: Fixed startingLocationId and rootLocationId in UDW

- src/bundle/Resources/public/scss/_edit-header.scss
- src/bundle/Resources/public/scss/_main-container.scss
> Revert "IBX-5784: CkEditor toolbar overflow fix"

- src/bundle/Resources/views/themes/admin/trash/list.html.twig
| Tickets       | [IBX-5945](https://issues.ibexa.co/browse/IBX-5945)
Simplifying changed condition should be enough to handle all parameters.
> IBX-5945: Fix Trash's pagination

- src/lib/Behat/Component/Fields/User.php
Upmerging https://github.com/ibexa/admin-ui/pull/786 to 4.5 and 4.6
It has been reverted during merge-up because it seemed not neccessary, but after latest failure wave it looks like it is actually needed 😄
> [Behat] IBX-4482 Fix for toggle button enabled (#786)

- src/lib/Behat/Component/Fields/ContentRelationSingle.php
Added timeout 5s for selecting content relation single.
> [Behat] Added timeout for select content relation single

- features/standard/ContentType.feature
- src/bundle/Resources/translations/menu.en.xliff
- src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
- src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4676
> IBX-4676: Update label for button 'Discard changes' [edit content type]

- src/bundle/Resources/public/scss/_tag.scss
| Tickets       | [IBX-5999](https://issues.ibexa.co/browse/IBX-5999)
Tag styles updated
> IBX-5999: Tag styles updated

- src/bundle/Resources/translations/content_url.en.xliff
- src/bundle/Resources/views/themes/admin/content/tab/url/custom_urls_table.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/url/system_urls_table.html.twig
| Tickets       | [IBX-2766](https://issues.ibexa.co/browse/IBX-2766)
This PR makes the custom URL tab more generic
> IBX-2766: Made custom url aliases tab more generic

- src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
> removed duplicated class in form_fields.html.twig file

- src/lib/Behat/BrowserContext/NotificationContext.php
- src/lib/Behat/Component/Notification.php
> JIRA: [IBX-5755](https://issues.ibexa.co/browse/IBX-5755)
I've added new test scenarios for product variants and product type to handle part of the system that hasn't been handled yet. Besides that I have also added missing test scenarios for Products (editing and deleting product from product page).
Related PR: https://github.com/ibexa/product-catalog/pull/978
> [Behat] IBX-5755 Added test scenarios for product variants

- src/bundle/Resources/public/scss/_filters.scss
- src/bundle/Resources/public/scss/_trash-search-form.scss
| Tickets       | [IBX-5979](https://issues.ibexa.co/browse/IBX-5979)
> IBX-5979: Fixed creator filter overlapped by table elements in trash list

- src/bundle/Resources/public/scss/_field-group.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4325
> IBX-4325: Added min-height for field definition header

- src/bundle/Resources/views/themes/admin/user/invitation/modal.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5145
Used in:
https://github.com/ibexa/corporate-account/pull/206
> IBX-5145: Modified invitation modal for easier extending

- src/bundle/Controller/ContentTypeController.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6214
> IBX-6214: default action set to publishContentType

- src/lib/Behat/Component/Fields/RichText.php
This is a simple fix that hopefully will solve https://issues.ibexa.co/browse/IBX-6280
We try entering the richtext value 3 times, hoping that one of them is correct.
Regression build: https://github.com/ibexa/experience/pull/226
> IBX-6280: [Behat] Retry entering Richtext value

- src/lib/Behat/BrowserContext/ContentActionsMenuContext.php
- src/lib/Behat/BrowserContext/ContentUpdateContext.php
- src/lib/Behat/Component/CreateNewPopup.php
- src/lib/Behat/Component/Fields/FieldTypeComponent.php
- src/lib/Behat/Page/ContentUpdateItemPage.php
Backport of https://github.com/ibexa/admin-ui/pull/876 to 4.5
> IBX-5754: Behat tests for Taxonomy

- .github/workflows/ci.yaml
- composer.json
- phpstan-baseline.neon
- phpstan.neon
- src/lib/Behat/Component/ContentItemAdminPreview.php
This PR adds PHPStan to our admin-ui package. PHPStan is a tool that helps catch bugs early by analyzing our code.
> Introduced PHP Stan

- .github/workflows/ci.yaml
- composer.json
- phpstan-baseline-7.4.neon
- phpstan-baseline-8.0.neon
- phpstan-baseline.neon
- phpstan-baseline.neon.php
- phpstan.neon
- src/lib/Behat/Component/ContentItemAdminPreview.php
Added PHPStan to version 4.5, which was previously omitted.
Most of these changes are already present on `main` (4.6) branch. In case of one PHP code change, the same solution was used as in `main`.
> Added PHPStan for 4.5 version

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/public/js/scripts/admin.search.sorting.js
- src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
| Tickets       |  [IBX-6338](https://issues.ibexa.co/browse/IBX-6338) 
| License       | [GPL-2.0](https://github.com/ibexa/search/blob/main/LICENSE)
Depends on https://github.com/ibexa/search/pull/25
> IBX-6338: As an Editor I'd like to sort the list of search results

- src/lib/Behat/Component/ContentTypePicker.php
- src/lib/Behat/Component/UniversalDiscoveryWidget.php
JIRA: https://issues.ibexa.co/browse/IBX-6505
This PR extends UDW code with create content on the fly
> [Behat] IBX-6505: Covered Content on the Fly with Visual Test

- src/bundle/Resources/public/scss/_mixins.scss
- src/bundle/Resources/public/scss/mixins/_spinner.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6454
> IBX-6454: Added new css spinner mixin

- src/bundle/Resources/public/scss/_main-container.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6378
> IBX-6378: Create content on the fly view is not styled properly

- phpstan-baseline.neon
- src/lib/Menu/ContentEditAnchorMenuBuilder.php
- src/lib/Menu/ContentTypeEditAnchorMenuBuilder.php
- tests/lib/Form/Data/FormMapper/ContentTypeDraftMapperTest.php
This PR fixes issues detected by PHPStan after incoming changes from ibexa/core.
> Fixed PHPStan errors after upstream update

- src/bundle/Resources/views/themes/admin/ui/breadcrumbs.html.twig
| Tickets       | [IBX-6638](https://issues.ibexa.co/browse/IBX-6638)
> IBX-6638: Provided tooltips for breadcrumbs in the Content View

- .github/workflows/browser-tests.yaml
This PR adds basic Page Builder tests as part of AdminUI test suite
> Add page builder tests

- src/lib/Behat/Component/Fields/ContentRelationSingle.php
- src/lib/Behat/Component/SubItemsList.php
- src/lib/Behat/Component/Table/TableRow.php
- src/lib/Behat/Page/ContentTypeUpdatePage.php
- src/lib/Behat/Page/RoleUpdatePage.php
Refactors code to take advatnage of https://github.com/ibexa/behat/pull/85
> Behat actions usage

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-6249](https://issues.ibexa.co/browse/IBX-6249) |
| **Type**                                   | improvement |
| **Target Ibexa version** | `v4.6`  |
| **BC breaks**                          | no |
Create toolbox with structure view
> IBX-6249: Create toolbox with structure view & Dropzones update

- src/bundle/Resources/public/scss/_field-group.scss
- src/bundle/Resources/public/scss/_page-title.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6459
> IBX-6459: Fixed eztext preview in content structure

- src/bundle/Resources/public/js/scripts/core/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6517
> IBX-6517: Search form for activity log

- src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6475
- https://github.com/ibexa/taxonomy/pull/243
> IBX-6475: fix transaltions

- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Added `brand` and `global_search` blocks to main layout.
> Added brand and global_search blocks to main layout

- features/standard/ObjectStates.feature
This tag should have been removed before merging, but wasn't (my mistake).
> [Behat] Removed test tag

- src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6845
> IBX-6845: Matrix field columns table header not present until saved

- src/bundle/Resources/config/services/rest.yaml
- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
> Fixed typo in FieldDefinitionCreate Content-Type header

- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/components.yaml
- src/bundle/Resources/config/services/components/layout.yaml
- src/bundle/Resources/config/services/search.yaml
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
- src/bundle/Resources/views/themes/admin/ui/user_menu.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6997
> IBX-6997: Introduced user-menu components group

- src/bundle/Resources/public/scss/_badges.scss
- src/bundle/Resources/public/scss/_page-title.scss
- src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6985
> IBX-6985: Product code badge at wrong position

- src/bundle/Resources/views/themes/admin/content_type/edit_base.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7061
> IBX-7061: Cannot switching filed groups on create and edit PT form

- src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
| Tickets       | [IBX-6866](https://issues.ibexa.co/browse/IBX-6866)
Added class to page title
> IBX-6866: Added class to page title

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6550
> IBX-6550: Global redesign of placeholder for trees

- features/personas/ChangePassword.feature
- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/translations/ibexa_user_settings.en.xliff
- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
- src/lib/Behat/Page/UserSettingsPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6977
> IBX-6977: Redesigned user settings page

- src/lib/Tab/LocationView/AuthorsTab.php
- src/lib/Tab/LocationView/RelationsTab.php
- src/lib/Tab/LocationView/TranslationsTab.php
- src/lib/Tab/LocationView/UrlsTab.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6750
> IBX-6750: [Smart mode] As the User I want to display tabs in Content items in different order by default

- src/bundle/Resources/config/universal_discovery_widget.yaml
| Tickets       | https://issues.ibexa.co/browse/IBX-7077
> IBX-7077: Add image_picker UDW config

- src/bundle/Resources/public/js/scripts/embedded.item.actions.js
- src/bundle/Resources/public/scss/_embedded-item-actions.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/bundle/Resources/public/scss/mixins/_spinner.scss
- src/bundle/Resources/views/themes/admin/ui/component/embedded_item_actions/embedded_item_actions.html.twig
| Tickets       | [IBX-6549](https://issues.ibexa.co/browse/IBX-6549) |
Implemeted redesign loader
> IBX-6549: Implemeted redesign loader

- src/lib/Form/Type/Event/ContentCreateContentTypeChoiceLoaderEvent.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7143 
> Added possibility to remove ContentTypeGroup from the list

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-7155
> IBX-7155: Updated column width and padding in UDW

- phpstan-baseline.neon
- src/lib/View/Filter/AdminSearchViewFilter.php
> Fixed PHPStan issues

- src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
> Removed duplicated type attribute in locations/tab.html.twig

- src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7145
> IBX-7145: Fixed hardcoded restricted content type ids/language codes

- src/bundle/Resources/public/scss/_search-criteria-tags.scss
- src/bundle/Resources/public/scss/_search-form.scss
- src/bundle/Resources/translations/ibexa_search.en.xliff
- src/bundle/Resources/views/themes/admin/ui/search/criteria_tags.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/spellcheck.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6649
| Bug fix?      |no
Added "Did you mean X?" in global search. **PR depends on** 
* https://github.com/ibexa/core/pull/276
* https://github.com/ibexa/solr/pull/52
* https://github.com/ibexa/search/pull/32
* https://github.com/ibexa/elasticsearch/pull/28
_Only to demonstrate feature. I need design & frontend teams help here :wink:_
> IBX-6649: Added support for spell checking

- src/bundle/Resources/public/js/scripts/core/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7250
> IBX-7250: [Site context] Long site name should be truncated with '...'

- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
| Tickets       | [IBX-7122](https://issues.ibexa.co/browse/IBX-7122)
> IBX-7122: Hidden hide/show toggler

- src/bundle/ui-dev/src/modules/common/input/filter.search.js
- src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js
- src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/browse.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
> Fixed langs extract

- src/bundle/Resources/public/js/scripts/admin.multilevel.popup.menu.js
- src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
| Tickets       | [IBX-7337](https://issues.ibexa.co/browse/IBX-7337) |
Added possibility to change poppup position when creating
> IBX-7337: Added possibility to change poppup position when creating

- src/bundle/Resources/config/services/ui_config/common.yaml
- src/lib/UI/Config/Provider/FocusMode.php
> Exposed Focus Mode status in adminUI config

- src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
- src/bundle/ui-dev/src/modules/sub-items/components/view-columns-toggler/view.columns.toggler.js
- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/view-switcher/view.switcher.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7356
> IBX-7356: [Sub-items] - disable Columns settings in Grid view

- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7415
> IBX-7415: [Subitems] As a User I want to see columns dependant on focus mode

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       |[IBX-7222](https://issues.ibexa.co/browse/IBX-7222)
Added 4px line to dropzone placeholder
> IBX-7222: Added 4px line to dropzone placeholder

- src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7399
> IBX-7399: Hidden tabs toggles in location view

- src/bundle/Resources/views/themes/admin/content/tab/policies/tab.html.twig
- src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
| Tickets       | [IBX-7454](https://issues.ibexa.co/browse/IBX-7454?filter=18027), [IBX-7075](https://issues.ibexa.co/browse/IBX-7075)
> IBX-7454, IBX-7075: Fixed misaligned limitations on policies list

- src/bundle/Resources/public/scss/_anchor-navigation.scss
- src/bundle/Resources/public/scss/_main-container.scss
- src/bundle/Resources/views/themes/admin/content_type/content_type_group/base.html.twig
- src/bundle/Resources/views/themes/admin/language/base.html.twig
- src/bundle/Resources/views/themes/admin/ui/edit_base.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7302
| BC breaks?    |  no
Related PRs:
- https://github.com/ibexa/payment/pull/129
- https://github.com/ibexa/product-catalog/pull/1113
- https://github.com/ibexa/shipping/pull/59
> IBX-7302: No left sidebar when no anchor menu items

- src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
| Tickets       | [IBX-7130](https://issues.ibexa.co/browse/IBX-7130)
> IBX-7130: Redirect back to user setting after discard password update

- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
| Tickets       | [IBX-7121](https://issues.ibexa.co/browse/IBX-7121)
> IBX-7121: Added asterisks in password user settings

- src/bundle/Resources/public/js/scripts/admin.search.autocomplete.content.js
- src/bundle/Resources/public/scss/_global-search.scss
- src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_item.html.twig
- src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_template.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7154
> IBX-7154: Fixed breadcrumb styles in autocomplete

- src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
- src/bundle/ui-dev/src/modules/universal-discovery/components/actions-menu/actions.menu.js
| **JIRA issue**       | [IBX-6747](https://issues.ibexa.co/browse/IBX-6747) |
> IBX-6747: Changed UDW cancel action label to "Discard"

- src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
| **JIRA issue**       | [IBX-7089](https://issues.ibexa.co/browse/IBX-7089) |
> IBX-7089: Aligned relation list item actions to the right

- src/bundle/Resources/public/scss/_filters.scss
| **JIRA issue**       | [IBX-6539](https://issues.ibexa.co/browse/IBX-6539) |
> IBX-6539: Fixed "Last modified" and "Created" filters style in global search

- src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
| **JIRA issue**       | [IBX-7128](https://issues.ibexa.co/browse/IBX-7128)   |
| Before | After |
|--------|--------|
| ![image](https://github.com/ibexa/admin-ui/assets/211967/e14cc84f-1507-45d8-97ba-dbb25f9aca92) | ![image](https://github.com/ibexa/admin-ui/assets/211967/040618b0-ff7c-491a-9525-e377be6d2f87) …
> IBX-7128: Fixed inconsistent section header size in user settings view

- src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7271
> IBX-7271: Missing suggestions while creating content in COFT

- src/bundle/Resources/public/scss/_tabs.scss
| Tickets       | [IBX-7459](https://issues.ibexa.co/browse/IBX-7459)
Tabs states updated:
* hover
* enabled
> IBX-7459: Tabs states updated

- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7052
I've added extra comment to task about design/feeling after this fix on that particular screen
> IBX-7052: UDW gets closed after switching Bookmarks view into grid view

- phpstan-baseline.neon
- src/bundle/Resources/translations/ibexa_menu.en.xliff
| **JIRA issue**       | [IBX-7410](https://issues.ibexa.co/browse/IBX-7410) |
> IBX-7410: Changed "View profile" to "Profile"

- src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
- src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig
- src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| **JIRA issue**       | [IBX-6680](https://issues.ibexa.co/browse/IBX-6680) |
#1094 backport
> [Backport] IBX-6680: Disabled add field action in field definition form when translating content type 

- src/bundle/DependencyInjection/Configuration/Parser/UserProfile.php
- src/bundle/Resources/config/ezplatform_default_settings.yaml
| **JIRA issue**       | [IBX-7491](https://issues.ibexa.co/browse/IBX-7491) |
Fixed typo and default configuration.
> IBX-7491: User profile is not available for Editors

- src/bundle/Resources/public/scss/_double-input-range.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7496 |
> IBX-7496: Fix centering double input separator

- features/standard/ContentType.feature
- src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
- src/bundle/Resources/public/scss/_buttons.scss
- src/bundle/Resources/public/scss/_split-button.scss
- src/bundle/Resources/translations/ibexa_menu.en.xliff
- src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
- src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
- src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_branch.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_group.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/split_btn/split_btn.html.twig
- src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
- src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6724
| Doc needed?   | yes (news screenshots and maybe something else?)
Related PRs:
- https://github.com/ibexa/page-builder/pull/317
- https://github.com/ibexa/form-builder/pull/110
- https://github.com/ibexa/image-editor/pull/87
- https://github.com/ibexa/taxonomy/pull/257
- https://github.com/ibexa/corporate-account/pull/228
- https://github.com/ibexa/user/pull/68
- https://github.com/ibexa/payment/pull/131
- https://github.com/ibexa/shipping/pull/60
- https://github.com/ibexa/product-catalog/pull/1116
> IBX-6724: Simplify context menus

- src/bundle/Resources/views/themes/admin/account/settings/update_datetime_format.html.twig
| **JIRA issue**       | [IBX-7549](https://issues.ibexa.co/browse/IBX-7549) |
> IBX-7549: Fixed wrong icon for data & time preview message User Settings > Location > Edit

- src/bundle/Resources/translations/ibexa_role.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/ui/modal/bulk_delete_confirmation.html.twig
- src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
| **JIRA issue**       | [IBX-7551](https://issues.ibexa.co/browse/IBX-7551) |
> IBX-7551: Fixed delete button label in role unassign confirmation modal

- src/bundle/Resources/public/scss/_edit-header.scss
- src/bundle/Resources/translations/ibexa_user_change_password.en.xliff
- src/bundle/Resources/translations/ibexa_user_settings.en.xliff
- src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
- src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
- src/lib/Behat/Page/ChangePasswordPage.php
- src/lib/Behat/Page/UserSettingsPage.php
| Tickets       |  [IBX-7119](https://issues.ibexa.co/browse/IBX-7119), [IBX-7171](https://issues.ibexa.co/browse/IBX-7171), [IBX-7123](https://issues.ibexa.co/browse/IBX-7123)
The issue with the test is missing the title parameter which is introduced here https://github.com/ibexa/user/pull/67
> IBX-7119, IBX-7171, IBX-7123: Corrected Headers inconsistency in Account settings

- src/bundle/Resources/public/scss/ibexa.scss
| **JIRA issue**       | [IBX-7598](https://issues.ibexa.co/browse/IBX-7598) |
> IBX-7598: Added missing import for scss file

- src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
| **JIRA issue**       | [IBX-7493](https://issues.ibexa.co/browse/IBX-7493) |
With: https://github.com/ibexa/activity-log/pull/69
> IBX-7493: Dropped dependency on user variable in user_thumbnail

- src/bundle/Resources/translations/ibexa_menu.en.xliff
- src/bundle/Resources/translations/ibexa_user_settings.en.xliff
- src/lib/Behat/Page/ContentViewPage.php
- src/lib/Menu/ContentRightSidebarBuilder.php
| **JIRA issue**       | [IBX-7168](https://issues.ibexa.co/browse/IBX-7168) |
> IBX-7168: Changed label to `create user` based on parent location

- src/bundle/Resources/public/scss/_inputs.scss
| **JIRA issue**       | [IBX-7604](https://issues.ibexa.co/browse/IBX-7604) |
Companion PR: https://github.com/ibexa/product-catalog/pull/1131
> IBX-7604: Fixed checkbox toggler

- src/bundle/Resources/public/js/scripts/admin.context.menu.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7153 |
> IBX-7153: Fix context menu popup buttons disabled state

- src/bundle/Resources/public/js/scripts/helpers/browser.helper.js
- src/bundle/Resources/public/js/scripts/helpers/config.loader.js
- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
- src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**       | [IBX-7552](https://issues.ibexa.co/browse/IBX-7552) |
Doubled tooltip on safari
> IBX-7552: Doubled tooltip on safari

- src/bundle/Resources/public/scss/_user-thumbnail.scss
| **JIRA issue**       | [IBX-7495](https://issues.ibexa.co/browse/IBX-7495) |
> For 4.6 IBX-7495 Fix user profile image width responsive, rebased PR 1109 for main branch. 

- src/bundle/Resources/public/scss/_preview.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7191 |
> IBX-7191: Fix clickable preview - disabled pointer events

- src/bundle/Resources/public/scss/_search-form.scss
- src/bundle/Resources/public/scss/mixins/_search-form-no-results.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
| **JIRA issue**       | [IBX-7680](https://issues.ibexa.co/browse/IBX-7680) |
Needed to https://github.com/ibexa/activity-log/pull/81
> IBX-7680:  Wrong empty screen after no search results

- src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7189 |
> IBX-7189: [Sub-items] Background for a white row in a table changes to gray when clicked on

- src/bundle/Resources/public/js/scripts/core/adaptive.items.js
| **JIRA issue**       | [IBX-7738](https://issues.ibexa.co/browse/IBX-7738) |
Changed query selector string for selector anchor
> IBX-7738: Changed query selector string for selector anchor

- src/bundle/Resources/public/scss/_inputs.scss
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | https://issues.ibexa.co/browse/IBX-7644 |
| **Type**                                   | bug |
| **Target Ibexa version** | `v4.6` |
| **BC breaks**                          | no |
> IBX-7644: Customizable dashboard, Page Builder - Select / switching layout

- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/public/scss/_details.scss
- src/bundle/Resources/public/scss/_user-profile.scss
- src/bundle/Resources/translations/ibexa_admin_ui.en.xliff
- src/bundle/Resources/views/themes/admin/account/profile/view.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
- src/bundle/ui-dev/src/modules/common/alert/alert.js
| **JIRA issue**       | [IBX-7555](https://issues.ibexa.co/browse/IBX-7555) |
User profile updated UI for summary:
- Updated alerts/notifcations with new design: https://www.figma.com/file/4sbNQyNLhFFwxWDH89Rf9X/%F0%9F%9F%A2-Ibexa-Design-System?node-id=1620%3A66516&mode=dev
> IBX-7555: User profile updated UI for summary

- src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
| **JIRA issue**       | [IBX-7526](https://issues.ibexa.co/browse/IBX-7526) |
Added cutomizable block name to content blocks
> IBX-7526: Added cutomizable block name to content blocks

- src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7802 |
> IBX-7802: Fix React multi-select dropdown checkbox lack of onChange prop error

- src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
- src/bundle/Resources/public/js/scripts/sidebar/instant.filter.js
- src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
- src/bundle/Resources/views/themes/admin/content/widget/instant_filter_group_template.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7671 |
> IBX-7671: [Content structure] Two different behaviour by clicking create from context menu and from action main button

- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7196 |
> IBX-7196: Fix distraction free mode btn styling in richtext editor

- src/bundle/Resources/translations/ibexa_admin_ui.en.xliff
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| **JIRA issue**       |https://issues.ibexa.co/browse/IBX-7214 |
> IBX-7214: Remove distraction free mode exit btn unnecessary tooltip

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/views/themes/admin/account/reset_password/index.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7540 |
> IBX-7540: [Password reset form] Buttons to clear input and discover password does not work

- src/bundle/Resources/public/scss/_buttons.scss
| **JIRA issue**       | [IBX-7645](https://issues.ibexa.co/browse/IBX-7645) |
Added secondary-dark btn
> IBX-7645: Added secondary-dark btn

- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7194|
PB:
Article:
> IBX-7194: Fix spacing in distraction free mode

- src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
- src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7027 |
> IBX-7027: Publish later button stays visible after choosing it

- src/bundle/Resources/public/scss/_header-user-menu.scss
- src/bundle/Resources/public/scss/_popup-menu.scss
- src/bundle/Resources/views/themes/admin/ui/focus_mode_form.html.twig
- src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7613 |
> IBX-7613: header-user-menu UI fixes

- src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7185 |
> IBX-7185: Fix subitems upload refresh

- src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
| **JIRA issue**       | [IBX-7810](https://issues.ibexa.co/browse/IBX-7810) |
Fixed type error while validating the blocks
> IBX-7810: Fixed type error while validating the blocks

- src/bundle/Resources/public/js/scripts/admin.notifications.js
- src/bundle/Resources/public/scss/_alerts.scss
- src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
- src/bundle/ui-dev/src/modules/common/alert/alert.js
| **JIRA issue**       | [IBX-7781](https://issues.ibexa.co/browse/IBX-7781) |
| **Type**             | Improvement                                                   |
Upgraded toast notifications
> IBX-7781: Upgraded toast notifications

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/account/reset_password/confirmation_page.html.twig
| **JIRA issue**       | [IBX-7870](https://issues.ibexa.co/browse/IBX-7870) |
| **Target version**   | `v4.5`, `4.6`                                                |
| **Needs**       | https://github.com/ibexa/user/pull/75 |
> IBX-7870: Fixed an old product name in "Change password" screen

- src/bundle/Controller/ContentTypeController.php
| **JIRA issue**       | [IBX-7914](https://issues.ibexa.co/browse/IBX-7914) |
| **Depends**       |  https://github.com/ibexa/admin-ui/pull/1201#issue-2175745833  |
Will be used to overwrite part of the template by the dashboard package to change breadcrumbs
> IBX-7914: Added possibility to use another template

- src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js
| **JIRA issue**       | [IBX-7856](https://issues.ibexa.co/browse/IBX-7856) |
Added possibility to add tag with Enter
> IBX-7856: Added possibility to add tag with Enter

- src/bundle/Resources/public/scss/ui/modules/common/thumbnail.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7607 |
> IBX-7607: [Sub-items] User avatar is misaligned

- src/bundle/Resources/config/default_parameters.yaml
- src/bundle/Resources/config/services/ui_config/common.yaml
- src/lib/UI/Config/Provider/Module/DamWidget.php
- tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| **JIRA issue**       | [IBX-7981](https://issues.ibexa.co/browse/IBX-7981) |
This PR adds folder configuration that will be used by DAM widget to simple folder managing, inline creating and editing folder name. Configured parameters will be used in rest request to create / update folder content item. …
> IBX-7981: [DAM] Added folder configuration

- src/bundle/Resources/public/scss/_anchor-navigation.scss
- src/bundle/Resources/translations/ibexa_fields_groups.en.xliff
- src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
- src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
- src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/section_group.html.twig
| **JIRA issue**       | [IBX-7989](https://issues.ibexa.co/browse/IBX-7989) |
Related to: https://github.com/ibexa/page-builder/pull/362
> IBX-7989: Unable to access content group fields in Page Builder interface form view

- src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| :ticket: Issue | IBX-7627 |
Implemented theme colors for toolbox
> IBX-7627: Implemented theme colors for toolbox

- src/bundle/Resources/public/img/ibexa-empty-graph.svg
> IBX-8086: Updated infographic for empty graph

- src/lib/REST/Value/ContentTree/NodeExtendedInfo.php
- tests/integration/AdminUiIbexaTestKernel.php
Ref: https://github.com/ibexa/admin-ui/actions/runs/8630425338/job/23657279878
> Fixed merge 4.5 into 4.6

- src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
| :ticket: Issue | https://issues.ibexa.co/browse/IBX-8009 |
> IBX-8009: Unnecessary tooltips in udw bookmarks

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
- src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
| :ticket: Issue | [IBX-7839](https://issues.ibexa.co/browse/IBX-7839) |
Fixed loading items when scrolling
> IBX-7839: Fixed loading items when scrolling

- phpstan-baseline.neon
- src/bundle/Controller/ContentViewController.php
- src/bundle/Resources/config/ezplatform_default_settings.yaml
- src/bundle/Resources/views/themes/admin/content/location_view.html.twig
- src/bundle/Resources/views/themes/admin/content/tab/relations/tab.html.twig
- src/lib/Pagination/Pagerfanta/RelationAdapter.php
- src/lib/Tab/LocationView/RelationsTab.php
- src/lib/UI/Dataset/RelationListDataset.php
| **JIRA issue**       | [IBX-7833](https://issues.ibexa.co/browse/IBX-7833) |
Depends on https://github.com/ibexa/core/pull/343
Regressions test: https://github.com/ibexa/commerce/pull/724
- [] Provided automated test coverage.
> IBX-7833: Added pagination to relation tab

- src/lib/Behat/Page/AdminUpdateItemPage.php
| :ticket: Issue | IBX-7537 |
https://github.com/ibexa/product-catalog/pull/1128
This PR expands `\Ibexa\AdminUi\Behat\Page\AdminUpdateItemPage::getField` by textarea fields. With this change we can fill the Description field in the attribute creation form.
> IBX-7537: Expanded AdminUpdateItemPage by textarea input

- src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7949 |
| **Type**             | feature                                                   |
> IBX-7949: Added extensibility point for app switcher

- src/bundle/Resources/public/scss/_empty-chart.scss
| **JIRA issue**       | [IBX-7699](https://issues.ibexa.co/browse/IBX-7699) |
Empty chart state updated
> IBX-7699: Empty chart state updated

- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/views/themes/admin/account/forgot_password/mail.html.twig
| :ticket: Issue |[IBX-8253](https://issues.ibexa.co/browse/IBX-8253) |
> IBX-8253: Replace eZ Platform to Ibexa DXP in forgot password mail

- docs/field-type-validator-usage.md
- src/bundle/Resources/public/js/scripts/core/toggle.button.js
- src/bundle/Resources/public/js/scripts/toggle.button.state.toggle.js
- src/bundle/Resources/public/scss/_flatpickr.scss
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
| :ticket: Issue | [IBX-8144](https://issues.ibexa.co/browse/IBX-8144) |
> IBX-8144: [Rebranding] Remove compatibility layer from webpack encore

- src/bundle/Resources/public/scss/_main-container.scss
> IBX-8367: Fixed extra line at the bottom of the page

- src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
> IBX-8360: Removed event listener for drop and dragover when showing upload popup

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
- src/bundle/Resources/public/scss/_main-menu.scss
- src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
| :ticket: Issue | [IBX-8449](https://issues.ibexa.co/browse/IBX-8449) |
> IBX-8449: [Main menu] Selected area of second level menu item changes after expanding/collapsing

- src/lib/Behat/Component/LeftMenu.php
| :ticket: Issue | IBX-8216 |
- https://github.com/ibexa/visual-testing/pull/47
This PR adds function to toggle second level menu, needed for Focus mode Visual Test
> [Behat] IBX-8216: As a QA I want to cover Focus mode with a Visual Test

- src/bundle/Resources/public/js/scripts/admin.preview.js
- src/bundle/Resources/public/scss/_preview.scss
> IBX-8396: Moved pointer-events inside iframe body for scrolling to work properly

- src/bundle/Resources/public/scss/_global-search.scss
- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
| :ticket: Issue | IBX-7745 |
Fixed UI of global search accordance with figma https://www.figma.com/design/4sbNQyNLhFFwxWDH89Rf9X/%F0%9F%9F%A2-Ibexa-Design-System?node-id=2761-94382&t=n0iyXpq8TlXx0NLc-0
> IBX-7745: State for icon in search has wrong color

- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
> IBX-8545: Trash icon jump when uploading long name files

- tests/integration/AdminUiIbexaTestKernel.php
| :ticket: Issue | IBX-8137 |
- https://github.com/ibexa/user/pull/84
> IBX-8137: Dropped SwiftMailer in integration tests setup

- src/bundle/Resources/public/js/scripts/core/tag.view.select.js
- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
| :ticket: Issue | IBX-8321 |
Empty List:
List with tags:
> IBX-8321: Taxonomy entry assignment field: Gap when empty

- src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
> IBX-8670: Clear input icon is too big

- src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js
| :ticket: Issue | [IBX-8649](https://issues.ibexa.co/browse/IBX-8649) |
> IBX-8649: [UDW] can't reselect initial language

- src/bundle/ui-dev/src/modules/common/taggify/taggify.js
| :ticket: Issue | IBX-8672 |
- https://github.com/ibexa/assets-library-widget/pull/27 - build for standalone version
Problem occurs only in standalone version
> IBX-8672: User can add several tags with the same tag name

- src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js
- src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
- src/bundle/Resources/public/scss/fieldType/preview/_ezkeyword.scss
- src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| :ticket: Issue | [IBX-8584](https://issues.ibexa.co/browse/IBX-8584) |
> IBX-8584: [Tags] Long tag name is not properly displayed within the field tags

- src/bundle/Resources/public/scss/_details.scss
| :ticket: Issue | [IBX-7550](https://issues.ibexa.co/browse/IBX-7550) |
> IBX-7550: Text is not wrapped in Payment method details

- features/standard/UserProfile.feature
| :ticket: Issue | IBX-8636 |
This PR adds new tag - IbexaDXP (as it describes commercial editions, i.e. it excludes OSS) to user profile feature. In ibexa/behat repo we run admin-ui job on oss edition, Editor CT is enabled from headless edition, what causes a fail https://github.com/ibexa/behat/actions/runs/10279575369/job/28445202414
> [Behat] IBX-8636: Added new tag to user profile feature

- phpstan-baseline.neon
- tests/bundle/Templating/Twig/LimitationValueRenderingExtensionTest.php
Property was removed in the latest version: https://github.com/twigphp/Twig/commit/215f9880f1bbd10cf01317c4cb1b40a4ebb5590e
Ref: https://github.com/ibexa/admin-ui/actions/runs/10314303415/job/28552478910#step:7:27
> Fixed tests

- src/bundle/Resources/public/scss/_notifications-modal.scss
> IBX-8752: Notifications are misaligned on the list

- src/bundle/Resources/public/scss/_search-form.scss
> IBX-8640: Weird listing of translations in search result

- src/bundle/Resources/public/scss/_tabs.scss
> IBX-8709: Inconsistent padding in content view tabs

- src/lib/Behat/Component/ContentItemAdminPreview.php
- src/lib/Behat/Component/Fields/MapLocation.php
- src/lib/Behat/Page/ContentUpdateItemPage.php
> [PHPStan] Fixed errors after PHPStan update

- src/bundle/Resources/public/scss/_pagination.scss
- src/bundle/Resources/public/scss/mixins/_pagination.scss
| :ticket: Issue | IBX-8768 |
- https://github.com/ibexa/assets-library-widget/pull/35
Standalone versions and pagination in DXP in IP should be tested
> IBX-8768: Add specific prefixes to all CSS (standalone app)

- src/bundle/Resources/config/services/test/components.yaml
- src/lib/Behat/Component/FullView.php
- src/lib/Behat/Component/UpperMenu.php
| :ticket: Issue | IBX-8217 |
- https://github.com/ibexa/visual-testing/pull/49
This PR adds a new FullView component and a method to select site context from dropdown.
> [Behat] IBX-8217: As a QA I want to cover Full view with a Visual Test

- src/bundle/Resources/public/scss/_custom-url-form.scss
> IBX-8685: Create a new URL alias modal - too narrow spaces above labels

- src/bundle/Resources/translations/ibexa_locationview.en.xliff
- src/bundle/Resources/views/themes/admin/account/bookmarks/toggle_switch.html.twig
> IBX-8182: Uppercase letter for bookmarks for bookmarks tooltip

- src/bundle/Resources/public/scss/_middle-ellipsis.scss
| :ticket: Issue | [IBX-8717](https://issues.ibexa.co/browse/IBX-8717) |
> IBX-8717: Added display inline block to .ibexa-middle-ellipsis__name-ellipsized

- src/bundle/Resources/public/js/scripts/filters.action.btns.js
| :ticket: Issue | [IBX-8895](https://issues.ibexa.co/browse/IBX-8895) |
- https://github.com/ibexa/connector-ai/pull/41
This script is needed by search filters and will be utilized by a action configuration list in the `connector ai` package
> Added filter script

- src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
> IBX-8130: UDW gets closed while switching into Grid view

- src/lib/Behat/Component/CreateNewPopup.php
| :ticket: Issue | IBX-7780 |
This PR attempts to fix a common CI taxonomy error - https://github.com/ibexa/commerce/actions/runs/10975897460/job/30476324937
Commerce build -> https://github.com/ibexa/commerce/actions/runs/10936585920?pr=1048
> [Behat] IBX-7780: taxonomy behat fails fix

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezrichtext.html.twig
| :ticket: Issue | [IBX-8900](https://issues.ibexa.co/browse/IBX-8900) |
> IBX-8900: Integrate the AI actions for refine text in the editor

- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | [IBX-8955](https://issues.ibexa.co/browse/IBX-8955) |
> IBX-8955: [Page builder] 500 occurs after adding certain blocks

- src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
| :ticket: Issue | [IBX-8943](https://issues.ibexa.co/browse/IBX-8943) |
> IBX-8943: [Image field] Alternative text retains after deleting asset

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
> IBX-7447: Hide allowed extensions if no extensions are defined in image fieldtype

- src/lib/Form/Data/DateRangeData.php
- src/lib/Form/Type/DateRangeType.php
> IBX-9023: Add DateRangeData and DateRangeType

- src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
| :ticket: Issue | IBX-9028 |
Please make sure this fix still works: https://issues.ibexa.co/browse/IBX-8943
> IBX-9028: Fixed remove button in binary file field type

- composer.json
Removed duplicates from composer
> Removed duplicates from composer

- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| :ticket: Issue | IBX-8807|
The issue is caused by the fact that `componentDidUpdate` runs whilst the `loadPage` request is still running in `componentDidMount`.
> IBX-8807: Fixed multiplied GraphQL subitems request

- phpstan-baseline-8.3.neon
https://github.com/ibexa/admin-ui/actions/runs/11270624172
N/A
N/A
> Resolved phpstan errors on PHP 8.3

- src/bundle/Resources/public/js/scripts/helpers/request.helper.js
> IBX-8784: Proper handling for error messages in fetches

- src/bundle/Resources/public/js/scripts/button.translation.edit.js
- src/bundle/Resources/public/scss/_translation-selector.scss
- src/bundle/Resources/views/themes/admin/ui/edit_translation_button.html.twig
- src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
> IBX-8968: Fixed translation selector in search and dashboard

- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
> IBX-9037: Added extensibility point for richtext in PB block

- src/bundle/Resources/public/scss/_extra-actions.scss
> IBX-7528: Fixed shadow button in extra actions

- src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
> IBX-8663: Fixed dropdown remove listener

- src/bundle/Resources/public/scss/_buttons.scss
| :ticket: Issue | [IBX-9050](https://issues.ibexa.co/browse/IBX-9050) |
This changes only icon color on active state. It doesn't touch styles for disabled button, as its styles are in line with our current disabled buttons.
There was an agreement, that even though addons designs uses new design system, we keep it consistent with current one (as the new one is not implemented yet).
> IBX-9050: [AI] Use AI button - display issues

- src/bundle/Resources/config/services/forms.yaml
- src/lib/Form/Data/AbstractLanguageSwitchData.php
- src/lib/Form/Type/LanguageSwitchType.php
- https://github.com/ibexa/product-catalog/pull/1195
- https://github.com/ibexa/connector-ai/pull/81
- https://github.com/ibexa/shipping/pull/88
> Extracted language switch from ProductCatalog

- src/lib/EventListener/ViewTemplatesListener.php
| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/435
> IBX-8534: Replaced pagelayout parameter

- src/bundle/Resources/public/js/scripts/fieldType/validator/richtext-validator.js
| :ticket: Issue | [IBX-9097](https://issues.ibexa.co/browse/IBX-9097) |
> IBX-9097: [PB] Error with Richtext validator in nested_attribute

- src/lib/Form/Type/ReferenceCollectionType.php
- https://github.com/ibexa/product-catalog/pull/1197
Extracted ReferenceCollectionType from the ProductCatalog package to use it in bulk delete functionality in packages independent from ProductCatalog (connector AI)
> Extracted ReferenceCollectionType from the ProductCatalog

- src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
| :ticket: Issue | [IBX-9047](https://issues.ibexa.co/browse/IBX-9047) |
> IBX-9047: [AI] Size issues for Use AI menu while names have different length

- src/bundle/Resources/public/scss/_split-button.scss
- src/bundle/Resources/views/themes/admin/ui/menu/context_menu.html.twig
> IBX-7600: Fixed color of split button in edit mode

- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| :ticket: Issue | IBX-9132 |
- https://github.com/ibexa/image-picker/pull/90
- https://github.com/ibexa/assets-library-widget/pull/47 BUILD
> IBX-9132: [ALW] Search tag issue

- src/bundle/ui-dev/src/modules/common/pagination/pagination.js
> IBX-9167: Fixed subitems pagination on current page

- composer.json
- phpstan-baseline.neon
- src/bundle/Controller/LocationController.php
- src/lib/UI/Dataset/RelationsDataset.php
- src/lib/UI/Dataset/VersionsDataset.php
> IBX-8534: Dropped removed ContentService::loadRelations methods usage

- src/bundle/Resources/public/scss/_middle-ellipsis.scss
> IBX-9143: Fixed middle ellipsis overlapping text

- src/bundle/Resources/encore/ibexa.js.config.js
- src/bundle/Resources/public/js/scripts/core/storage.js
> IBX-8445: Added storage class

- src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
| :ticket: Issue | IBX-9261 |
Added use of translate function for field groups names in content type preview
> IBX-9261 added translate function with correct translation domain

- src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| :ticket: Issue | IBX-9314 |
We care only about the aggregation result, there is no need to fetch any data.
Idea by @adamwojs
> IBX-9314: UDW's suggestions query performance optimization

- phpstan-baseline.neon
> [PHPStan] Fixed reported errors

- src/bundle/Resources/public/js/scripts/admin.picker.js
| :ticket: Issue | IBX-3534 |
- https://github.com/ibexa/product-catalog-date-time-attribute/pull/8
> IBX-3534: Date picker seconds configuration

- src/bundle/Resources/public/scss/_tabs.scss
> IBX-9428: Changed margin-bottom to 0

- src/bundle/Resources/public/scss/_user-mode-badge.scss
> IBX-9347: Set with to max-content and added margin-right

- src/bundle/Resources/views/themes/admin/language/create.html.twig
- src/bundle/Resources/views/themes/admin/language/edit.html.twig
> IBX-7670: Added padding between fields

- features/standard/Roles.feature
This PR aims to fix CI issue such as this https://github.com/ibexa/experience/actions/runs/13273161538/job/37057645650#step:18:73
This issue is caused by pagination (by default there should be only 10 items displayed), step cannot see the item on list so it fails.
> [Behat] Fix for Roles.feature

- features/standard/Sections.feature
This PR aims to fix issues like https://github.com/ibexa/commerce/actions/runs/13251119322/job/37038468940#step:18:166
This is another case of pagination, 'Media' has to many items assigned (test item before fix was 11th one), i have switched reassinging of test item to ~'Form' section~  ~Standard section (Form section is not created on lower editions 🙈 ).~ I had to scrap Standard section too, on higher edition it gets packed with too much content, i settled for the nice test section.
> [Behat] Fix for Sections.feature

- src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
- src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig
> IBX-8306: Fixed placement of bookmark and trash icon in menu navbar

- src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
> IBX-8809: Fixed long name in ezimage fieldtype

- src/bundle/Resources/public/js/scripts/helpers/modal.helper.js
- src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
- src/bundle/Resources/views/themes/admin/ui/dashboard/tab/my_draft_list.html.twig
| :ticket: Issue | IBX-9406 |
- https://github.com/ibexa/share/pull/29
> IBX-9406: Add share action to Dashboard blocks & Drafts list

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
> IBX-9412: Fixed allowed extensions in ezimage field

- phpstan-baseline.neon
- src/lib/Menu/TrashRightSidebarBuilder.php
- https://github.com/ibexa/rector/pull/23
- https://github.com/ibexa/core/pull/489
Refactored SearchResult::$count to SearchResult::$totalCount deprecation
> Refactored SearchResult::$count to SearchResult::$totalCount deprecation

- composer.json
> Bump `symfony/deprecation-contracts` package

- src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
- src/bundle/Resources/public/scss/_tabs.scss
| :ticket: Issue | [IBX-8928](https://issues.ibexa.co/browse/IBX-8928) |
> IBX-8928: Tab with [...] is visible while loading the product details.

- src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
> IBX-9459: [Left menu] it is possible for the tabs in left menu to merge

- src/bundle/Resources/public/scss/fieldType/preview/_ezgmaplocation.scss
> IBX-9633: Fixed z-index for content map preview

- src/bundle/Resources/public/scss/ui/modules/common/_popup.scss
- src/bundle/ui-dev/src/modules/common/popup/popup.component.js
| :ticket: Issue | IBX-9453 |
- https://github.com/ibexa/product-catalog/pull/1226
> IBX-9453: Product Picker category filter

- src/bundle/Resources/public/scss/_dropdown.scss
| :ticket: Issue | IBX-9566 |
- https://github.com/ibexa/product-catalog/pull/1240
> IBX-9566: Product Picker - product type filter

- src/bundle/Resources/public/scss/ui/modules/_universal.discovery.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.no.results.scss
- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
- src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
- src/bundle/ui-dev/src/modules/common/table/empty.table.body.row.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
- src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.no.results.js
| :ticket: Issue | IBX-9599 |
- https://github.com/ibexa/product-catalog/pull/1243
> IBX-9599: empty table row and no search results component

- src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
> IBX-9629: Improve the map location (ezgmaplocation) fields layout.

- src/bundle/Resources/public/js/scripts/filters.action.btns.js
| :ticket: Issue | [IBX-9361](https://issues.ibexa.co/browse/IBX-9361) |
- https://github.com/ibexa/corporate-account/pull/272
> IBX-9361: The 'x' button in search for Clients list doesn't work

- src/bundle/ui-dev/src/modules/common/popup/popup.component.js
| :ticket: Issue | IBX-9462 |
- https://github.com/ibexa/page-builder/pull/419
> IBX-9462: React Popup fix

- src/bundle/ui-dev/src/modules/common/table/table.js
| :ticket: Issue | IBX-9649 |
- https://github.com/ibexa/product-catalog/pull/1265
> IBX-9649: Sticky columns in React table

- src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig
> IBX-9632: Added inLanguage parameter to URL for download file

- src/bundle/Resources/public/scss/_dropdown.scss
- src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
> IBX-9659: Fix dropdown elements sticking out and search icon is not in the input

- src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
> IBX-9658: Fixed removing tooltips

- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
> IBX-8760: Fixed styles for nontranslatable field notice

- phpstan-baseline.neon
- src/bundle/Controller/ContentViewController.php
…
| :ticket: Issue | IBX-9614 |
| :ticket: Issue | IBX-9585 |
| :ticket: Issue | IBX-9586 |
> IBX-9614, IBX-9585, IBX-9586: Fixed pagination after upgrading to symfony 6

- src/bundle/Resources/public/scss/_tables.scss
- src/bundle/Resources/views/themes/admin/ui/component/table/table_head_cell.html.twig
- src/bundle/ui-dev/src/modules/common/table/table.head.cell.js
- tests/integration/bootstrap.php
| :ticket: Issue | IBX-9652 |
- https://github.com/ibexa/product-catalog/pull/1268
> IBX-9652: TableHeadCell checkbox fixes

- src/bundle/Resources/public/js/scripts/helpers/request.helper.js
| :ticket: Issue | [IBX-8941](https://issues.ibexa.co/browse/IBX-8941) |
- https://github.com/ibexa/connector-openai/pull/41
- https://github.com/ibexa/connector-ai/pull/113
> IBX-8941: Added error descrition handling

- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-9717 |
- https://github.com/ibexa/discounts/pull/170
> IBX-9717: Fix permanent discount end date saving problem

- src/bundle/ui-dev/src/modules/common/table/empty.table.body.row.js
| :ticket: Issue | IBX-9741 |
- https://github.com/ibexa/product-catalog/pull/1295
> IBX-9741: Add products list link on no products view in PP

- src/bundle/Resources/public/scss/_inputs.scss
- src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-9775 |
- https://github.com/ibexa/discounts/pull/189
> IBX-9775: Fix invalid date time input styling

- src/lib/Behat/Page/ContentUpdateItemPage.php
| :ticket: Issue | N/A |
This change has been moved from https://github.com/ibexa/admin-ui/pull/1480/commits/2fe9c1574e8bb239f647080de0632d463934aaaf
> [Behat] Fixed selector for pageTitle in ContentUpdateItemPage

- src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
- src/bundle/Resources/translations/ibexa_multi_file_upload.en.xliff
- src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
> IBX-8769: Fixed multi file upload errors alignment

- src/bundle/Controller/Location/LoadSubItemsController.php
- src/bundle/Resources/config/routing_rest.yaml
- src/bundle/Resources/config/services/controllers.yaml
- src/bundle/Resources/config/services/rest.yaml
- src/bundle/Resources/translations/ibexa_sub_items.en.xliff
- src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
- src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
- src/bundle/ui-dev/src/modules/sub-items/services/bulk.service.js
- src/bundle/ui-dev/src/modules/sub-items/services/endpoints.js
- src/bundle/ui-dev/src/modules/sub-items/services/sub.items.service.js
- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
- src/lib/REST/Output/ValueObjectVisitor/SubItems/ContentInfo.php
- src/lib/REST/Output/ValueObjectVisitor/SubItems/ContentType.php
- src/lib/REST/Output/ValueObjectVisitor/SubItems/Owner.php
- src/lib/REST/Output/ValueObjectVisitor/SubItems/SubItem.php
- src/lib/REST/Output/ValueObjectVisitor/SubItems/SubItemList.php
- src/lib/REST/Output/ValueObjectVisitor/SubItems/Thumbnail.php
- src/lib/REST/Value/SubItems/ContentInfo.php
- src/lib/REST/Value/SubItems/ContentType.php
- src/lib/REST/Value/SubItems/Owner.php
- src/lib/REST/Value/SubItems/SubItem.php
- src/lib/REST/Value/SubItems/SubItemList.php
- src/lib/REST/Value/SubItems/Thumbnail.php
| :ticket: Issue | IBX-9722 |
Based on graphql query, this is what atm is returned from new endpoint
```json
{
"SubItems": {
"_media-type": "application\/vnd.ibexa.api.SubItems+json",
"totalCount": 176,
"SubItemList": [
{
"_media-type": "application\/vnd.ibexa.api.SubItem+json",
"id": 42,
"remoteId": "581da01017b80b1afb1e5e2a3081c724",
"hidden": false,
"priority": 0,
"pathString": "\/1\/2\/42\/",
"invisible": false,
"contentThumbnail": {
"_media-type": "application\/vnd.ibexa.api.contentThumbnail+json",
"Thumbnail": {
"_media-type": "application\/vnd.ibexa.api.Thumbnail+json",
"uri": "\/placeholder",
"mimeType": "image\/svg+xml"
}
},
"owner": {
"_media-type": "application\/vnd.ibexa.api.owner+json",
"Owner": {
"_media-type": …
```
> IBX-9722: Replaced graphql subitems fetching with dedicated REST endpoint

- .github/workflows/ci.yaml
- .github/workflows/frontend-ci.yaml
> [CI] Bumped ubuntu version to 24.04

- tests/lib/Menu/Action/BaseActionMenuBuilderTest.php
- tests/lib/Menu/Action/DraftListActionMenuBuilderTest.php
- tests/lib/Menu/Action/VersionListActionMenuBuilderTest.php
Fixes: https://github.com/ibexa/admin-ui/actions/runs/14491495494/job/40648783337
> [Tests] IBX-9619: Fixed ActionMenuBuilder tests

- features/standard/ContentDraft.feature
- phpstan-baseline.neon
- src/bundle/Resources/public/js/scripts/core/suggestion.taggify.js
- src/bundle/Resources/public/js/scripts/core/taggify.js
- src/bundle/Resources/views/themes/admin/ui/component/user/user.html.twig
- src/lib/Behat/Component/Table/Table.php
- src/lib/Behat/Page/DashboardPage.php
| :ticket: Issue | IBX-9750 |
- https://github.com/ibexa/share/pull/42
> IBX-9750: Share dialog adjustments

- phpstan-baseline.neon
- src/bundle/Resources/public/js/scripts/core/suggestion.taggify.js
> IBX-9761: [RTC] Search results are displayed after typing 4 characters

- phpstan-baseline.neon
> [CI] Removed no longer existing phpstan errors

- src/bundle/Resources/public/scss/_forms.scss
| :ticket: Issue | IBX-9836 |
- https://github.com/ibexa/product-catalog/pull/1305
> IBX-9836: Fix form help icon shrinking

- phpstan-baseline.neon
- src/lib/REST/Input/Parser/BulkOperation.php
- src/lib/REST/Input/Parser/Operation.php
https://github.com/ibexa/rest/pull/164
> IBX-9727: Aligned Parsers with rest changes

- src/bundle/ui-dev/src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
- src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
- src/bundle/ui-dev/src/modules/sub-items/constants.js
- src/bundle/ui-dev/src/modules/sub-items/services/view.registry.js
- src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| :ticket: Issue | IBX-9935 |
This PR introduces an easy way to add new view to subitems.
All what has to be done is set the component to registry:
```js
import TimelineViewComponent from 'path to: timeline.view.component';
import { registerView } from '@ibexa-admin-ui-modules/sub-items/services/view.registry';
registerView('timeline', {
component: TimelineViewComponent,
iconName: 'timeline',
label: 'Timeline view',
});
```
timeline.view.component
```js
import React from 'react';
import PropTypes from 'prop-types';
import TimelineViewItemComponent from './timeline.view.item.component';
const TimelineViewComponent = ({ items, generateLink }) => {
const groupByDate = (items) => {
return items.reduce((groups, item) => {
const date = new …
```
> IBX-9935: Added extensibility point for new views in subitems

- src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
- src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
- src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-9926 |
- https://github.com/ibexa/share/pull/58
- https://github.com/ibexa/fieldtype-richtext/pull/227
- https://github.com/ibexa/fieldtype-richtext-rte/pull/13
> IBX-9926: [Collaboration] Users list for CKEditor

- src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
> IBX-9847: Fixed ezobjectrelation selection limit

- src/lib/Behat/Component/CreateNewPopup.php
- src/lib/Behat/Component/Dialog.php
| :ticket: Issue | IBX-9859 |
- https://github.com/ibexa/discounts/pull/219
This Pr adjusts CreateNewPopup component to work with radio buttons.
> [Behat] IBX-9859: Adjustments for discounts behat tests

- src/lib/Behat/Component/Fields/RichText.php
| :ticket: Issue | IBX-9915 |
- https://github.com/ibexa/connector-openai/pull/50
> [Behat] IBX-9915: AI richtext coverage

- src/bundle/Resources/views/themes/admin/ui/component/user/user.html.twig
| :ticket: Issue | IBX-9918 |
- https://github.com/ibexa/share/pull/59
> IBX-9918: Added parameter is_link in twig user component

- src/bundle/Resources/encore/ibexa.webpack.custom.config.js
- src/bundle/Resources/public/js/scripts/admin.content.tree.js
- src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
- src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
- src/bundle/Resources/public/js/scripts/admin.location.view.js
- src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
- src/bundle/Resources/public/js/scripts/admin.search.filters.js
- src/bundle/Resources/public/js/scripts/admin.section.list.js
- src/bundle/Resources/public/js/scripts/admin.section.view.js
- src/bundle/Resources/public/js/scripts/admin.trash.list.js
- src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
- src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
- src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
- src/bundle/Resources/public/js/scripts/helpers/react.helper.js
- src/bundle/Resources/public/js/scripts/react.dom.load.js
- src/bundle/Resources/public/js/scripts/react.load.js
- src/bundle/Resources/public/js/scripts/udw/browse.js
- src/bundle/Resources/public/js/scripts/udw/copy.js
- src/bundle/Resources/public/js/scripts/udw/copy_subtree.js
- src/bundle/Resources/public/js/scripts/udw/locations.tab.js
- src/bundle/Resources/public/js/scripts/udw/move.js
- src/bundle/Resources/public/js/scripts/udw/select.location.js
- src/bundle/Resources/public/js/scripts/udw/swap.js
- src/bundle/Resources/views/themes/admin/ui/layout.html.twig
> IBX-9916: Upgrade frontend dependencies

- src/bundle/Resources/public/scss/_dropdown.scss
> IBX-8304: Fixed dropdown multi selection display

- src/bundle/Resources/public/scss/_custom-url-form.scss
- src/bundle/Resources/views/themes/admin/url_wildcard/modal_create.html.twig
- src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
> IBX-8688: Fixed switcher helper text

- src/bundle/Resources/public/js/scripts/core/suggestion.taggify.js
- src/bundle/Resources/public/scss/_taggify.scss
| :ticket: Issue | IBX-9973 |
- https://github.com/ibexa/share/pull/63
> IBX-9973: Only 10 editors are displayed on users list

- src/bundle/Resources/public/scss/_tag-view-select.scss
- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
| :ticket: Issue | IBX-9759 |
- https://github.com/ibexa/taxonomy/pull/346
> IBX-9759: Fixed disabled fields styles

- src/bundle/Resources/public/scss/_context-menu.scss
| :ticket: Issue | IBX-10102 |
> IBX-10102: [...] button is shorter than other buttons in content menu

- src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
> IBX-7940: Fixed clearing email input field

- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
| :ticket: Issue | IBX-9759 |
- https://github.com/ibexa/taxonomy/pull/348
> IBX-9759: Fixed id_disabled value and styles condition

- phpstan-baseline.neon
- src/lib/EventListener/ContentTypeSuggestionsListener.php
- src/lib/UI/Module/ContentTree/NodeFactory.php
| :ticket: Issue | N/A       |
Ref. https://github.com/ibexa/admin-ui/actions/runs/15445741564/job/43474757011?pr=1559
N/A
N/A
> [PHPStan] Resolved phpstan issues

- src/bundle/Resources/config/default_parameters.yaml
> IBX-7845: Fixed form icon ID

- src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
| :ticket: Issue | [IBX-10130](https://issues.ibexa.co/browse/IBX-10130) |
> IBX-10130: [Twig] Added admin-ui-versions-table-before component group

- src/bundle/Resources/public/scss/fieldType/edit/_ibexa_user.scss
- src/bundle/Resources/public/scss/fieldType/preview/_ibexa_user-preview.scss
| :ticket: Issue | IBX-9947  |
ezuser has been incorrectly replaced with ibexa_time in  https://github.com/ibexa/admin-ui/pull/1560
N/A
N/A
> [SCSS] Fixed CSS selectors for ibexa_user field type

- features/standard/fields/contentQuery.feature
- src/lib/Behat/Component/ContentItemAdminPreview.php
- src/lib/Behat/Component/Fields/ImageAsset.php
- src/lib/Behat/Component/Fields/User.php
- src/lib/Behat/Page/ContentUpdateItemPage.php
Follow up for https://github.com/ibexa/admin-ui/pull/1560 
Ref. https://github.com/ibexa/admin-ui/actions/runs/15509518259/job/43668611783#step:18:251
N/A
N/A
> [Behat] Fixed User::getFieldTypeIdentifier implementation

- src/bundle/ui-dev/src/modules/common/services/content.service.js
- src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| :ticket: Issue | IBX-9895 |
As per discussion in https://github.com/ibexa/rest/pull/181
> IBX-9895: Encoded location search query identifier

- src/bundle/Resources/public/js/scripts/user.invitation.modal.js
| :ticket: Issue | IBX-9894 |
It's pretty much copy-paste from other forms.
> IBX-9894: Prevented invitation form submission with the enter key

- src/lib/Behat/Component/Fields/Keywords.php
| :ticket: Issue | IBX-10162 |
- https://github.com/ibexa/admin-ui-assets/pull/34
Adjusted Taggify use in Keywords field Behat component after removal of dependency.
> [Behat] IBX-10162: Adjusted Taggify use in Keywords field

- src/bundle/Resources/views/themes/admin/content/edit/javascripts.html.twig
| :ticket: Issue | IBX-10300 |
- https://github.com/ibexa/product-catalog/pull/1360
> IBX-10300: Remove old taggify script from twig files

- src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
> IBX-6657: Fixed margin in ezauthor field

- src/bundle/Resources/public/scss/_dropdown.scss
| :ticket: Issue | IBX-10207 |
> IBX-10207: Fixed dropdown empty state image

- src/bundle/DependencyInjection/Compiler/ComponentPass.php
- src/contracts/Component/Renderable.php
- src/contracts/Component/Renderer/RendererInterface.php
- src/lib/Component/Event/RenderGroupEvent.php
- src/lib/Component/Event/RenderSingleEvent.php
- src/lib/Component/LinkComponent.php
- src/lib/Component/Registry.php
- src/lib/Component/Renderer/DefaultRenderer.php
- src/lib/Component/ScriptComponent.php
- src/lib/Component/TwigComponent.php
> Update deprecation removal version from 5.0 to 6.0 in admin-ui components

- src/bundle/Resources/public/scss/_content-type-edit.scss
> IBX-8754: Fixed label spacing for content type fields options

- src/bundle/Resources/public/scss/fieldType/edit/_ezmedia.scss
- src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base_fields.html.twig
> IBX-9978: Fixed media field checkboxes alignment

- src/bundle/Resources/public/scss/_filters.scss
> IBX-8167: creators list covered by chevron

- src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
| :ticket: Issue | IBX-10117 |
> IBX-10117: Errors thrown in the console when uploading more files

- src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
| :ticket: Issue | [IBX-9730](https://issues.ibexa.co/browse/IBX-9730) |
Changes for https://github.com/ibexa/taxonomy/pull/325 allowing to pass custom html form
[IBX-9730]: https://ibexa.atlassian.net/browse/IBX-9730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IBX-9730: Taxonomy subtree limitation

- src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
> IBX-8698: Fixed user profile group navigation

- src/bundle/Resources/public/js/scripts/core/popup.menu.js
| :ticket: Issue | IBX-10138 |
> IBX-10138: Not animated arrow in the drop-down in the share dialog

- src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
| :ticket: Issue | IBX-10454 |
> IBX-10454:[UDW] Error when open bookmarks

- .github/workflows/ci.yaml
- phpstan-baseline.neon
- src/lib/Form/DataTransformer/LanguageTransformer.php
- tests/lib/Form/DataTransformer/ContentInfoTransformerTest.php
- tests/lib/Form/DataTransformer/LanguageTransformerTest.php
| :ticket: Issue | IBX-10507 |
- https://github.com/ibexa/admin-ui/pull/1681
> IBX-10507: Add PHP 8.4 to CI testing matrix

- src/bundle/Resources/translations/ibexa_content_create.en.xliff
- src/bundle/Resources/translations/ibexa_content_edit.en.xliff
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
- src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| :ticket: Issue | IBX-10412 |
> IBX-10412: COTF - fixed confirm label

- src/bundle/Controller/NotificationController.php
- src/bundle/Resources/public/scss/_list-filters.scss
- src/bundle/Resources/public/scss/_notifications.scss
- src/bundle/Resources/public/scss/_side-panel.scss
- src/bundle/Resources/public/scss/ibexa.scss
- src/lib/Form/Factory/FormFactory.php
| :ticket: Issue | N/A |
|----------------|-----|
Added missing @use '@ibexa-admin-ui/src/bundle/Resources/public/scss/custom.scss' as *; to new SCSS files
> Imported custom SCSS in _notifications.scss for improved styling consistency

- src/bundle/Resources/public/js/scripts/helpers/modal.helper.js
| :ticket: Issue | IBX-10567 |
> IBX-10567: [Share dialog] Modal backdrop fade is not removed

- src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
| :ticket: Issue | IBX-10635 |
> IBX-10635: Fixed 'allowInput' flag in flatpickr

- src/bundle/Resources/public/scss/_custom-url-form.scss
- src/bundle/Resources/views/themes/admin/content/tab/url/modal_add_custom_url.html.twig
| :ticket: Issue | [IBX-10473] |
Visual representation
> IBX-10473: Refactor custom URL form styles and templates to match the design and improve maintainability and consistency.

- src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content-type-selector-list.scss
| :ticket: Issue | IBX-10406 |
> IBX-10406: Include custom.scss in _content.type.selector.list.scss to apply shared styles

- src/lib/Behat/Page/DashboardPage.php
- https://github.com/ibexa/commerce/pull/1507
This PR aims to fix CI errors such as https://github.com/ibexa/commerce/actions/runs/17702447063/job/50310164298
> [Behat] Fix for no draft on draft list

- src/bundle/Resources/public/js/scripts/filters.action.btns.js
| :ticket: Issue | IBX-10427 |
> IBX-10427: Fixed date and datetime filters clearing

- features/standard/ContentManagement.feature
- src/lib/Behat/BrowserContext/ContentViewContext.php
- src/lib/Behat/Page/ContentViewPage.php
| :ticket: Issue | IBX-10333 |
Behat test covering hide/reveal content in main menu (context management).
> [Behat] IBX-10333 Added scenarios for hide and reveal content

- src/bundle/Resources/public/js/scripts/edit.header.js
| :ticket: Issue | IBX-10659 |
Added verification if headerBottomRowNode is not null
> IBX-10659: Added verification if headerBottomRowNode is not null

- src/bundle/Resources/public/js/scripts/admin.location.add.translation.js
| :ticket: Issue | IBX-10489 |
> IBX-10489: Fixed disabled state in content tree translation modal
