ibexa/admin-ui

src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| **JIRA issue**                          | [IBX-538](https://issues.ibexa.co/browse/IBX-538)
| **Requires**                            | ibexa/core#13
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes
ibexa/core#13 updates `ibexa/core` Bundle names with proper Ibexa prefix instead of EzPublish. This PR aligns Twig namespace references with the bundle name change.
=> IBX-538: Replaced EzPublishCore Twig namespace references with IbexaCore

behat_suites.yml, features/standard/SystemInfo.feature
This PR adjusts config file paths and tests to the rebranding process.
I've removed some of the bundles from the list, because TBH I don't see the advantage in checking all of them.
=> [Behat] Adjusted suite paths to rebranding

src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1505
=> IBX-1505: Added autosave to COTF in UDW

src/bundle/Resources/public/scss/_main-menu.scss, src/bundle/Resources/public/scss/_popup-menu.scss, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig, src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig, src/contracts/Menu/AbstractBuilder.php, src/lib/Menu/MainMenuBuilder.php, src/lib/Menu/MenuItemFactory.php, tests/lib/Menu/MainMenuBuilerTest.php
| Tickets       | [IBX-1015](https://issues.ibexa.co/browse/IBX-1015)
As a developer I want to group submenu items and change order of items in groups
follow up for https://github.com/ezsystems/ezplatform-admin-ui/pull/2003
=> IBX-1015: Added support for subitems grouping in admin-ui menu

src/bundle/Resources/views/themes/admin/trash/list.html.twig
| Tickets       | [EZEE-3213](https://issues.ibexa.co/browse/EZEE-3213)
Merge up from: https://github.com/ezsystems/ezplatform-admin-ui/pull/2016
=> EZEE-3213: Added verification if the user has section/view permission

.github/workflows/browser-tests.yaml, .github/workflows/ci.yaml
Things done:
1) Looks like the cyclic dependency between ibexa/admin-ui and ibexa/user is removed - I've removed the `COMPOSER_ROOT_VERSION` from Unit tests and Browser tests as it's no longer needed.
2) Added testing on `main`, not master
CI failures are not related to this PR.
=> [CI] Updated configuration for main branch

src/contracts/Menu/AbstractBuilder.php
This PR fixes invalid return type declaration that causes error: 
`Parameter #1 $child of method Knp\Menu\ItemInterface::addChild() expects Knp\Menu\ItemInterface|string, Knp\Menu\ItemInterface|null given.
`
=> Fixed return type declaration for AbstractBuilder::createMenuItem

src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_base.html.twig
| Tickets       | -
* `anchor_params` variable is used only in  `left_sidebar` block, so it's scope should be narrowed to block.
* `left_sidebar` block could be overwriten in child template so then there is no need to compute `anchor_params` at all
=> Moved anchor_params variable to block scope

src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1684
=> IBX-1684: Added adapt context menu when content tree is resized

features/standard/SystemInfo.feature, src/lib/Behat/Page/SystemInfoPage.php
Failing build: https://github.com/ibexa/admin-ui/actions/runs/1582117472
```
Then I see "Composer" system information table    # Ibexa\AdminUi\Behat\BrowserContext\SystemInfoContext::iSeeSystemInformationTable()
Failed asserting that expected string 'Composer' is equal to actual 'Packages' for css locator 'tableTitle': '.tab-pane.active .ez-fieldgroup__name'
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Composer'
+'Packages'
```
```
Then I see "Symfony Kernel" system information table    # Ibexa\AdminUi\Behat\BrowserContext\SystemInfoContext::iSeeSystemInformationTable()
Failed asserting that expected string 'Symfony Kernel' is equal to actual 'Bundles' for css locator 'tableTitle': '.tab-pane.active .ez-fieldgroup__name'
Failed asserting that two strings …
```
=> [Behat] Fixed System info tests

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1742
=> IBX-1742: Dropdown not working in Shipping Management - dynamic dropdowns

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/scss/_content-type-edit.scss, src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1608
- https://github.com/ibexa/personalization/pull/29
- https://github.com/ibexa/product-catalog/pull/231
- [x ] Ready for Code Review
=> IBX-1608: Added possibility to add field by click

src/bundle/Resources/public/js/scripts/admin.limitation.pick.js, src/bundle/Resources/views/themes/admin/limitation/udw_limitation_value_list_item.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1795
Fixes problem with double escaped attribute value (attribute in a template in an attribute)
=> IBX-1795: Location limitation not working

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/js/scripts/admin.input.text.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1789
=> IBX-1789: Fix Shipping Management page - manage attaching events to dynamically add inputs

src/bundle/Resources/config/ezplatform_default_settings.yaml, src/bundle/Resources/config/services/user_settings.yaml, src/bundle/Resources/public/js/scripts/admin.settings.datetimeformat.update.js, src/bundle/Resources/views/themes/admin/account/settings/list.html.twig, src/bundle/Resources/views/themes/admin/account/settings/update.html.twig, src/bundle/Resources/views/themes/admin/account/settings/update_datetime_format.html.twig, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       |  [IBX-1109](https://jira.ez.no/browse/IBX-1109) 
- https://github.com/ibexa/user/pull/16
=> IBX-1109: Aligned views with groupable user settings

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.create.widget.scss, src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1666
=> IBX-1666: Moved create actions to the bottom in UDW

src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/helpers/location.helper.js, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/public/scss/_tag.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1588
=> IBX-1588: add location helper; fix ibexa-input--checkbox input, ibexa-tag

src/contracts/Event/ContentProxyCreateEvent.php, src/lib/Event/Options.php, src/lib/EventListener/ContentProxyCreateDraftListener.php, tests/lib/EventListener/ContentProxyCreateDraftListenerTest.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1772
Worth addition (kinda required for Taxonomy) to creating content. While subscribing to `ContentProxyCreateEvent` you could only use generated Response which was not really helpful if you needed to work on created content. So, after making `ContentProxyCreateEvent::$options` mutable I could pass `content_draft` option for further manipulation in event listeners.
=> IBX-1772: Passed created content draft to ContentProxyCreateEvent context

src/bundle/Resources/views/themes/admin/ui/form_fields/toggle_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1765
| Bug fix?      |  no
=> IBX-1765: Added customize label on/off for toggle widget

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezcountry.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezemail.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezfloat.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezstring.scss, src/bundle/Resources/public/scss/ibexa.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss, src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/ui-dev/src/modules/common/popup/popup.component.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1526
=> IBX-1526: change edit fields width to full column; Page Builder updates

src/bundle/Resources/translations/dashboard.en.xliff, src/bundle/Resources/translations/language.en.xliff, src/bundle/Resources/translations/section.en.xliff, src/bundle/Resources/views/themes/admin/language/list.html.twig, src/bundle/Resources/views/themes/admin/section/list.html.twig, src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
| Tickets       | [](https://issues.ibexa.co/browse/IBX-1859)
=> IBX-1859: Update primary buttons labels in various places

src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss, src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js
| Tickets       | [IBX-1889](https://issues.ibexa.co/browse/IBX-1889)
=> IBX-1889: Visually the sub items are at the same level as the parent in the content tree

src/bundle/DependencyInjection/Compiler/ComponentPass.php, src/bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPass.php, src/bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php, src/bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php, src/bundle/DependencyInjection/Compiler/TabPass.php, src/bundle/DependencyInjection/Compiler/UiConfigProviderPass.php, src/bundle/Resources/config/services/components/content/edit.yaml, src/bundle/Resources/config/services/dashboard.yaml, src/bundle/Resources/config/services/fieldtype_form_mappers.yaml, src/bundle/Resources/config/services/form_ui_action_mappers.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/modules/content_tree.yaml, src/bundle/Resources/config/services/modules/subitems.yaml, src/bundle/Resources/config/services/rest.yaml, src/bundle/Resources/config/services/role_form_mappers.yaml, src/bundle/Resources/config/services/search.yaml, src/bundle/Resources/config/services/siteaccess.yaml, src/bundle/Resources/config/services/strategies.yaml, src/bundle/Resources/config/services/tabs/content_type.yaml, src/bundle/Resources/config/services/tabs/locationview.yaml, src/bundle/Resources/config/services/tabs/url_management.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/bundle/Resources/config/services/user_settings.yaml, src/bundle/Resources/config/services/views.yaml, src/contracts/Tab/TabInterface.php, tests/bundle/DependencyInjection/Compiler/FieldTypeFormMapperDispatcherPassTest.php
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
Additionally, the support for the service tag `ez.fieldFormMapper.definition` deprecated prior Ibexa v3.3 has been dropped.
=> IBX-1694: Rebranded dependency injection container service tags

src/bundle/DependencyInjection/Compiler/LimitationFormMapperPass.php, src/bundle/DependencyInjection/Compiler/LimitationValueMapperPass.php, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/action_dispatchers.yaml, src/bundle/Resources/config/services/autosave.yaml, src/bundle/Resources/config/services/controllers.yaml, src/bundle/Resources/config/services/dashboard.yaml, src/bundle/Resources/config/services/fieldtype_form_mappers.yaml, src/bundle/Resources/config/services/form_processors.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/menu.yaml, src/bundle/Resources/config/services/modules/content_tree.yaml, src/bundle/Resources/config/services/modules/subitems.yaml, src/bundle/Resources/config/services/pagination.yaml, src/bundle/Resources/config/services/rest.yaml, src/bundle/Resources/config/services/role_form_mappers.yaml, src/bundle/Resources/config/services/siteaccess.yaml, src/bundle/Resources/config/services/tabs/content_type.yaml, src/bundle/Resources/config/services/tabs/locationview.yaml, src/bundle/Resources/config/services/twig.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/bundle/Resources/config/services/universal_discovery_widget.yaml, src/bundle/Resources/config/services/validators.yaml, src/bundle/Resources/config/services/views.yaml, src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig, tests/lib/Menu/MainMenuBuilerTest.php
=> IBX-1853: Rebranded services names

src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/ui/component/preview_unavailable.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1652
=> IBX-1652: Fixed alert width in content edit view

src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1164
This PR adds hidden attribute, as before, in 3.3 this select wasn't visible from this form and it wasn't translated neither.
(and as it's hidden, it doesn't matter if it's translated)
=> IBX-1164: [Roles] missing translation in roles dropdown

src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-1458
=> IBX-1458: Fix dropdown 'invalid input tooltip' displayed in lower than dropdown

src/bundle/Resources/config/services/role_form_mappers.yaml, src/bundle/Resources/config/services/views.yaml
Dropped .class parameters which have been deprecated since Symfony 3.x
=> IBX-1696: Removed class parameters from ibexa/admin-ui repository

src/bundle/Resources/public/scss/_extra-actions.scss, src/bundle/Resources/public/scss/_instant-filter.scss, src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig, src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1348
- https://github.com/ibexa/taxonomy/pull/62
=> IBX-1348: Create sidebar design fixes - main & UDW

.prettierrc, src/bundle/Resources/translations/universal_discovery_widget.en.xliff, src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-button/content.create.button.js, src/bundle/ui-dev/src/modules/universal-discovery/components/simple-dropdown/simple.dropdown.js, src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-1761
=> IBX-1761: Updated UDW design

src/bundle/Resources/public/scss/_content-type-edit.scss, src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss, src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig, src/bundle/Resources/views/themes/admin/content_type/edit.html.twig, src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig, src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig, src/bundle/Resources/views/themes/admin/content_type/part/nontranslatable_fields_disabled.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-1498
=> IBX-1498: Disabled drag and drop, fields in content type translate

src/lib/Behat/Component/UniversalDiscoveryWidget.php, src/lib/Behat/Page/AdminUpdateItemPage.php, src/lib/Behat/Page/RoleUpdatePage.php
Fix for:
```
And I select "Media" from Sections as role assignment limitation # Ibexa\AdminUi\Behat\BrowserContext\RolesContext::iSelectSectionLimitation()
Ibexa\Behat\Browser\Exception\ElementNotFoundException: Could not find element named: 'Sections'. Collection is empty. XPATH locator 'input': '//label/..'. in vendor/ezsystems/behatbundle/src/lib/Browser/Element/ElementCollection.php:61
```
errors
https://github.com/ibexa/admin-ui/runs/5017417803?check_suite_focus=true
Looks like the tests have problems accessing the data in the "Limitations" tab:
https://res.cloudinary.com/ezplatformtravis/image/upload/v1643699156/screenshots/61f8dbd46ba5c463228304-vendor_ibexa_admin-ui_features_standard_roles_feature_61_p8w1fx.png
I've added directly switching into the tab to make the life easier for …
=> [Behat] Added switching into specific tabs in Roles feature

src/lib/Form/Data/ContentTypeData.php, src/lib/Form/Data/FieldDefinitionData.php, src/lib/Form/Type/Search/DateIntervalType.php, tests/bundle/ParamConverter/LanguageParamConverterTest.php, tests/lib/Specification/ContentType/ContentTypeIsUserTest.php
=> IBX-1853: Used rebranded namespaces in comments

bootstrap.php, features/standard/ContentType.feature, features/standard/ContentTypeFields.feature, features/standard/Roles.feature, src/bundle/Controller/ContentViewController.php, src/bundle/DependencyInjection/IbexaAdminUiExtension.php, src/bundle/Resources/config/services/pagination.yaml, src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig, src/bundle/Resources/views/themes/admin/link_manager/view.html.twig, src/bundle/Resources/views/themes/admin/ui/pagination.html.twig, src/bundle/View/EzPagerfantaView.php, src/contracts/Form/Data/FormMapper/FormDataMapperInterface.php, src/lib/Form/Data/FormMapper/ContentCreateMapper.php, src/lib/Form/Data/FormMapper/ContentTranslationMapper.php, src/lib/Form/Data/FormMapper/ContentTypeDraftMapper.php, src/lib/Form/Data/FormMapper/ContentUpdateMapper.php, src/lib/Form/Data/FormMapper/UserUpdateMapper.php, src/lib/Pagination/Pagerfanta/NotificationAdapter.php, src/lib/Pagination/Pagerfanta/TrashItemAdapter.php, src/lib/QueryType/ContentSubtreeQueryType.php, src/lib/QueryType/LocationPathQueryType.php, src/lib/QueryType/MediaSubtreeQueryType.php, src/lib/QueryType/TrashSearchQueryType.php, src/lib/Strategy/NotificationTwigStrategy.php, tests/lib/QueryType/SearchQueryTypeTest.php, tests/lib/Translation/Extractor/LimitationTranslationExtractorTest.php, tests/lib/Validator/Constraint/UniqueURLValidatorTest.php
=> IBX-1853: Used rebranded Ibexa name in codebase

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.table.item.scss, src/bundle/ui-dev/src/modules/universal-discovery/components/actions-menu/actions.menu.js, src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2226
=> IBX-2230: [UDW] Hide footer buttons on "Create" from dashboard; Change border in search to blue; Allow creating content from search

src/bundle/Controller/FieldDefinitionController.php
| Tickets       | [IBX-2240](https://issues.ibexa.co/browse/IBX-2240)
Changed default field type name on content type create
=> IBX-2240: Default field type name on CT create

src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
| Tickets       | [IBX-1572](https://issues.ibexa.co/browse/IBX-1572)
=> IBX-1572: Changed default profile image in user menu

src/bundle/Command/CompileAssetsCommand.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2299
=> IBX-2299: Added `config-name` option to ibexa:encore:compile command

src/bundle/Resources/views/themes/admin/content/location_view.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2287
https://github.com/ibexa/taxonomy/pull/102
=> IBX-2287: Context menu in location view doesn't respect it's max available width

src/bundle/Resources/public/js/scripts/admin.context.menu.js, src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js, src/bundle/Resources/public/js/scripts/core/adaptive.items.js, src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2288
=> IBX-2288: Use ResizeObserver for adaptive items and subitems

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss, src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2278
=> IBX-2278: Added spinner to loading location meta data

src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php
| Tickets       | https://issues.ibexa.co/browse/IBX-1496
=> IBX-1496: When configuring a Content Type - the Category dropdown should  removed 

src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/admin.dropdown.js, src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/js/scripts/helpers/object.instances.js, src/bundle/Resources/public/scss/_modals.scss, src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2277
=> IBX-2277: [Taxonomy] As a user, I want to change language context in Taxonomy Tree

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2454
=> IBX-2454: Content Type/Product Type page should be scrolled down to invalid fields

src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2177
| Related PR | https://github.com/ibexa/page-builder/pull/97
=> IBX-2177: Page builder - Error state on icon

src/lib/UI/Config/ConfigWrapper.php
Disables PHP return type deprecation notices when running the site on PHP 8.1
=> Add #[\ReturnTypeWillChange] to disable PHP 8.1 deprecation warnings

src/lib/Behat/Component/Pagination.php
Tested in https://github.com/ibexa/experience/pull/26 with 3 successfull runs, the only issue that occured was:
```
│  	[2022-03-21T22:56:25.550491+00:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: mkdir(): File exists" at /var/www/vendor/friendsofsymfony/jsrouting-bundle/Extractor/ExposedRoutesExtractor.php line 179 {"exception":"[object] (ErrorException(code: 0): Warning: mkdir(): File exists at /var/www/vendor/friendsofsymfony/jsrouting-bundle/Extractor/ExposedRoutesExtractor.php:179)"} []
```
which is not related
=> [Behat] Increased go to the top timeout

src/bundle/Resources/public/scss/_main-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2565
=> IBX-2565: Main menu - text outside popup when too long

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2622
| Doc needed?   | no, I think
=> IBX-2622: As a developer I want to have dynamic Dropdown

src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js, src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js, src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2020
Note for QA:
please check the showing of the file size error for the following situation:
1. Click the button
2. Drop file
Because I noticed that it actually caused two different behaviors when it comes to marking the container invalid
=> IBX-2020: Fixed error message

src/lib/Behat/Component/ContentTypePicker.php
Looks like the tests slowed down after https://github.com/ibexa/admin-ui/pull/377 , this PR narrows one selector to make Behat's jobs easier. It's still not back to the level it was before, further investigation will be needed as well.
Current build (https://github.com/ibexa/experience/runs/6068980934?check_suite_focus=true):
```
1/40	✔	21 min 2 s 781 ms	/var/www/vendor/ibexa/admin-ui/features/standard/ContentTypeFields.feature
2/40	✔	30 min 13 s 774 ms	/var/www/vendor/ibexa/form-builder/features/FormBuilderTests.feature
3/40	✔	14 min 38 s 886 ms	/var/www/vendor/ibexa/page-builder/features/DynamicLandingPage/Blocks/Blocks.feature
4/40	✔	7 min 58 s 820 ms	/var/www/vendor/ibexa/form-builder/features/FormContentItemAdministration.feature
12/40	✔	13 min 23 s 330 ms …
```
=> [Behat] Narrowed down ContentTypePicker selector

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2627
=> IBX-2627: dropdown small styling issues

src/bundle/Resources/public/scss/_badges.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2557
Related PRs:
- https://github.com/ibexa/commerce-shop/pull/75
- https://github.com/ibexa/workflow/pull/43
- https://github.com/ibexa/scheduler/pull/56
=> IBX-2557: Fix badge

src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2628
=> IBX-2628: Introduce colorful tag-like dropdown

src/bundle/Resources/public/scss/_anchor-navigation.scss, src/bundle/Resources/public/scss/_content-edit.scss, src/bundle/Resources/public/scss/_content-type-edit.scss, src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/public/scss/_main-container.scss, src/bundle/Resources/public/scss/mixins/_containers.scss, src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig, src/bundle/Resources/views/themes/admin/account/settings/update.html.twig, src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig, src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/content_type/content_type_group/base.html.twig, src/bundle/Resources/views/themes/admin/content_type/create.html.twig, src/bundle/Resources/views/themes/admin/content_type/edit.html.twig, src/bundle/Resources/views/themes/admin/content_type/edit_base.html.twig, src/bundle/Resources/views/themes/admin/content_type/edit_section.html.twig, src/bundle/Resources/views/themes/admin/language/base.html.twig, src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig, src/bundle/Resources/views/themes/admin/object_state/base.html.twig, src/bundle/Resources/views/themes/admin/object_state/object_state_group/base.html.twig, src/bundle/Resources/views/themes/admin/section/base.html.twig, src/bundle/Resources/views/themes/admin/section/create.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_base.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig, src/bundle/Resources/views/themes/admin/user/policy/base.html.twig, src/bundle/Resources/views/themes/admin/user/role/base.html.twig, src/bundle/Resources/views/themes/admin/user/role_assignment/base.html.twig, src/lib/Behat/Page/RoleUpdatePage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2655
Fixed create/edit layout by removing boostrap class `row` and `col-`. All content should be aligned to the left sidebar
1. 1376px width
2. 1920px width
3. > 1920px width
=> IBX-2655: create/edit layout fixes

src/bundle/Resources/public/scss/fieldType/edit/_ezinteger.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2760
This solution doesn't work on Firefox - unfortunately there's no way to fix it on that browser, but it should work on other browsers (Chrome, Safari, Edge, Opera)
=> IBX-2760: Number input - clear X button overlaps with the number

src/bundle/Resources/public/scss/_field-group.scss, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2918
Change togglers in view tab from arrows to button with arrow and a label
=> IBX-2918: Improvement collapse panel

src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js, src/bundle/Resources/public/scss/_tabs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2920
=> IBX-2920: Fixed rolled-up styles

src/bundle/Controller/FieldDefinitionController.php
| Tickets       | [https://issues.ibexa.co/browse/IBX-2939](https://issues.ibexa.co/browse/IBX-2939)
=> IBX-2939: Field order in CT edit is incorrectly saved on refresh

src/lib/Behat/Page/ContentUpdateItemPage.php
It seems that ElementTextCriterion was removed during crossmerge :) (https://github.com/ibexa/admin-ui/pull/449/files#diff-120e25363c558247aa880bccdfbabde3541728910e8c25b3a84ec4bf8d161c98L16). It is the cause of CI failure -such as https://github.com/ibexa/commerce/runs/6679362821?check_suite_focus=true#step:12:49
=> [Behat] Restore deleted ElementTextCriterion

src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js, src/bundle/Resources/public/js/scripts/admin.content.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-2943
Additionaly it fixes problem with large gap between fields and taxonomy, as now it adds padding at the end of form.
In 4.2/main, selector `.ibexa-edit-content form` should be replaced with `.ibexa-edit-content__container`
=> IBX-2943: Section is not fully switched when editing content with multiple sections

composer.json, src/bundle/DependencyInjection/IbexaAdminUiExtension.php
| **JIRA issue**                          | [IBX-2961](https://issues.ibexa.co/browse/IBX-2961)
| **Requires**                             | ibexa/core#120
| **Type**                                   | improvement
| **Target Ibexa version** | `v4.1`+
| **BC breaks**                          | no
This PR aligns AdminUi with the changes done in ibexa/core#120 for ibexa/fieldtype-richtext#46
It is worth to update "[Importing assets from a bundle](https://doc.ibexa.co/en/latest/extending/import_assets_from_bundle/#configuration-from-a-bundle)" page, stating that now it's possible to place Ibexa Webpack Encore configuration in the project top-level directory `encore`. Applies …
=> IBX-2961: Refactored Extension to rely on Encore Configuration Dumper

src/bundle/Controller/ContentOnTheFlyController.php, src/bundle/Controller/UniversalDiscoveryController.php, src/bundle/Controller/UserOnTheFlyController.php, src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js, src/bundle/Resources/public/scss/_default-location.scss, src/bundle/Resources/public/scss/ibexa.scss, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig, src/bundle/Resources/views/themes/admin/content_type/relation_form_fields.html.twig, src/bundle/Resources/views/themes/admin/content_type/relation_list_form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig, src/bundle/Resources/views/themes/admin/ui/tag.html.twig, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js, src/lib/FieldType/Mapper/RelationFormMapper.php, src/lib/FieldType/Mapper/RelationListFormMapper.php, src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationStartingLocationId.php, src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2937
Not a stand alone PR.
- https://github.com/ibexa/core/pull/112
- https://github.com/ibexa/content-forms/pull/31
=> IBX-2937: Added new relation starting location options

src/lib/Behat/BrowserContext/ContentTypeContext.php
Failure:
https://github.com/ibexa/commerce/runs/7242133030?check_suite_focus=true
```
And I select "Content" category to Content Type definition                  # Ibexa\AdminUi\Behat\BrowserContext\ContentTypeContext::iSelectCategory()
Ibexa\Behat\Browser\Exception\TimeoutException: Element with CSS locator 'contentTypeCategoryList': ' div.ibexa-content-type-edit__add-field-definitions-group > ul > li:nth-child(n):not(.ibexa-popup-menu__item-action--disabled)' was not found. Timeout value: 3 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:59
Stack trace:
#0 vendor/ibexa/admin-ui/src/lib/Behat/Page/ContentTypeUpdatePage.php(86): Ibexa\Behat\Browser\Element\BaseElement->waitUntilCondition()
#1 vendor/ibexa/admin-ui/src/lib/Behat/BrowserContext/ContentTypeContext.php(1 …
```
=> [Behat] Make sure Content Type Update Page is loaded before further interactions

src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2779
Unification of caret icon in dropdown, as eralier it was different in whole system
=> IBX-2779: Unify ghost dropdown caret icon

src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3242
=> IBX-3242: Added twig macros for rendering form fields in edit base view

src/bundle/Resources/views/themes/admin/language/index.html.twig, src/lib/Behat/Page/LanguagePage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3388
Updated view of language details
=> IBX-3388: Updated language details according to invsion project

src/bundle/Resources/public/scss/_date-time-picker.scss, src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3386
=> IBX-3386: Fixed styles for schedule hiding menu

src/bundle/Resources/config/bazinga_js_translation.yaml, src/bundle/Resources/public/js/scripts/user.group.invitation.js, src/bundle/Resources/public/js/scripts/user.invitation.modal.js, src/bundle/Resources/public/scss/_alerts.scss, src/bundle/Resources/public/scss/_user-invitation-modal.scss, src/bundle/Resources/translations/user_invitation.en.xliff, src/bundle/Resources/views/themes/admin/content/modal/user_group_invitation_modal_form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/issue_duplicate.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/issue_email_empty.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/issue_email_not_valid.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/modal.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/modal_entry.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2534
Related PRs:
- https://github.com/ibexa/corporate-account/pull/40
=> IBX-2534: Improved invite users modal design

src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php, src/bundle/Resources/config/admin_ui_forms.yaml, src/bundle/Resources/config/services/components/content/edit.yaml, src/bundle/Resources/config/services/events.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/menu.yaml, src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js, src/bundle/Resources/public/js/scripts/admin.anchor.sections.navigation.js, src/bundle/Resources/public/js/scripts/admin.content.edit.js, src/bundle/Resources/public/scss/_content-edit.scss, src/bundle/Resources/public/scss/_main-container.scss, src/bundle/Resources/public/scss/_navigation-menu.scss, src/bundle/Resources/public/scss/ibexa.scss, src/bundle/Resources/translations/menu.en.xliff, src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig, src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig, src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig, src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/primary_section.html.twig, src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/secondary_section.html.twig, src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig, src/lib/Component/Content/ContentEditMetaFieldsComponent.php, src/lib/EventListener/SetViewParametersListener.php, src/lib/Form/Provider/GroupedNonMetaFormFieldsProvider.php, src/lib/Menu/ContentEditAnchorMenuBuilder.php, src/lib/Menu/Event/ConfigureMenuEvent.php, tests/bundle/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php, tests/lib/EventListener/SetViewParametersListenerTest.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3523
| Complementary PR | https://github.com/ibexa/taxonomy/pull/142
This PR changes sidebar menu in content editing interface to use tabs. Idea behind this is to separate typical fieldtypes from fieldtypes enriching content with new functionality. Good example is SEO - it isn't a field per se but rather a fieldtype handling functionality for the whole Content object. Taxonomy is another good example. Items assigned to Meta tabs are configured using semantic configuration:
```yaml
ibexa:
system: …
```
=> IBX-3523: Introduced tabs to left sidebar in Content Edit interface

src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3596
Previous PR:
- https://github.com/ibexa/admin-ui/pull/530
=> IBX-3596: Fix bronken validation messages in CI edit (again in one more place)

src/bundle/Resources/config/bazinga_js_translation.yaml, src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3459
=> IBX-3459: js error when trying create content type without defined fields

src/bundle/Resources/public/js/scripts/admin.content.edit.js, src/bundle/Resources/public/scss/_autosave.scss, src/bundle/Resources/translations/content.en.xliff
| Tickets       | https://issues.ibexa.co/browse/IBX-3532
=> IBX-3532: Improved autosave messages

src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig, src/lib/Behat/Component/ContentItemAdminPreview.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-3725
| Bug fix?      | maybe?
=> IBX-3725: Removed colon from Content View labels

src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss, src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3716
=> IBX-3716: Updated design of the selection field on the content preview screen

src/lib/Behat/Page/ContentTypeUpdatePage.php
JIRA: https://issues.ibexa.co/browse/IBX-3093
This PR adds a smal delay between the mouse over and click actions - because the error from JIRA still happens (https://github.com/ibexa/commerce/runs/8279366922?check_suite_focus=true) and I'm not sure we can do anything else.
=> [Behat] Added small waiting before adding new Content Type fields

src/bundle/Resources/config/services/form_processors.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/twig.yaml
| Tickets       | https://issues.ibexa.co/browse/IBX-3264
As we use that autowiring configuration here:
https://github.com/ibexa/core/blob/main/src/lib/Resources/settings/repository/autowire.yml#L29
https://github.com/ibexa/admin-ui/pull/549
https://github.com/ibexa/content-forms/pull/37
https://github.com/ibexa/permissions/pull/11
https://github.com/ibexa/corporate-account/pull/83
https://github.com/ibexa/compatibility-layer/pull/49
=> IBX-3264: Used service name based on interface instead of implementation

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig, src/bundle/Resources/views/themes/admin/content_type/list.html.twig
Follow up for https://github.com/ibexa/admin-ui/pull/556
Current status:
I've asked @DominikaK about them and we agreed that these notices can be improved - these new suggestions come from Dominika.
=> Fixed microcopy notice for Content Type Group and Groups

src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Hotfix for invalid mapping in `content.create.widget.js`, please see https://github.com/ibexa/admin-ui/actions/runs/3052837865/jobs/4922694267#step:13:2474
=> Hotfix for `content.create.widget.js`

src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3869
The problem occurred because bootstrap libraries changed the selectors for the buttons. It was necessary to set a more precise selector
=> IBX-3869: set more precise seletor for ibexa-btn

src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig, src/bundle/Resources/views/themes/admin/ui/component/table/table_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3799
I changed the default value for the variable headline_title in the table component and the headline table. Previously, the default value was set as headline and if there is no headline, it was set to an empty string.
Currently default is always an empty string and the user must set the headline_title variable to have a tooltip because according to our design system, if we have a label somewhere, we should not have a tooltip
=> IBX-3799: Change default value for headline_title in table

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3922
=> IBX-3922: Fix dropdown inside modal

src/lib/Behat/Page/ContentTypeGroupPage.php
| Tickets       | n/a
Example error:
https://github.com/ibexa/commerce/actions/runs/3215686319/jobs/5257026001
```
And I start editing Content Type "CustomLaunchModeLandingPage"                                                             # Ibexa\AdminUi\Behat\BrowserContext\ContentTypeContext::iStartEditingItem()
WebDriver\Exception\ElementClickIntercepted: element click intercepted: Element <a href="/admin/contenttypegroup/1/contenttype/92/edit" class="btn ibexa-btn ibexa-btn--ghost ibexa-btn--no-text" data-original-title="Edit" aria-label="Edit" …
```
=> [Behat] Scrolled to the bottom to avoid "Go to the top" button

src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig, src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/content/edit_macros.html.twig, src/bundle/Resources/views/themes/admin/ui/component/extra_actions/extra_actions.html.twig, src/bundle/Resources/views/themes/admin/ui/component/extra_actions/extra_actions_container.html.twig, src/bundle/Resources/views/themes/admin/ui/layout.html.twig
=> IBX-3682: AdminUI extension points to be used by Corporate Account

src/bundle/Resources/public/scss/_inputs.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3800
Requires: 
- https://github.com/ibexa/commerce-admin-ui/pull/58
=> IBX-3800: Z-index for inputs actions button

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss, src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss, src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig, src/bundle/Resources/views/themes/admin/object_state/view.html.twig, src/bundle/Resources/views/themes/admin/ui/menu/context_menu.html.twig, src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php, src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php, src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php, src/lib/Menu/Admin/ObjectState/ObjectStateCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ObjectState/ObjectStateEditRightSidebarBuilder.php, src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php, src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php, src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php, src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php, src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Menu/SectionCreateRightSidebarBuilder.php, src/lib/Menu/SectionEditRightSidebarBuilder.php, src/lib/Menu/URLEditRightSidebarBuilder.php, src/lib/Menu/URLWildcardEditRightSidebarBuilder.php, src/lib/Menu/UserCreateRightSidebarBuilder.php, src/lib/Menu/UserEditRightSidebarBuilder.php, src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-3937
=> IBX-3937: First button primary- creating/editing/updating forms

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-2624
| Releated PR | https://github.com/ibexa/product-catalog/pull/824
=> IBX-2624: Disabled validation for discard changes

src/bundle/Resources/public/scss/_card.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4028
=> IBX-4028: Set default background of ibexa-card to transparent

src/bundle/Command/CompileAssetsCommand.php
| Tickets       | https://issues.ibexa.co/browse/IBX-2817
Propagation of the change from this PR: https://github.com/ezsystems/ezplatform-core/pull/55 because the command has been moved to admin-ui
=> IBX-2817: Input timeout string casted to float for ibexa:encore:compile command

src/bundle/Resources/config/services/role_form_mappers.yaml, src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff, src/bundle/Resources/translations/ibexa_content_forms_policies.en.xliff, src/bundle/Resources/translations/ibexa_content_forms_role.en.xliff, src/bundle/Resources/views/themes/admin/limitation/limitation_values.html.twig, src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php, src/lib/Translation/Extractor/LimitationTranslationExtractor.php
| Tickets       | [IBX-4032](https://issues.ibexa.co/browse/IBX-4032)
Admin UI Interface (form mapper) for new `ChangeOwner` limitation added to `ibexa/core`.
=> IBX-4032: Added limitation to prevent changing content ownership

src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3524
=> IBX-3524: Removed icon and added default none to dropdown placeholder

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3301
=> IBX-3301: Product type - disable button Add when there is no option to add more elements

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
| Tickets       | https://issues.ibexa.co/browse/IBX-3901
=> IBX-3901: Add empty field after bulk delete all authors

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js, src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4044
| Doc needed?   | maybe?
If he have documented using tooltips anywhere, it's probably worth adding that HTML is now switched of by default and to use HTML in tooltips `data-tooltip-use-html` parameter has to be added on node with title.
Also for QA - as default using HTML was switched off in whole system, there can be missed places where it should be switched on and I missed them, so probably that's thing worth checking as well. Sorry!
=> IBX-4044: Option to use HTML in tooltips

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4273
=> IBX-4273: Missing translation for field_definition in content type (and wrong domain)

src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js, src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js, src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js, src/bundle/Resources/public/scss/_date-time-picker.scss, src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezmedia.scss, src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss, src/bundle/Resources/views/themes/admin/content/form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezauthor.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdatetime.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezgmaplocation.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezmedia.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/eztime.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/toggle_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3973
=> IBX-3973: Nontranslatable and disabled fields are not greyed out in content editing UI

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_content-type-selector.scss, src/bundle/Resources/public/scss/_header-user-menu.scss, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/public/scss/_main-header.scss, src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4213
=> IBX-4213: Missing hovers on icons

src/bundle/Resources/public/js/scripts/core/custom.tooltip.js, src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tab-selector/tab.selector.js, src/lib/Behat/Component/UniversalDiscoveryWidget.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4277
=> IBX-4277: [UDW] Tooltips from left menu aren't visible

src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js, src/bundle/Resources/public/scss/_tag.scss, src/bundle/Resources/views/themes/admin/ui/tag.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3619
| Doc needed?   | don't know?
=> IBX-3619: Tag update helper

src/lib/Behat/Component/Fields/User.php, src/lib/Behat/Component/UniversalDiscoveryWidget.php
This PR tries to fix three recently common failures:
1) User Creation
https://github.com/ibexa/experience/actions/runs/3527356556/jobs/5916328659
```
And I set content fields for user                                   # Ibexa\AdminUi\Behat\BrowserContext\ContentUpdateContext::iSetFieldsForUser()
| label        | Username | Password   | Confirm password | Email         | Enabled |
| User account | testuser | Test1234pw | Test1234pw       | test@test.com | Yes     |
Ibexa\Behat\Browser\Exception\TimeoutException: Element with CSS locator 'buttonEnabledToggleConfirmation': '.ibexa-toggle--is-checked' was not found. Timeout value: 10 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:59
```
2) Switching UDW tabs …
=> [Behat] Stability fixes

src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js, src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig, src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3792
This PR provides fix for COTF edit / create view to display missing anchor menu.
=> IBX-3792: Fixed display meta tab

src/lib/EventListener/AdminExceptionListener.php
| Tickets       | [IBX-4636](https://issues.ibexa.co/browse/IBX-4636)
This PR replaces the no longer used "ezplatform" entry point with "ibexa".
=> Changed Entrypoint in AdminExceptionListener from "ezplatform" to "ibexa"

src/bundle/Resources/public/js/scripts/admin.preview.js, src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig, src/lib/Behat/Page/ContentPreviewPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4328
=> IBX-4328: Hover on icons preview switcher

src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig, src/bundle/Resources/views/themes/admin/ui/layout.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4544
This pull request removes menu from 404 page error. The menu appearing on the 404 page resulted in an infinite loop.
=> IBX-4544: Removed menu items from 404 page causing loops and timeouts

src/lib/Form/Type/Policy/PolicyChoiceType.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4717
This PR fixes issues with missing role translations on edit limitation page. Caused by missing defaults translation domain configuration.
=> IBX-4717: Fixed PolicyChoiceType translation domain configuration

src/bundle/Resources/translations/universal_discovery_widget.en.xliff, src/bundle/ui-dev/src/modules/common/input/filter.search.js
| Tickets       | [IBX-4520](https://issues.ibexa.co/browse/IBX-4520)
| Doc needed?   | not sure
Implemented filter search as a component in react
=> IBX-4520: implemented filter search as a component in react

src/bundle/Resources/public/js/scripts/core/date.time.picker.js
| Tickets       | [IBX-4576](https://issues.ibexa.co/browse/IBX-4576)
Related to https://github.com/ibexa/scheduler/pull/77 (merge up)
=> IBX-4576: Added a keyup event so that set minutes and hours can be set from the keyboard

src/bundle/Resources/encore/ibexa.css.config.js, src/bundle/Resources/public/scss/_flatpickr.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4327
| Bug fix?      | bug
Added css for confirmDate plugin for flatpickr
Requires https://github.com/ibexa/admin-ui-assets/pull/14
Here is built version of assets: https://github.com/ibexa/admin-ui-assets/pull/15
=> IBX-4327: Content airtime settings modal design

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4678
=> IBX-4678: Unnecessary remove icon in enabled state of inputs- Article content form

src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
| Tickets       | [IBX-4972](https://issues.ibexa.co/browse/IBX-4972)
Middle elippsis fixed container class checked
=> IBX-4972: Middle elippsis fixed container class checked

src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php, src/bundle/Resources/config/admin_ui_forms.yaml, src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig, src/lib/Behat/BrowserContext/ContentUpdateContext.php, src/lib/Behat/Page/ContentUpdateItemPage.php, src/lib/Component/Content/ContentEditMetaFieldsComponent.php, src/lib/EventListener/SetViewParametersListener.php, src/lib/Form/Provider/GroupedNonMetaFormFieldsProvider.php, src/lib/Menu/ContentEditAnchorMenuBuilder.php, tests/bundle/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php, tests/lib/EventListener/SetViewParametersListenerTest.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4629
A new configuration has been implemented that allows configuring fieldgroups that would be shown in the "Meta" section in the content form:
```
system:
admin_group:
admin_ui_forms:
content_edit:
meta_field_groups_list:
- metadata
```
The default value is set to `metadata`, however, one can configure it to include any of available fieldgroups or even disable this feature:
```
system:
admin_group:
admin_ui_forms:
content_edit:
meta_field_groups_list: []
```
The `meta_fieldgroup_list` configuration is …
=> IBX-4629: Implement Meta field groups

src/lib/Behat/Component/SubItemsList.php
https://github.com/ibexa/experience/actions/runs/4088165529/jobs/7049534493
```
| root/FolderGrandParent/FolderParent/FolderChild1 | NewContent2 | NewContent2Edited | root/FolderGrandParent/FolderParent/FolderChild1 |
| root/FolderGrandParent/FolderParent              | NewContent1 | NewContent1Edited | root/FolderGrandParent/FolderParent              |
Failed step: Given I navigate to content "NewContent1" of type "DedicatedFolder" in "root/FolderGrandParent/FolderParent"
Ibexa\Behat\Browser\Exception\ElementNotFoundException: Could not find element named: 'Modified'. Collection is empty. CSS locator 'horizontalHeaders': '.m-sub-items .ibexa-table__header-cell'. in vendor/ibexa/behat/src/lib/Browser/Element/ElementCollection.php:61
```
Increasing the timeout should do …
=> [Behat] Increased timeout when searching for subitem headers

src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff, src/bundle/Resources/translations/validators.en.xliff, src/lib/Validator/Constraints/UniqueContentTypeIdentifier.php, src/lib/Validator/Constraints/UniqueFieldDefinitionIdentifier.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4922
=> IBX-4922: [Product type] Missing translation for validation message for identifier field and notification message

src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-4937
This is fix for OSS version. For Content and above fix is in Tree Builder bundle: 
To whomever testing this - after clicking enter for executing script, you can go make a tea, script to generate 2000 contents takes around 10 minutes. ;)
=> IBX-4937: Content Tree has CSS issues when loading plenty of children under a node

src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| Tickets       | [IBX-4993](https://issues.ibexa.co/browse/IBX-4993)
| Bug fix?      |no
| BC breaks?    |no
| Doc needed?   |no
Changed template to display table headers for single/multiple relations fields in the content preview
=> IBX-4993 changed content_fields.html.twig to display table header for single/multiple relation in preview

src/bundle/Resources/config/services/events.yaml
| Tickets       | [IBX-4386](https://issues.ibexa.co/browse/IBX-4386)
This PR fixes an issue that occurs in other libraries making use of `admin-ui`:
```
Error in bootstrap script: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException:
A binding is configured for an argument of type "string" named "$logLevel" under "_defaults" in file "/.../admin-ui/src/bundle/DependencyInjection/../Resources/config/services/events.yaml", but no corresponding argument has been found. It may be unused and should be removed, or it may have a typo.
```
I have …
=> IBX-4386: Removed argument binding to prevent breaking external libraries

src/bundle/Resources/public/js/scripts/core/date.time.picker.js, src/bundle/Resources/public/scss/_date-time-picker.scss, src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4791
With: https://github.com/ibexa/page-builder/pull/193
=> IBX-4791: [Date picker] Cannot open date time picker by clicking on calendar icon in the input

src/lib/Behat/Component/UniversalDiscoveryWidget.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4483
| Bug fix?      | no (issue in tests)
Changed the code to stop relying on `data-original-title` attribute - according to what @GrabowskiM told me it there can be a small delay before the attribute is added (because it's processed by MutationObserver).
Instead of adding a `usleep(100);` I've decided to change the way we verify the tab is loaded.
=> [Behat] Removed code reliant on MutationObserver changes

src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/js/scripts/admin.form.error.js, src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js, src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/js/scripts/helpers/form.error.helper.js, src/bundle/Resources/public/js/scripts/user_password.change.js, src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/public/scss/mixins/_inputs.scss, src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig, src/bundle/Resources/views/themes/admin/content/form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/issue_email_empty.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/issue_email_not_valid.html.twig, src/bundle/Resources/views/themes/admin/user/invitation/modal_entry.html.twig, src/lib/Behat/Page/AdminUpdateItemPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-4339
=> IBX-4339: Input validation - wrong style

src/bundle/Resources/public/js/scripts/admin.table.js, src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5017
=> IBX-5017: Select all checkbox in Relation List is inconsistent

src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-2778
PR from Perso: https://github.com/ibexa/personalization/pull/157 (for reference, in comments there are some bugs mentioned)
That's all frontend part, ad2. that's backend change, a little bigger as I see.
=> IBX-2778: Personalization - Wrong styles for Scenarios

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4887
=> IBX-4887: Content type group with space or '/' causes js an error in the BackOffice search

src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4681
As discussed with backend team, it's not possible to customize section order per CT, so we remove icon and possibility to drag sections (which does nothing in fact).
=> IBX-4681: Cannot swap sections with D&D in Content/Product Type

src/bundle/Resources/public/js/scripts/admin.table.js, src/bundle/Resources/public/scss/_tables.scss, src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4445
| Doc needed?   | maybe?
=> IBX-4445: Option to add last column in tables as sticky

src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss, src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5151
=> IBX-5151: [Subitems] Clicking arrow in non-focused input priority doesn't change value

src/bundle/Resources/public/js/scripts/edit.header.js, src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js, src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/public/scss/_middle-ellipsis.scss, src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5138
=> IBX-5138: The header in content edit view is displayed incorrectly when scrolling

src/bundle/Resources/public/scss/_badges.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5131
=> IBX-5131: Add status badge

src/bundle/Controller/ContentTypeGroupController.php, src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/content_type/content_type_group/index.html.twig, src/bundle/Resources/views/themes/admin/content_type/list.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5018
Updated Content Type list template to match Content Type Group list template when it comes to the 'Create' buttons.
After:
=> IBX-5018: Unified 'Create' buttons in Content Types and Content Type Groups lists

src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js, src/bundle/Resources/public/js/scripts/helpers/form.error.helper.js, src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js, src/bundle/Resources/public/js/scripts/user_password.change.js, src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5255
=> IBX-5255: Move required validation method to helpers

src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5248
=> IBX-5248: Fixed checkbox alignment in content center table cell

src/lib/Behat/Component/Fields/RichText.php
Needed for https://github.com/ibexa/recipes-dev/pull/55 and https://github.com/ibexa/admin-ui-assets/pull/17
This PR changes how the offset is calculated when Custom Styles are used - only the inline ones are counted.
=> [Behat] Keep only inline custom styles to calculate offset

src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php
| Tickets       | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
Fix ChangeOwnerLimitationMapper::getSelectionChoices phpDoc by removing the possibility for the key to be `null`.
From phpDocumentor v3.3.1: `Unable to parse file "vendor/ibexa/admin-ui/src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php", an error was detected: An array can have only integers or strings as keys`
- When used as a key, `null` is casted to an empty string so it can't be a key.
-  [`ChangeOwnerLimitation::LIMITATION_VALUE_SELF`](https://github.com/ibexa/core/blob/main/sr …
=> IBX-4929: ChangeOwnerLimitationMapper: Fix phpDoc

src/bundle/Controller/TrashController.php
| Tickets       | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
| Tests pass?   | n/a
`TrashController::listAction` method was ignored by phpDocumentor because of two `@internal` tags. As those tags seems meaningless, I propose their removal.
=> IBX-4929: TrashController::listAction: remove @internal

src/bundle/Command/CompileAssetsCommand.php, src/bundle/Resources/config/services/commands.yaml
This PR makes the `CompileAssets` command respect the `COMPOSER_PROCESS_TIMEOUT` environment variable if present.
=> Allowed CompileAssets Command to respect COMPOSER_PROCESS_TIMEOUT env variable

src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/menu.yaml, src/lib/Component/Content/PreviewUnavailableTwigComponent.php, src/lib/Form/Type/ChoiceList/Loader/SiteAccessChoiceLoader.php, src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php, src/lib/Menu/ContentEditRightSidebarBuilder.php, src/lib/Siteaccess/NonAdminSiteaccessResolver.php, src/lib/Siteaccess/SiteaccessResolver.php, src/lib/Siteaccess/SiteaccessResolverInterface.php
| Tickets       | https://issues.ibexa.co/browse/IBX-5121
| Doc needed?   | no(?)
As a part of changes, I moved `\Ibexa\PageBuilder\Siteaccess\SiteaccessService::resolveSiteAccessForContent` into  `\Ibexa\AdminUi\Siteaccess\SiteaccessResolverInterface` as it seems that is a proper place for it. As additional cleanup, I had deprecated `\Ibexa\AdminUi\Siteaccess\SiteaccessResolverInterface::getSiteaccessesForLocation` as `getSiteAccessesListForLocation` does basically the same thing, and the naming is quite confusing - same thing was done for `getSiteaccesses` method.
=> IBX-5121: Streamlined SiteaccessResolverInterface

src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5288
It's needed as payment details status has dynamic colors defined in yaml
=> IBX-5288: Added extra attr for tag

src/bundle/Resources/public/js/scripts/core/tag.view.select.js, src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
| Tickets       | [IBX-5412](https://issues.ibexa.co/browse/IBX-5412)
| Doc needed?   |no
=> IBX-5412: Removed parseInt from selectedItem.dataset.id

src/bundle/Resources/public/scss/_popup-menu.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5368
=> IBX-5368: fix popup menu item height for multiline items

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/lib/FieldType/Mapper/UserAccountFormMapper.php
| Tickets       | [IBX-5361](https://issues.ibexa.co/browse/IBX-5361)
See description in the companion PR https://github.com/ibexa/core/pull/221. That PR adds the feature that this one adds admin UI for. The feature is disabled by default, for BC.
**Documentation**
The [password rules page](https://doc.ibexa.co/en/latest/users/user_management/#password-rules) would need documentation for this feature.
**Screenshot**
=> IBX-5361: Use NotCompromisedPassword constraint

src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
| Tickets       | https://issues.ibexa.co/browse/IBX-4012
We need to recalculate last section padding in case of when there is dynamically loaded content, as it changes content height and breaks proper selecting of active section in left nav menu
=> IBX-4012: [Sections] Recalculate last section padding on section height change

src/bundle/Resources/public/js/scripts/adaptive.filters.js, src/bundle/Resources/public/scss/_adaptive-filters.scss, src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5622
=> IBX-5622: Adaptive filters styling improvements

src/bundle/Resources/translations/content_type.en.xliff, src/bundle/Resources/views/themes/admin/ui/modal/delete_confirmation.html.twig, src/lib/FieldType/Mapper/UserAccountFormMapper.php
| Tickets       | https://issues.ibexa.co/browse/IBX-5565
=> IBX-5565: Add reusable delete confirmation modal

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/scss/_dropdown.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5576
=> IBX-5576: [Payments] Issues with filters

src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5635
=> IBX-5635: [Payments] Missing placeholder after removing all items from the filter

src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://issues.ibexa.co/browse/IBX-5382
Minor refactoring to avoid checking if every location is bookmarked.
=> IBX-5382: Optimize Content Tree node building when it comes to bookmarks

src/bundle/Resources/public/scss/_tag-view-select.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5400
Currently there's also problem that prevents closing UDW after confirming - you can close UDW manually and item is still aded however, but this bug also prevents name from being ellipsized - PR https://github.com/ibexa/admin-ui/pull/773 fixes that issue (so ideally IBX-5400 should be tested after mergind admin-ui/773)
=> IBX-5400: Subtree Filter with content long name have remove icon outside of badge

src/lib/Behat/Component/UniversalDiscoveryWidget.php
Failure: https://github.com/ibexa/experience/actions/runs/4840933996
Testing if increasing the timout will help - because you can see on the screen that UDW is correctly closed , the issue is not that it stays open.
=> [Behat] Increased timeout for UDW closing

src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5702
This PR fixes `ezselection` field rendering when field should be displayed as readonly. In case when field is set as required and not-translatable, value for `ezselection` field is not sent because source field contains disabled attribute.
=> IBX-5702: Fixed ezselection rendering

src/bundle/Resources/translations/dropdown.en.xliff, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
Fixes 
```
The message 'dropdown.placeholder' exists with two different descs: 'All' in /vendor/ibexa/admin-ui/src/bundle/DependencyInjection/../../../src/bundle/Resources/views/themes/a  
dmin/ui/component/dropdown/dropdown.html.twig on line 75, and 'Choose an option' in /vendor/ibexa/admin-ui/src/bundle/DependencyInjection/../../../src/bundle/Resources/views/t  
hemes/admin/ui/component/dropdown/dropdown.html.twig on line 115 
``` 
error
=> Changed translation key to avoiding duplication of keys

src/lib/Behat/Component/Fields/User.php
> JIRA: [IBX-4482](https://issues.ibexa.co/browse/IBX-4482)
A bug fix for toggle button enabled on user creation form.
An example of failed build: https://github.com/ibexa/content/actions/runs/4919955972/jobs/8788215942
=> [Behat] IBX-4482 Fix for toggle button enabled

src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5606
The  `containerResizeObserver` injected into `componentDidMount` method actually causes double GraphQL requests. Component is immediately updated because of `containerResizeObserver`, hence firing `componentDidUpdate` method, hence second GraphQL request.
=> IBX-5606: Removed duplicated GraphQL request in the Subitems module

src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4674
=> IBX-4674: Unnecessary wrap on text in checkbox on field - opened accordion

src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5620
| BC breaks?    | o
=> IBX-5620: Fixed validation in change password

src/bundle/Resources/public/scss/_details.scss, src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig, src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5778
=> IBX-5778: CT translation dropdown is not aligned and its placement is wrong place

src/bundle/ui-dev/src/modules/common/helpers/css.class.names.js
| Tickets       | [IBX-5429](https://issues.ibexa.co/browse/IBX-5429)
Fixed empty spaces when creating classes
=> IBX-5429: Fixed empty spaces when creating classes

src/lib/Resolver/IconPathResolver.php
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-5672](https://jira.ez.no/browse/IBX-5672)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | 2.3
| **BC breaks**      | no
| **Tests pass**     | yes/no
| **Doc needed**     | yes/no
Add simple in-memory cache for IconPathResolver::resolve() to speed up icon handling. Often, the same icon ( like `checkmark` ) are used many times on the same page
FYI : You my find info from blackfire in the Jira ticket
**TODO**:
=> IBX-5672: Performance Improvement of IconPathResolver::resolve()

src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/public/scss/_main-container.scss
| Tickets       | [IBX-5784](https://issues.ibexa.co/browse/IBX-5784)
| | [IBX-5743](https://issues.ibexa.co/browse/IBX-5743)
| | [IBX-4329](https://issues.ibexa.co/browse/IBX-4329)
CkEditor toolbar overflow fix
=> IBX-5784: CkEditor toolbar overflow fix

src/bundle/Resources/public/scss/_filters.scss, src/bundle/Resources/public/scss/_search-form.scss
| Tickets       | [IBX-5181](https://issues.ibexa.co/browse/IBX-5181)
=> IBX-5181 fix ui texts position

src/lib/Form/Type/ContentType/FieldDefinitionsCollectionType.php
| Tickets       | [IBX-5411](https://issues.ibexa.co/browse/IBX-5411)
This PR fixes an issue with Content Type update form in UI which occurs when:
1. A field is removed from a Content Type (AJAX request starts).
2. Form is submitted.
3. AJAX request resolves or for any other reason HTML form elements are not (yet) removed from DOM when form submission occured.
Despite the description in the issue suggesting this is related to field groups, it is in fact related to race condition between Javascript UI changes and normal browser submission.
While the main issue lies in the aforementioned race …
=> IBX-5411: Fixed form exception due to incomplete field definition

src/lib/Behat/Component/Fields/ContentRelationSingle.php
Fix for create and edit company form.
Issue:
`Facebook\WebDriver\Exception\ElementClickInterceptedException: element click intercepted: Element <span class="ibexa-relations__cta-btn-label">...</span> is not clickable at point (484, 820). Other element would receive the click: <p class="ibexa-relations__helper-text">...</p>`
Failure example:
https://github.com/ibexa/experience/actions/runs/5272432723/jobs/9534689193
PR and regression build Exp:
https://github.com/ibexa/experience/pull/191
https://github.com/ibexa/experience/actions/runs/5282065720/jobs/9556504632?pr=191
=> [Behat] Fix for create and edit company form

src/lib/Behat/Component/Fields/ContentRelationSingle.php
Fix for company edition.
Issue:
`Ibexa\Behat\Browser\Exception\TimeoutException: CSS selector 'combined--selectContent': 'div.ibexa-field-edit:nth-of-type(6) .ibexa-relations__cta-btn-label' not found in 1 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79`
Failure example:
https://github.com/ibexa/experience/actions/runs/5305890694/jobs/9603136896
Regression builds (experience and commerce):
https://github.com/ibexa/experience/pull/193
https://github.com/ibexa/commerce/pull/287
=> [Behat] Fix for company edition

src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
| Tickets       | [IBX-6003](https://issues.ibexa.co/browse/IBX-6003)
=> IBX-6003: Fixed tab rendering after changing page in the Assignments tab in the Roles module

src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
| Tickets       | https://issues.ibexa.co/browse/IBX-5981
=> IBX-5981: Fixed mutation observer in content create validation

src/lib/Behat/Component/Fields/ContentRelationSingle.php
Failure: https://github.com/ibexa/experience/actions/runs/5448786834/jobs/9912374424
```
And I set content fields                                                                            # Ibexa\AdminUi\Behat\BrowserContext\ContentUpdateContext::iSetFields()
| label          | value                                                   |
| Is active      | true                                                    |
| Name           | Ibexa Poland Sp. z o.o.                                 |
| Tax ID         | 200027649902100895                                      |
| Website        | www.ibexa.co                                            |
| Customer group | Customer group for corporate account                    |
| Sales rep      | Users/Sales reps/SalesRepFirstCreate SalesRepLastCreate | …
```
=> [Behat] Added small wait before interacting with Single relation button

src/bundle/Resources/public/scss/_search-form.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5869
=> IBX-5869: Search results table view for many translations

src/lib/Behat/Page/ContentTypeUpdatePage.php
Potential fix for https://issues.ibexa.co/browse/IBX-6122
It seems that the `mouseOver` action is not always registered, I've added a retry mechanism so that we do it untill the mouseOver effect happens.
Tested in:
https://github.com/ibexa/experience/pull/205
https://github.com/ibexa/commerce/pull/310
in which the failure did not occur at all.
=> [Behat] Hardened Field Type adding

src/bundle/Resources/public/js/scripts/core/tag.view.select.js
| Tickets       | [IBX-6001](https://issues.ibexa.co/browse/IBX-6001)
=> IBX-6001: Added cast items array to String

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6160
=> IBX-6160: Fix tooltip text height calculation

src/bundle/Resources/public/scss/_field-group.scss, src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-4172
=> IBX-4172: Fixed jumping headline in content structure

src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-3675
Related PRs:
- https://github.com/ibexa/page-builder/pull/231
=> IBX-3675: Fix unavailable state styling of PB sidebar blocks (d&d)

src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6327
=> IBX-6327: Added missing content_type_name parameter

src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js, src/bundle/Resources/public/scss/_anchor-navigation.scss, src/bundle/Resources/public/scss/_switcher.scss, src/bundle/Resources/public/scss/ibexa.scss, src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig, src/lib/Behat/Page/ContentUpdateItemPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6240
=> IBX-6240: Create general css classes for switcher (from edit form left menu)

src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6260
Possible siteAccesses to display given content should not take language order into consideration. It should be matter of selector, to pick _the most proper_ one out of those.
This same issue came up, when having identical siteAccess configuration (as in ticket), you tried to just translate any other content into other language and you get `Preview unavailable` information, when there clearly was one to do it.
Same issue goes up in 3.3 version, but as there, page-builder logic is separated from this …
=> IBX-6260: Fixed preview voter taking language priority into consideration

src/bundle/Resources/config/services/forms.yaml, src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php, src/lib/Form/Type/Content/Draft/ContentCreateType.php, src/lib/Form/Type/Event/ContentCreateContentTypeChoiceLoaderEvent.php
| Tickets       | [IBX-5886](https://issues.ibexa.co/browse/IBX-5886)
This PR refactors `ContentCreateType` to utilize `ContentCreateContentTypeChoiceLoader` as a service. Aside from that event is dispatched when loading content types.
Related PR: https://github.com/ibexa/taxonomy/pull/215
=> IBX-5886: Dispatched `ContentCreateContentTypeChoiceLoaderEvent`

src/lib/Behat/Component/Fields/Matrix.php, src/lib/Behat/Component/Table/TableBuilder.php, src/lib/Behat/Component/UniversalDiscoveryWidget.php, src/lib/Behat/Page/ContentTypePage.php, src/lib/Behat/Page/ContentTypeUpdatePage.php, src/lib/Behat/Page/SystemInfoPage.php
| Tickets       | [IBX-6230](https://issues.ibexa.co/browse/IBX-6230)
| Bug fix?      | no (behat)
This is the second part of the task (first part is done in https://github.com/ibexa/behat/pull/69 which covers validation for new selectors).
This fixes existing wrong selectors in this repo.
Tests for all PRs combined: https://github.com/ibexa/commerce/pull/348.
=> IBX-6230: Fix incorrect CSS selectors in Behat code

src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
| Tickets       | [IBX-6261](https://issues.ibexa.co/browse/IBX-6261)
When switching from Search module locations were cleared, this shouldn't be the case now.
=> IBX-6261: Fixed UDW Search module to set locations when unmounting

behat_suites.yml, features/standard/MyDrafts.feature, src/bundle/Resources/config/services/test/feature_contexts.yaml, src/bundle/Resources/config/services/test/pages.yaml, src/lib/Behat/BrowserContext/MyDraftsContext.php, src/lib/Behat/Page/MyDraftsPage.php
| Tickets       | <https://issues.ibexa.co/browse/IBX-6330>
=> IBX-6330: [Behat] Cover "My Drafts" Page

src/bundle/Resources/views/themes/admin/user/create.html.twig, src/bundle/Resources/views/themes/admin/user/edit.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6342
=> IBX-6342: Fixed richtext field in user content type

src/bundle/Resources/config/ezplatform_default_settings.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/bundle/Resources/public/js/scripts/adaptive.filters.js, src/bundle/Resources/public/js/scripts/helpers/cookies.helper.js, src/bundle/Resources/public/js/scripts/sidebar/main.menu.js, src/lib/UI/Config/Provider/CurrentBackOfficePath.php
| Tickets       | https://issues.ibexa.co/browse/IBX-5854
For @ibexa/javascript-dev,
we would also need to unify used cookies names, as atm we have:
```
second_menu_width
ibexa-tb-ibexa-category-filter-tree-%d-container-width
ibexa-tb-ibexa-taxonomy-tree-%d-+-container-width
ibexa-tb-ibexa-content-tree-%d-container-width
ibexa_adaptive_filters-is_expanded-ibexa_om_orders_list
```
This is just part of the solution for the issue. What needs to be checked here if backoffice path is always properly added to adminUI conig with different siteAccess …
=> IBX-5854: Added base backoffice path to adminUI config

features/standard/SystemInfo.feature
| Tickets       | https://issues.ibexa.co/browse/IBX-6314
| Needs      | https://github.com/ibexa/system-info/pull/44
This PR is a result of changing the tab name to `Product` in `system-info` package https://github.com/ibexa/system-info/pull/44/files#diff-3e96dfcf9b3d195658a34706c41dd70943c731a874f92bf5f749cb5dff6c8f0fR3
https://github.com/ibexa/system-info/actions/runs/6035157816/job/16374967649?pr=44
=> Fixed Behat tests

src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/public/scss/_main-container.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-5743
=> IBX-5743: Fixed header z-index in edit mode

behat_suites.yml, features/standard/MyDrafts.feature, src/bundle/Resources/config/services/test/feature_contexts.yaml, src/bundle/Resources/config/services/test/pages.yaml, src/lib/Behat/BrowserContext/MyDraftsContext.php, src/lib/Behat/Page/MyDraftsPage.php
| Tickets       | [IBX-6406](https://issues.ibexa.co/browse/IBX-6406)
Its backport from #878
Test contains editing and deleting a draft.
=> IBX-6406: Cover "My Drafts" Page - Back-port to 4.5

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3698
Added properties `help_attr.with_icon|default(true)` to display icons in the `form_help` block
=> IBX-3698: Conditional icon for form_help

src/bundle/Resources/public/scss/_buttons.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6252
TODO:
title/hover on disabled button doesn't work
=> IBX-6252: Update hover styles for --selector button

src/bundle/Resources/config/services/test/components.yaml, src/lib/Behat/Component/PropertiesList.php
JIRA: https://issues.ibexa.co/browse/IBX-6335
This PR adds PropertiesList component to verify value of fields in content tabs.
=> [Behat] IBX-6335: Added PropertiesList component

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
| Tickets       |  [IBX-6339](https://issues.ibexa.co/browse/IBX-6339) 
| License       | [GPL-2.0](https://github.com/ibexa/search/blob/main/LICENSE)
Depends on https://github.com/ibexa/search/pull/26
=> IBX-6339: As an Editor I'd like use facets to filter global search results

src/bundle/Resources/translations/ibexa_dashboard.en.xliff, src/bundle/Resources/translations/ibexa_menu.en.xliff, src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig, src/lib/Menu/MainMenuBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6502
=> IBX-6502: Drafts under content

src/bundle/Resources/encore/ibexa.js.config.js, src/bundle/Resources/public/js/scripts/helpers/system.helper.js
| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-6492](https://issues.ibexa.co/browse/IBX-6492) |
| **Type**                                   | improvement |
| **Target Ibexa version** | `v4.6` |
| **BC breaks**                          | no |
Keyboard support for redo and undo
=> IBX-6492: Keyboard support for redo  and undo

src/bundle/Resources/config/services/validators.yaml
| Tickets       | [IBX-6627](https://issues.ibexa.co/browse/IBX-6627)
Deprecated Since eZ Platform 3.0.2 class moved to EzPlatformUser Bundle, and removed since Ibexa DXP 4.0 https://github.com/ezsystems/ezplatform-admin-ui/blob/118c25f18088cf556c65291e1035c9a0e3916c58/src/lib/Validator/Constraints/UserPasswordValidator.php#L19C66-L19C66.
=> IBX-6627: Removed non-existing service definition

src/lib/Form/Data/Content/Draft/ContentCreateData.php
| Tickets       | [IBX-5280](https://issues.ibexa.co/browse/IBX-5280)
=> IBX-5280: Added constraint LocationIsContainer to parentLocation in ContentCreateData

src/bundle/Resources/public/js/scripts/fieldType/ezdate.js, src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js, src/bundle/Resources/public/scss/_mixins.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6343
=> IBX-6343: ezdate and ezdatetime validation is styled properly

src/bundle/Resources/public/js/scripts/sidebar/main.menu.js, src/bundle/Resources/views/themes/admin/content/location_view.html.twig, src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig, src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-5854
| BC breaks?    | yno
https://github.com/ibexa/product-catalog/pull/1070
https://github.com/ibexa/taxonomy/pull/232
https://github.com/ibexa/tree-builder/pull/116
=> IBX-5854: Unified cookies names

src/bundle/Resources/translations/ibexa_content_create.en.xliff, src/bundle/Resources/translations/ibexa_content_edit.en.xliff, src/bundle/Resources/views/themes/admin/content/create/create.html.twig, src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig, src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6475
- https://github.com/ibexa/taxonomy/pull/234
=> IBX-6475: Fix translation variable visible in UI

.github/workflows/browser-tests.yaml
Example failing job:
https://github.com/ibexa/admin-ui/actions/runs/6392168048/job/17348897150?pr=929
```
Examples:
| fieldInternalName    | fieldName                    | fieldSettings | label1    | value1       | label2     | value2      | label3 | value3 | contentItemName |
| ezobjectrelation     | Content relation (single)    |               | value     | Media/Images |            |             |        |        | Images          |
Failed step: Then success notification that "Content published." appears
Facebook\WebDriver\Exception\StaleElementReferenceException: stale element reference: element is not attached to the page document
(Session info: chrome=110.0.5481.177) in vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:132
```
For some reason the notifications stop …
=> [CI] Increased job count for Behat

src/bundle/Resources/public/scss/_grid-view-item.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss, src/bundle/Resources/views/themes/admin/ui/component/grid_view/grid_view_item.html.twig, src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6599
- https://github.com/ibexa/personalization/pull/306
- https://github.com/ibexa/site-factory/pull/79
=> IBX-6599: New grid view item design

src/bundle/Resources/public/scss/_content-type-edit.scss, src/bundle/Resources/views/themes/admin/content_type/edit_section.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-3240
=> IBX-3240: Added notice message in edit section

features/standard/Languages.feature
Adjusting tests for https://github.com/ibexa/core/pull/281
=> [Behat] Adjusted error message for duplicated language code

src/bundle/Resources/public/scss/_tables.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6635
=> IBX-6635: Empty product list is not adapted to low resolution screens

src/bundle/Resources/public/scss/_custom.scss
| Tickets       | https://issues.ibexa.co/browse/IBX-6377
=> IBX-6377: Wrong table color in RTE in content preview

src/lib/Behat/Component/Notification.php
This should hopefully help with https://issues.ibexa.co/browse/IBX-6743
There are two things here:
1) The assertion is replaced with a Wait condition (we will be waiting until the element is visible, not checking if it's visible as soon as it found)
2) the timeouts are increased to 30 seconds (mirroring https://github.com/ibexa/behat/pull/89)
=> [Behat] Replaced assertion with Wait condition

src/lib/Behat/Component/SubItemsList.php
https://github.com/ibexa/experience/actions/runs/6526653543/job/17720634676
```
Scenario: Create a new Landing Page and use Publish Later     # vendor/ibexa/scheduler/features/PublishInTheFuture.feature:19
Given I'm on Content view Page for root                     # Ibexa\AdminUi\Behat\BrowserContext\NavigationContext::iMOnContentViewPageFor()
Ibexa\Behat\Browser\Exception\TimeoutException: Element with CSS locator 'spinner': '.m-sub-items__spinner-wrapper' was found, but it should not exist. Timeout value: 5 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:59
```
I believe increasing the timeout will make this failure go away 🤞
=> [Behat] Increased timeout for subitems loading

src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6718
This PR does three things:
1. Adds scroll to items list (fix to bug reported in issue)
2. Moves items list above dropdown if lacking space below (< 150px)
3. recalculates items list position live on scroll site
=> IBX-6718: Missing scroll in language dropdown

src/lib/Behat/Component/Fields/RichText.php
Requires https://github.com/ibexa/behat/pull/90 to be merged first - the CI build will be green then
This should help with https://issues.ibexa.co/browse/IBX-6281 and https://issues.ibexa.co/browse/IBX-3097
"Emulate a focused page" is a cool trick that can be used when automating Richtext:
```
Now, the hidden elements will not disappear on the page and you would be able to inspect the elements on the web application.
```
This makes working with Richtext much easier.
Tested in:
https://github.com/ibexa/experience/pull/251
https://github.com/ibexa/commerce/pull/421
=> [Behat] Emulate a focused page when interacting with Richtext

features/standard/ContentManagement.feature, features/standard/Trash.feature
As you can see on the screenshot in https://github.com/ibexa/admin-ui/actions/runs/6534801187/job/17742837238 :
We're creating too many `ContentManagement` and `TrashTest` folders.
Using the `Given a "folder" Content item named "X" exists in root` step allows us to create it only once.
=> [Behat] Removed duplicated folders

phpstan-baseline.neon
Updated PHPStan's baseline to fix CI failure due to upstream changes removing one of the errors.
=> Regenerated PHPStan's baseline due to upstream changes

src/bundle/Resources/translations/ibexa_menu.en.xliff, src/lib/Menu/UserMenuBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6729
=> IBX-6729: Drafts should be removed from user menu

src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js, src/bundle/Resources/public/scss/_extra-actions.scss, src/bundle/Resources/translations/locationview.en.xliff, src/bundle/Resources/translations/universal_discovery_widget.en.xliff, src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig, src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-button/content.create.button.js, src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js, src/lib/Behat/Component/ContentTypePicker.php, src/lib/Behat/Page/ContentViewPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6597
| Tests pass?   | ?
=> IBX-6597: Content type pickers are inconsistent

src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
`class` is already passed to `@ibexadesign/ui/component/dropdown/dropdown.html.twig` in line 19.
=> Removed duplicated class key in drowdown_widget.html.twig

features/standard/Autosave.feature, src/bundle/Resources/public/js/scripts/admin.content.edit.js, src/bundle/Resources/public/scss/_autosave.scss, src/bundle/Resources/public/scss/_context-menu.scss, src/bundle/Resources/public/scss/_edit-header.scss, src/bundle/Resources/translations/ibexa_content.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig, src/bundle/Resources/views/themes/admin/ui/component/autosave/autosave.html.twig, src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig, src/lib/Behat/BrowserContext/ContentUpdateContext.php, src/lib/Behat/Page/ContentUpdateItemPage.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6725
=> IBX-6725: Autosave notification is in wrong place

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6883
`[data-original-title]` is used to store original `title` parameter, as after initializing tooltips BS takes control over `title` parameter and I want to have reliable way of retrieving og value ("If you want something done right, do it yourself")
`initializeTooltip` method is almost the same code as before (minus disposing tooltip instance)  just moved to new function
`hasEllipsisStyle` checks for ellipsis style - if there's no such style, tooltip should be always visible. Otherwise, it should be …
=> IBX-6883: [PB] Add tooltips for all buttons in header

src/bundle/Resources/public/js/scripts/admin.location.view.js, src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
| Tickets       | [IBX-6004](https://issues.ibexa.co/browse/IBX-6004)
| Doc needed?   |no
=> Adding condition to display sorting options

src/bundle/Resources/public/js/scripts/admin.table.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6993
=> IBX-6993: [Fieldtype Matrix] After adding field, "select all checkbox" in table does not work

src/lib/Behat/Component/Fields/RichText.php
This PR changes how the buttons are clicked - from hardcoded positions we switch to clicking by text.
Regression run: https://github.com/ibexa/experience/pull/265
=> [Behat] Removed hardcoded button positions

src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6998
=> IBX-6998: First table row has white background

src/bundle/Resources/public/scss/_filters.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_filters.scss, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/bundle/ui-dev/src/modules/universal-discovery/components/collapsible/collapsible.js, src/bundle/ui-dev/src/modules/universal-discovery/components/content-type-selector/content.type.selector.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6955
=> IBX-6955: Filters in global search are misaligned for long content type name

src/lib/Behat/Component/Fields/Country.php
```
Examples:
| label1 | value1  | label2 | value2 | label3 | value3 | oldContentItemName | newContentItemName |
| value  | Albania |        |        |        |        | Angola             | Albania            |
Failed step: And I set content fields
Ibexa\Behat\Browser\Exception\TimeoutException: CSS selector 'dropdownExpanded': '.ibexa-dropdown-popover .ibexa-dropdown__items' not found in 1 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79
```
https://github.com/ibexa/commerce/actions/runs/6790838955/job/18461314383
I'm not sure if this helps, but this page should use the dedicated Dropdown component anyway - so this is a step in the right direction.
=> [Behat] Country field: switch to using Ibexa dropdown

src/bundle/ui-dev/src/modules/common/popup/popup.component.js, src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js, src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | [IBX-6547](https://issues.ibexa.co/browse/IBX-6547)
IBX-6547: Updated Popup modal
=> IBX-6547: Updated Popup modal

phpstan-baseline.neon, src/contracts/Tab/AbstractControllerBasedTab.php, src/contracts/Tab/AbstractEventDispatchingTab.php, src/contracts/Tab/AbstractRouteBasedTab.php, src/contracts/Tab/AbstractTab.php, src/contracts/Tab/ConditionalTabInterface.php, src/contracts/Tab/OrderedTabInterface.php, src/contracts/Tab/TabInterface.php
Improved phpdoc in `Ibexa\Contracts\AdminUi\Tab` namespace:
* Removed redundant phpdocs
* Fixed typos
* Added mode specific `$parameters` type
=> Improved Tab API phpdoc

src/bundle/Resources/views/themes/admin/content/edit_base.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig, src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6612
=> IBX-6612: [Customer] JS exception occurs while user navigate on content action menu

composer.json
During the installation of the search package, the last stable version was installed (v4.6.0-beta2) instead of dev-main. A problem occurred during running tests in the PC package. https://github.com/ibexa/product-catalog/actions/runs/6927580604/job/18841713339?pr=1081
=> Fixed search package dependency to allow installation of the latest version

src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
| Tickets       | [IBX-6950](https://issues.ibexa.co/browse/IBX-6950) 
=> IBX-6950: Added style for invalid fields

src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js, src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| Tickets       | https://issues.ibexa.co/browse/IBX-6907
=> IBX-6907: Image picker: Translations filter

phpstan-baseline.neon, src/bundle/Resources/translations/ibexa_locationview.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/content/tab/authors.html.twig, src/bundle/Resources/views/themes/admin/content/tab/details.html.twig, src/lib/Tab/LocationView/AuthorsTab.php, src/lib/Tab/LocationView/ContentTab.php, src/lib/Tab/LocationView/DetailsTab.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6839
This PR adds new Authors tab.
=> IBX-6839: [Smart mode] As the User I want to view Authors tab with only selected data

src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js
| Tickets       | [IBX-6413](https://issues.ibexa.co/browse/IBX-6413)
`ibexa.site_access.config.<scope>.search.suggestion.min_query_length: 3` should mean that suggestion start to be made for a 3 character long text.
- With `<=` it was starting at 4 characters.
- With `<` it starts at 3.
=> IBX-6413: Fixes minQueryLength test to stick to parameter's meaning

src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/public/scss/_grid-view-item.scss, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7086
=> IBX-7086: Widget to change site context

phpstan-baseline.neon, src/bundle/Controller/UniversalDiscoveryController.php, src/bundle/ControllerArgumentResolver/UniversalDiscoveryRequestQueryArgumentResolver.php, src/bundle/Resources/config/routing.yaml, src/bundle/Resources/config/routing_rest.yaml, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/controller_argument_resolvers.yaml, src/bundle/Resources/config/services/controllers.yaml, src/bundle/Resources/config/services/rest.yaml, src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js, src/contracts/UniversalDiscovery/Provider.php, src/lib/Exception/ValidationFailedException.php, src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/AbstractLocationDataVisitor.php, src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/AccordionDataVisitor.php, src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationDataVisitor.php, src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationListDataVisitor.php, src/lib/REST/Value/UniversalDiscovery/AccordionData.php, src/lib/REST/Value/UniversalDiscovery/LocationData.php, src/lib/REST/Value/UniversalDiscovery/LocationListData.php, src/lib/REST/Value/UniversalDiscovery/RequestQuery.php, src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php, src/lib/Validator/Builder/REST/UniversalDiscoveryRequestValidatorBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6957
=> IBX-6957: Moved UDW endpoints to REST API

features/standard/Bookmark.feature, features/standard/SearchContent.feature
The tests using Cotf cannot be run on Ibexa Experience and Commerce editions - removing the tags should be enough
We will bring them back once "Create content" action is added by default in the Dashboard
=> [Behat] Disabled COTF tests on Experience and Commerce editions

phpstan-baseline.neon, src/bundle/Controller/ContentController.php, src/bundle/Resources/config/routing.yaml, src/bundle/Resources/translations/ibexa_menu.en.xliff, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php, src/lib/REST/Value/ContentTree/Node.php, src/lib/UI/Module/ContentTree/NodeFactory.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7051
Related PRs:
- https://github.com/ibexa/content-tree/pull/52
- https://github.com/ibexa/site-context/pull/4
=> IBX-7051: Preview button with siteaccess

features/personas/SubtreeEditor.feature
This commit was part of https://github.com/ibexa/admin-ui/pull/995 (https://github.com/ibexa/admin-ui/commit/450e330262b0795b5c1712a5ccf7ed4016143a19) , but then it got lost during the rebase process
There is a bug in context menu in AdminUI - reported as https://issues.ibexa.co/browse/IBX-7153
We will need to enable this tests (or adjust them) once it's fixed.
=> [Behat] Disabled tests checking status of button hidden in the Context menu

src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig, src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig, src/bundle/Resources/views/themes/admin/ui/tab/default.html.twig
This is a workaround to the issue that causes `runtime.js` to be applied on all ESI fragments.
Requires: https://github.com/ibexa/dashboard/pull/45
=> IBX-7147: Fixed issue where multiple Encore entries are applied to ESI fragments

src/bundle/Controller/ContentController.php, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig, src/lib/Menu/ContentRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7159
Related PRs:
- https://github.com/ibexa/content-tree/pull/54
- https://github.com/ibexa/site-context/pull/10
=> IBX-7159: Fix preview back button 500

src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js, src/bundle/Resources/public/scss/_empty-chart.scss, src/bundle/Resources/public/scss/ibexa.scss, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig, src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig, src/bundle/Resources/views/themes/admin/ui/empty_chart.html.twig
| Tickets       | [IBX-7163](https://issues.ibexa.co/browse/IBX-7163)
Remove Bootstrap classes
=> IBX-7163: Remove Bootstrap classes, change trigger for bootstrap btns to hover

src/bundle/Resources/config/bazinga_js_translation.yaml, src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/translations/ibexa_dropdown.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7173
Change started as thing for site access widget, but at the end done to all dropdowns in whole system...
=> IBX-7173: As the user I want to see empty state message in dropdown while filtering

phpstan-baseline.neon, src/bundle/Resources/translations/ibexa_content_create.en.xliff, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/lib/EventListener/ContentTypeSuggestionsListener.php, src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php, src/lib/Form/Type/Content/Draft/ContentCreateType.php, src/lib/Form/Type/ContentType/ContentTypeChoiceType.php, src/lib/Form/Type/Event/ContentCreateContentTypeChoiceLoaderEvent.php, tests/lib/EventListener/ContentTypeSuggestionsListenerTest.php
| Tickets       | [https://issues.ibexa.co/browse/IBX-6566](https://issues.ibexa.co/browse/IBX-6566)
It's very common to have items of the same or very limited number of types inside single container. For example:
| Location        | Content Type |
|-----------------|--------------|
| `/Media/Images` | Images       |
| `/Media/Files`  | File         |
| `/Forms`        | Form         |
| `/Users`        | User Group   |
| `/Users/**/`    | User         |
This PR adds content type suggestions to content creation form 
and reduce time needed to finding …
=> IBX-6566: As a Editor I'd like to get content type suggestions while creating content in given location

src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7258
=> IBX-7258: add getContentTypeDataByHref helper

src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7252
=> IBX-7252: Add react dropdown disabled state

src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
| Tickets       | IBX-6728
1) Fixed reference to undefined saveAndClose propety
2) Added missing ULR parameter
=> IBX-6728: Fixed sidebar menu in URL editing form

src/lib/Tab/Dashboard/MyDraftsTab.php, tests/lib/Tab/Dashboard/MyDraftsTabTest.php
| Question                 | Answer                                              |
|--------------------------|-----------------------------------------------------|
| **JIRA issue**           | [IBX-7126](https://issues.ibexa.co/browse/IBX-7126) |
| **Required by** | ibexa/dashboard#53
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.6`             |
| **BC breaks**            | no                                              |
When "My Drafts" Dashboard tab is rendered as a Customizable Dashboard Builder block, neither original request route name nor pagination parameter is available in a current context.
Parameters, in the end, after a few iterations, were seamlessly copied from main request to the block-rendering request via …
=> IBX-7126: Allowed passing extra parameters to pager of "My Drafts" tab

phpstan-baseline.neon, src/bundle/Controller/LocationController.php, src/bundle/Resources/translations/ibexa_location.en.xliff
| Tickets       | IBX-7055
| Needs         | https://github.com/ibexa/dashboard/pull/54/files
A different approach was merged but it is still worth to merge it. It removes an unused method and reduces the number of phpstan errors. 
~When the Exception is thrown and the content item is not sent to Trash then a proper flash message should be displayed~
=> IBX-7055: Removed unused method

src/lib/FieldType/Mapper/ImageFormMapper.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6937
| Related to   | https://github.com/ibexa/core/pull/291
This PR changes form type field `maxSize` from Integer to Number that allows to use float values for max file size setting.
=> IBX-6937: Used NumberType field to set max image size in ImageFormMapper

src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js, src/bundle/Resources/public/js/scripts/helpers/system.helper.js, src/bundle/Resources/public/scss/_global-search.scss, src/bundle/Resources/translations/ibexa_search.en.xliff, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7158
=> IBX-7158: As an Editor, I'd like to have shortcut for search focus

src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
| Tickets       | [IBX-7246](https://issues.ibexa.co/browse/IBX-7246)
Burger menu duplicated for tabs without children
=> IBX-7246: Burger menu duplicated for tabs without children

src/lib/Behat/Page/ContentUpdateItemPage.php
This is a quick fix and something that we should investigate in a more convienent time.
https://github.com/ibexa/commerce/actions/runs/7160506519/job/19495050988
```
And I set content fields                                    # Ibexa\AdminUi\Behat\BrowserContext\ContentUpdateContext::iSetFields()
| label       | value          |
| Identifier  | TagIdentifier  |
| Name        | TagName        |
| Description | TagDescription |
Ibexa\Behat\Browser\Exception\TimeoutException: CSS selector 'formElement': 'form.ibexa-form, .ibexa-edit-content' not found in 10 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79
Stack trace:
#0 vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php(105): Ibexa\Behat\Browser\Element\BaseElement->waitUntil()
#1 …
```
=> [Behat] Increased the timeout for opening Content update Page

src/lib/Behat/Component/UniversalDiscoveryWidget.php
Example failure: https://github.com/ibexa/headless/actions/runs/7153741371/job/19480535119
```
And I search for content item "folderUDW" through UDW       # Ibexa\AdminUi\Behat\BrowserContext\UDWContext::searchForContentItem()
Ibexa\Behat\Browser\Exception\TimeoutException: CSS selector 'inputField': '.c-top-menu-search-input__search-input' not found in 1 seconds. in vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php:79
Stack trace:
#0 vendor/ibexa/behat/src/lib/Browser/Element/BaseElement.php(105): Ibexa\Behat\Browser\Element\BaseElement->waitUntil()
#1 vendor/ibexa/admin-ui/src/lib/Behat/Component/UniversalDiscoveryWidget.php(174): Ibexa\Behat\Browser\Element\BaseElement->find()
#2 vendor/ibexa/admin-ui/src/lib/Behat/BrowserContext/UDWContext.php(114): …
```
=> [Behat] Increased timeout for UDW searching

phpstan-baseline.neon, src/bundle/Resources/config/services/fieldtype_form_mappers.yaml, src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js, src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js, src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js, src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js, src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js, src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss, src/bundle/Resources/translations/ibexa_content_forms_content.en.xliff, src/bundle/Resources/translations/ibexa_content_type.en.xliff, src/bundle/Resources/translations/validators.en.xliff, src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig, src/bundle/Resources/views/themes/admin/ui/layout.html.twig, src/lib/FieldType/Mapper/ImageFormMapper.php
| Tickets       | https://issues.ibexa.co/browse/IBX-6856
https://github.com/ibexa/core/pull/300
https://github.com/ibexa/content-forms/pull/55
https://github.com/ibexa/image-editor/pull/80
=> IBX-6856: Added mimeTypes field to ImageFormMapper

phpstan-baseline.neon, src/bundle/Resources/public/scss/_alerts.scss
| Tickets       | [IBX-7059](https://issues.ibexa.co/browse/IBX-7059)
The issue also occurs on 4.5, so I created a PR from 4.5
=> IBX-7059: Added align-items for icon-wrapper

src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js, src/bundle/Resources/public/js/scripts/fieldType/ezimage.js, src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
https://issues.ibexa.co/browse/IBX-7401
=> IBX-7401: Fixed input file type validation for image asset field

src/lib/Behat/Component/UniversalDiscoveryWidget.php
Backport of https://github.com/ibexa/admin-ui/pull/1041 to 4.5
Failure on 4.5: https://github.com/ibexa/oss/actions/runs/7201439313/job/19617561554
=> [Behat] Increased timeout for UDW searching (#1041)

src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
| Tickets       | [IBX-7294](https://issues.ibexa.co/browse/IBX-7294)
Similar issue in the Product catalog: https://github.com/ibexa/product-catalog/pull/1109
=> IBX-7294: Gracefully handle missing user's thumbnail image

src/bundle/Resources/translations/ibexa_admin_ui.en.xliff, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7410
According to figma project label should be always "Focus mode"
=> IBX-7410: Aligned focus mode switcher with design

src/bundle/ui-dev/src/modules/common/popup/popup.component.js
| Tickets       | [iBX-7167](https://issues.ibexa.co/browse/IBX-7167)
Added tooltip option to popup
=> IBX-7167: Added tooltip option to popup

src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig, src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7029
Before:
After:
=> IBX-7029: Fixed invalid content type icon when creating Content with Content On The Fly

src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/bundle/Resources/translations/messages.en.xliff, src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
| Tickets       |  [IBX-7037](https://issues.ibexa.co/browse/IBX-7037) 
=> IBX-7037: Added check if user has permission to change password

features/personas/ChangePassword.feature, src/lib/Behat/Page/UserSettingsPage.php
Adapting tests to the changes from https://github.com/ibexa/user/pull/66
The User Settings page covers two use cases right now: viewing user settings and editing them
The `verifyIsLoaded` method was written only for the editing use case, I had to adapt it so that it makes sense in the view mode as well.
=> [Behat] Adapted tests after redirect change

src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss, src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js, src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| Tickets       | https://issues.ibexa.co/browse/IBX-7184
=> IBX-7184: [Sub-items] For lower resolution list header actions ale not fully visible

src/lib/Event/FilterContentTypesEvent.php, src/lib/UI/Config/Provider/ContentTypes.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7299
This will be utilized in the dashboard package (https://github.com/ibexa/dashboard/pull/77). The dashboard group will be removed from the list of available content types.
=> IBX-7299: Added event emission to allow modification of content type list

src/bundle/Resources/translations/ibexa_locationview.en.xliff, src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/lib/Behat/Page/ContentViewPage.php, src/lib/Tab/LocationView/DetailsTab.php, src/lib/UserSetting/FocusMode.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7109
Changed "Technical Details" to "Technical details".
=> IBX-6680: Fixed capitalization in location view tabs

src/lib/EventListener/UserPasswordChangeRightSidebarListener.php, src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7489
=> IBX-7489: Fix user settings password change Discard button link

features/personas/ChangePassword.feature, features/standard/Autosave.feature, src/bundle/Resources/translations/ibexa_menu.en.xliff, src/lib/EventListener/UserPasswordChangeRightSidebarListener.php, src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php, src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7124
=> IBX-7124: Aligned confirmation/discard action labels in User settings with design

src/lib/Behat/Component/UpperMenu.php, src/lib/Behat/Page/ContentViewPage.php, src/lib/Tab/LocationView/AuthorsTab.php, src/lib/Tab/LocationView/DetailsTab.php, tests/lib/Tab/LocationView/AuthorsTabVisibilityTest.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7357
=> IBX-7357: Adjusted Authors & Details tabs to modes specification

src/bundle/Resources/public/scss/_add-translation.scss, src/bundle/Resources/views/themes/admin/content/modal/add_translation.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6262
Added `form-content-add-translation-body component` group and adjusted CSS
=> IBX-6262: Added extension point to allow rendering additional fields in content translation form

src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js, src/bundle/Resources/public/scss/_global-search.scss, src/bundle/Resources/translations/ibexa_search.en.xliff, src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-7420
Requires: https://github.com/ibexa/search/pull/38
=> IBX-7420: Added total number of results to autocomplete

src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/lib/UI/Config/Provider/Module/ImagePicker.php, tests/lib/UI/Config/Provider/Module/ImagePickerTest.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7367
Ref: https://github.com/ibexa/core/blob/main/data/mysql/cleandata.sql#L50
This is required by image picker to be able to run UDW with correct settings and search by correct field definition and content type identifier.
Currently values for field definition and KeywordTermAggregation are hardcoded.
https://github.com/ibexa/image-picker/blob/main/src/bundle/ui-dev/src/modules/image-picker/components/items-view/items.view.js#L198-L202
https://github.com/ibexa/admin-ui/blob/main/src/bundle/ui-dev/src/module …
=> IBX-7367: Added config provider for image picker

src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7148|
=> IBX-7505: Fix unnecessary +0 text in React dropdown

src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
| Tickets       | https://issues.ibexa.co/browse/IBX-6679
=> IBX-6679: Disabled delete action in field definition form when translating content type

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| Tickets       | [IBX-7182](https://issues.ibexa.co/browse/IBX-7182)
Implemented autoopen on init page for extra actions
=> IBX-7182: Implemented autoopen on init page for extra actions

src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig, src/lib/UserSetting/FocusMode.php
| Tickets       | [IBX-7352](https://issues.ibexa.co/browse/IBX-7352)
Aligned focus mode labels in user settings with design. See JIRA issue for more details.
=> IBX-7352: Aligned focus mode labels in user settings with design

phpstan-baseline.neon, src/bundle/Controller/User/FocusModeController.php, src/contracts/Event/FocusModeChangedEvent.php
| **JIRA issue**       | [IBX-7450](https://issues.ibexa.co/browse/IBX-7450) |
Dispatched `\Ibexa\Contracts\AdminUi\Event\FocusModeChangedEvent` when focus mode changed its state.
=> IBX-7450: Dispatched event when focus mode changed its state

src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js, src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| **JIRA issue**       |https://issues.ibexa.co/browse/IBX-7290|
=> IBX-7290: Add abort controller to useSearchByQueryFetch

src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
| **JIRA issue**       | [IBX-7448](https://issues.ibexa.co/browse/IBX-7448) |
`map` takes parameters in other order, it was changed from `for` loop during redesign so it is fine for 3.3.
(for 4.6, I had created https://github.com/ibexa/admin-ui/pull/1075 as a fix for other bug tho.)
It was working fine for most …
=> IBX-7448: Fixed siteaccess dropdown values

src/lib/EventListener/UserProfileListener.php
| **JIRA issue**       | [IBX-7563](https://issues.ibexa.co/browse/IBX-7563) |
With   
```
user_profile:
enabled: true 
```
or  currently user content type not being in enabled user profile content types, when self editing user, after saving you are unsuccessfully redirected to profile view even when it is not …
=> IBX-7563: Redirect only if user profile is enabled

src/bundle/Resources/public/scss/_header-user-menu.scss
| **JIRA issue**       | [IBX-7595](https://issues.ibexa.co/browse/IBX-7595) |
Removed styles for `:focus` state for `.ibexa-header-user-menu`
=> IBX-7595: Removed :focus styles for ibexa-header-user-menu

src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
| **JIRA issue**       | [IBX-7656](https://issues.ibexa.co/browse/IBX-7656) |
Quick action now will work with `hashes` instead of query parameters. Used by https://github.com/ibexa/dashboard/pull/100
=> IBX-7656: Changed quick action to work with fragment

src/bundle/Resources/config/services/events.yaml, src/lib/EventListener/UserProfileListener.php
| **JIRA issue**       | [IBX-7674](https://issues.ibexa.co/browse/IBX-7674) |
It seems that if `User` (besides default `Editor`) CT was enabled to have "User profile" feature, the redirection was a bit imprecise. `UserProfileListener` now detects if it was triggered from dedicated view. Therefore. if "User" CT …
=> IBX-7674: Skip redirection to user profile if user CT is edited via configuration view

src/bundle/Controller/ContentController.php, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig, src/lib/Form/Type/ChoiceList/Loader/SiteAccessPreviewChoiceLoader.php, src/lib/Form/Type/Preview/SiteAccessChoiceType.php
| Tickets       | https://issues.ibexa.co/browse/IBX-7278
This adds sort of extension point to modify list of available siteaccesses like done in:
https://github.com/ibexa/corporate-account/pull/227
This needs some frontend love, hence work in progress.
=> IBX-7278: Changed HTML form to symfony one

src/lib/Form/Type/ChoiceList/Loader/SiteAccessPreviewChoiceLoader.php
| **JIRA issue**       | [IBX-7448](https://issues.ibexa.co/browse/IBX-7448) |
As in first place this was build upon bug in twig form, I made that same mistake as there :sweat_smile:
=> IBX-7448: Fixed wrong used of name instead of identifier for siteaccess form dropdown value

src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/lib/UI/Config/Provider/Module/DamWidget.php, tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| **JIRA issue**       | N/A |
Renamed `ImagePicker` to `DamWidget` and also renamed all related parameters containing `image_picker` to `dam_widget` in name.
There is also added `image` phrase in parameter name to distinguish for which DAM widget part configuration belongs to.
=> Renamed ImagePicker config provider to DamWidget

src/bundle/Resources/public/js/scripts/core/dropdown.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7606 |
=> IBX-7606: [Site context] Site dropdown changes width after entering a search term

.gitignore, composer.json, phpstan-baseline.neon, phpunit.integration.xml, src/lib/UI/Module/ContentTree/NodeFactory.php, tests/integration/AdminUiIbexaTestKernel.php, tests/integration/REST/BaseAdminUiRestWebTestCase.php, tests/integration/REST/PostPostLoadSubtreeTest.php, tests/integration/Resources/REST/InputPayloads/ContentTreeLoadSubtreeRequest.json, tests/integration/Resources/REST/Schemas/ContentTreeRoot.json, tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json, tests/integration/Resources/ibexa_test_config.yaml, tests/integration/Resources/routing.yaml, tests/integration/SetupValidationTest.php, tests/integration/bootstrap.php
| Question                 | Answer                                              |
|--------------------------|-----------------------------------------------------|
| **JIRA issue**           | [IBX-6815](https://issues.ibexa.co/browse/IBX-6815) |
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.5`              |
| **BC breaks**            | no                                              |
A [merge up](https://github.com/ibexa/admin-ui/pull/856/files#diff-f65a7556df790de631de3760e0ceff5e35c69ad0185bfd7c23092a2823b7fa54L100) caused the regression which resulted in Location bookmark information not being propagated when building ContentTree REST response (`/load-subtree` endpoint).
We need some minimal test coverage for that endpoint, as the …
=> IBX-6815: [REST] Fixed isBookmarked property in load-subtree response

.gitignore, composer.json, phpstan-baseline.neon, phpunit.integration.xml, src/lib/UI/Module/ContentTree/NodeFactory.php, tests/integration/AdminUiIbexaTestKernel.php, tests/integration/REST/BaseAdminUiRestWebTestCase.php, tests/integration/REST/PostPostLoadSubtreeTest.php, tests/integration/Resources/REST/InputPayloads/ContentTreeLoadSubtreeRequest.json, tests/integration/Resources/REST/Schemas/ContentTreeRoot.json, tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json, tests/integration/Resources/ibexa_test_config.yaml, tests/integration/Resources/routing.yaml, tests/integration/SetupValidationTest.php, tests/integration/bootstrap.php, tests/lib/EventListener/ContentProxyCreateDraftListenerTest.php, tests/lib/Tab/LocationView/VersionsTabVisibilityTest.php
> [!WARNING]
> This is a merge up, so needs to be merged in a fast forward way (pushed)
This is a technical PR to test merge up of #1139 as there are many conflicts around newly introduced integration test setup.
Additionally we have 2 outstanding issues in current unit tests on `main`, fixed as separate commits:
```
There were 2 warnings:
1) Ibexa\Tests\AdminUi\EventListener\ContentProxyCreateDraftListenerTest::testAutosaveDisabled
Class "Ibexa\AdminUi\Event\Options" is declared "final" and cannot be mocked.
2) Warning
The data provider specified for Ibexa\Tests\AdminUi\Tab\LocationView\VersionsTabVisibilityTest::testTabVisibilityInGivenUserMode is invalid.
Error: Typed property Ibexa\Tests\AdminUi\Tab\LocationView\VersionsTabVisibilityTest::$exampleContent must not be accessed before …
```
=> [Fast forward] Merged branch '4.5' into main

src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| **JIRA issue**       | [IBX-7667](https://issues.ibexa.co/browse/IBX-7667) |
| **Related PR**            | https://github.com/ibexa/image-picker/pull/44                                      |
Adds support for using `ContentNameCriterion` in search query.
=> IBX-7667: Added support for search by ContentNameCriterion

src/lib/Menu/MainMenuBuilder.php
| **JIRA issue**       | [IBX-7365](https://issues.ibexa.co/browse/IBX-7365) |
=> IBX-7365: Changed order of admin menu items

src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
| **JIRA issue**       | [IBX-7472](https://issues.ibexa.co/browse/IBX-7472) |
There is no easy way to retain uploaded image between this and validation, but this at least ~clears up form (ok, not clearing form as this is also not so easy to do, seems errors came from other field)~ change view so user knows that …
=> IBX-7472: Set view to empty file, when uri value is empty

src/bundle/Resources/views/themes/admin/account/profile/view.html.twig
| **JIRA issue**       | [IBX-7731](https://issues.ibexa.co/browse/IBX-7731) |
Do not display container on empty user profile component.
=> IBX-7731: Prevented container element display on empty user profile

src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/views/themes/admin/content/tab/details.html.twig, src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7773 |
After alignment:
Also fix for:
=> IBX-7773: Fix Sub-items sorting order form vertical alignment

src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7677 |
=> IBX-7677: Remove markedLocationId reset to null from useSearchByQueryFetch

src/bundle/Resources/config/universal_discovery_widget.yaml
| **JIRA issue**       | [IBX-7655](https://issues.ibexa.co/browse/IBX-7655) |
After discussion with @IdaDra, Image library should show Content Tree starting from Media folder. Currently starting location id is 1.
=> IBX-7655: Added root and starting location id for richtext embeded image UDW config

src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
| **JIRA issue**       | [IBX-7720](https://issues.ibexa.co/browse/IBX-7720) |
Fixed conent-type not highlighter in COTF
=> IBX-7720: Fixed content-type not highlighted in COTF

src/bundle/Resources/translations/ibexa_user_settings.en.xliff, src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig, src/lib/Behat/Page/UserSettingsPage.php, src/lib/UserSetting/Autosave.php, src/lib/UserSetting/InContextTranslation.php
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7637 |
=> IBX-7637: [User settings] Enabled/Disabled labels should be in upper case

src/bundle/Resources/public/js/scripts/admin.location.tab.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7690 |
Thanks to this solution when we enter link like `http://localhost:8000/admin/view/content/52/full/1/2#ibexa-tab-location-view-preview` we are redirected to proper tab, but we're not scrolled to element with id `#ibexa-tab-location-view-preview` …
=> IBX-7690: [Full view] Exit full view should redirect user to View tab, not Fields

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss, src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff, src/bundle/ui-dev/src/modules/universal-discovery/browse.tab.module.js, src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7209 |
=> IBX-7209: Clear results button in UDW Search

src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js, src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7825|
=> IBX-7825: UDW Blank browse tab after going from bookmarks from search

src/bundle/Resources/public/js/scripts/admin.context.menu.js, src/bundle/Resources/views/themes/admin/ui/menu/context_menu.html.twig
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-6877|
=> IBX-6877: Fix multilevel popup menu in context menu's "more items" menu

src/bundle/Resources/public/js/scripts/core/doughnut.chart.js
| **JIRA issue**       | [IBX-7574](https://issues.ibexa.co/browse/IBX-7574) |
| **Required** |  https://github.com/ibexa/order-management/pull/111 |
| **Required** |   |
What is done:
1. Moved logic from packages: product catalog and order management to doughtnut chart.
2. Hidded datalabels label in doughnut …
=> IBX-7574: Hidded label in doughnut chart when unchecked

src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
| **JIRA issue**       |  https://issues.ibexa.co/browse/IBX-7804 |
=> IBX-7804: Fix dropdown offsetHeight error when ibexa-main-header not present

src/bundle/Resources/public/scss/_mixins.scss, src/bundle/Resources/public/scss/mixins/_spinner.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-6905 |
Backporting spinner mixin for fieldtype-address fix
=> IBX-6905: Changing Country in Corporate Account form removes current data without any warning

src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.helpers.js, src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7030 |
For whole UDW markedLocationId is used as both item that is detailed in sidebar and parent of last/active branch. 
It changes however in grid view, where markedLocationId keeps data about details in sidebar, but it's not necessary parent of …
=> IBX-7030: [UDW] Inactive edit button in grid view

src/bundle/Resources/public/js/scripts/core/dropdown.js, src/bundle/Resources/public/js/scripts/helpers/text.helper.js
| **JIRA issue**       | [IBX-7442](https://issues.ibexa.co/browse/IBX-7442) |
|**Required by** | https://github.com/ibexa/product-catalog/pull/1139
=> IBX-7442: Escaped values in JS

composer.json, dependencies.json, src/bundle/Controller/Permission/LanguageLimitationController.php, src/lib/Permission/LimitationResolver.php
Fix issue IBX-7959
| **JIRA issue**       | [IBX-7959](https://issues.ibexa.co/browse/IBX-7959) |
=> IBX-7959: Create content permission regression with section limitation

src/bundle/Resources/public/js/scripts/core/dropdown.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7517 |
Dropdown is initialized (thefore - its fitItems method is run) before it's visible on screen. That causes that in calculation, dropdown width is 0 and condition to hide elements is always met.
=> IBX-7517: [Dashboard] Quick actions: selected tags aren't fully displayed

src/lib/Menu/Admin/ContentType/AbstractContentTypeRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php, src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
Fixes an error which occurred during the extraction of translations:
```
In TranslationContainerExtractor.php line 112:
call_user_func() expects parameter 1 to be a valid callback, cannot call abstract method Ibexa\AdminUi\Menu\Admin\ContentType\AbstractContentTypeRigh  
tSidebarBuilder::getTranslationMessages()  
```
=> Fixed extraction of translation

src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7926 |
By exceeding input we made data source div too big and header and input weren't able to fit into one column so it broke into two (in left there was header; in right, beyond screen there was data source), adding nowrap ensures it's always in one …
=> IBX-7926: [Distraction free mode] Black screen when user exceeds RTE field input in distraction free mode

src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js, src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js, src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js, src/bundle/ui-dev/src/modules/universal-discovery/helpers/locations.helper.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useLoadBookmarksFetch.js
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7901 |
Bookmarks are kept in other place than LoadedLocationsMapContext (which is modified after clicking "Remove from bookmarks", so bookmarks state has to be reload as well.
Bookmark children (BookmarksList and Browse) are rendered conditionally now …
=> IBX-7901: [UDW] Removing from bookmarks content is still visible on bookmark list

src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/lib/UI/Config/Provider/Module/DamWidget.php, tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| :ticket: Issue | [IBX-8089](https://issues.ibexa.co/browse/IBX-8089) |
This PR adds new configuration for image management allows to provide complex settings for different content types. In next steps we should be able to configure description and tags fields.
-  `contentTypeIdentifiers` and `fieldDefinitionIdentifiers` - now will be dynamically added, based on `mappings` parameter. Used in search criteria. 
- `nameSchemaIdentifiers` - same as for folder, name identifiers will be dynamically added as array of extracted field definition identifiers from nameSchema pattern. 
```yaml
ibexa.dam_widget.image.mappings:
<content_type_identifier>:
imageFieldIdentifier: <field_definition_identifier>
```
```json
"image": {
"showImageFilters": false,
"aggregations": …
```
=> IBX-8089: Added configuration for image management

src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/lib/UI/Config/Provider/Module/DamWidget.php, tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| :ticket: Issue | [IBX-7981](https://issues.ibexa.co/browse/IBX-7981) |
This PR provides improved folder configuration that returns array of field definition identifiers extracted from name schema. Previous solution with manually pointing field type identifier did not account case when name schema contains more than one field definition identifier. Now we will iterate through array of identifiers and edit first matched field.
Provided configuration for DamWidget should contains all field definition identifiers from name schema setting.
=> IBX-7981: Improved folder configuration

phpstan-baseline.neon
| **JIRA issue**       |N/A |
Fixes PHPStan due to incoming changes from https://github.com/ibexa/rest/pull/87
=> Fixed PHPStan

src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
| :ticket: Issue | [IBX-8011](https://issues.ibexa.co/browse/IBX-8011) |
- https://github.com/ibexa/content-tree/pull/75
=> IBX-8011: Refine bookmarking in Content Tree

src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
=> IBX-8075: User (group) re-selection not possible after failed role assignment

src/bundle/Controller/ContentTypeController.php
| :ticket: Issue | IBX-8059|
A simple validation of Content Type Group was added to avoid loading certain Content Types inside non-matching Content Type Groups.
=> IBX-8059: Validate Content Type's Group in the Content Type view action

src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
=> IBX-8188: Fix breadcrumbs hidden menu (not opening)

src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations.html.twig
=> IBX-8254: Added check if relation is accessible

src/bundle/Controller/NotificationController.php, src/bundle/DependencyInjection/Configuration/Parser/Notifications.php, src/bundle/Resources/config/ezplatform_default_settings.yaml, src/bundle/Resources/public/js/scripts/admin.notifications.modal.js, src/bundle/Resources/views/themes/admin/account/notifications/list.html.twig
| **JIRA issue**       | N/A |
(conversion of ezsystems/ezplatform-admin-ui#1396)
Get `getNotificationsStatusLoop` (`notifications/count`) interval from YAML config parameters.
One could want (or need) to increase this interval to reduce server activity.
Config doc could be added around …
=> Get getNotificationsStatusLoop interval from YAML config

phpstan-baseline.neon, src/bundle/Controller/Content/ContentTreeController.php, src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php, src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php, src/lib/UI/Module/ContentTree/NodeFactory.php
| **JIRA issue**       | https://issues.ibexa.co/browse/IBX-7653 |
=> IBX-7653: Allow filtering for loadSubtreeAction

src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js, src/bundle/Resources/public/js/scripts/fieldType/validator/richtext-validator.js, src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
| :ticket: Issue | IBX-8184|
- https://github.com/ibexa/page-builder/pull/373
In case an input is empty it should be handled accordingly instead of throwing an exception. Please, see the related PR as it improves validation in PB more.
Additionally reusable RichText validation was implemented.
=> IBX-8184: Implemented reusable RichText validator

src/bundle/Resources/public/scss/_main-container.scss
| **JIRA issue**       | [IBX-7542](https://issues.ibexa.co/browse/IBX-7542) |
| **Doc needed**       | no                                                    
Fixed notification element position under main-container-edit
=> IBX-7542: Fixed elements position under main-container-edit

src/bundle/Controller/ContentViewController.php, src/bundle/Resources/config/services/controllers.yaml
| :ticket: Issue | IBX-8140 |
The idea is to engage Symfony mechanisms to check permissions. Otherwise, we end-up in the BO-user-protected templates which cannot perform any operations on `null` user which is anonymous in the new Symfony security approach. 
Removal of the `Ibexa\Contracts\AdminUi\Controller\Controller` definition is done due to duplication, ref: https://github.com/ibexa/admin-ui/blob/main/src/bundle/Resources/config/services.yaml#L49.
- https://github.com/ibexa/core/pull/368
- https://github.com/ibexa/rest/pull/90
- https://github.com/ibexa/recipes-dev/pull/118
=> IBX-8140: Enabled authenticator manager-based security

src/lib/Event/AddContentTypeGroupToUIConfigEvent.php, src/lib/UI/Config/Provider/ContentTypes.php
| :ticket: Issue | IBX-8058|
- https://github.com/ibexa/dashboard/pull/122
A new event was added to allow adding additional content type groups to UI config event. 
The `getContentTypeData` method now allows to set `isHidden` parameter as well based on content type group's `system` property.
=> IBX-8058: Implemented subscriber that adds content type groups to `ContentTypes` UI config event

composer.json, src/bundle/Controller/DownloadImageController.php, src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/routing_rest.yaml, src/bundle/Resources/config/services/controllers.yaml, src/lib/UI/Config/Provider/Module/DamWidget.php, tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| :ticket: Issue | [IBX-8344](https://issues.ibexa.co/browse/IBX-8344) |
This PR adds new endpoint for download images used in Image picker. 
When downloading several images a zip archive is created with all images.
=> IBX-8344: Added endpoint for download images

src/lib/EventListener/InContextTranslationListener.php, src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php, src/lib/Siteaccess/SiteaccessResolver.php, src/lib/Strategy/ContentTypeThumbnailStrategy.php, src/lib/UI/Module/ContentTree/NodeFactory.php
| **JIRA issue**                          | [IBX-7911](https://issues.ibexa.co/browse/IBX-7911)
| **Requires** | ibexa/core#347, ibexa/user#76
| **Type**                                   | bug
| **Target Ibexa version** | `v4.6`
| **BC breaks**                          | no
This PR replaces usages of magic getters with strict ones introduced via ibexa/core#347. See the ibexa/core PR for the reasoning behind this change. The scope of the changes is limited to code paths executed when calling `ContentTreeController::loadSubreeAction` controller.
=> IBX-7911: Replaced usage of magic getters for load subtree code paths

src/bundle/Controller/Content/ContentTreeController.php, src/lib/Pagination/Mapper/AbstractPagerContentToDataMapper.php, src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php, src/lib/REST/Output/ValueObjectVisitor/ContentTree/NodeExtendedInfoVisitor.php, src/lib/REST/Value/ContentTree/Node.php, src/lib/REST/Value/ContentTree/NodeExtendedInfo.php, src/lib/UI/Module/ContentTree/NodeFactory.php, tests/integration/REST/GetContentTreeExtendedInfoTest.php, tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.json, tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.xsd, tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.json, tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.xml, tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json
| :ticket: Issue | IBX-8280, solves also IBX-7911 |
- https://github.com/ibexa/content-tree/pull/81
- https://github.com/ibexa/image-picker/pull/62
- https://github.com/ibexa/admin-ui/pull/1212
- https://github.com/ibexa/site-factory/pull/94
- https://github.com/ibexa/user/pull/76
- https://github.com/ibexa/core/pull/347
- https://github.com/ibexa/product-catalog/pull/1150
- https://github.com/ibexa/dashboard/pull/119
All PRs should be tested together, there will be a combo branch for 2 admin-ui PRs.
=> IBX-8280: Move previewableTranslations info to node extended info endpoint

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss, src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
| :ticket: Issue | https://issues.ibexa.co/browse/IBX-8195 |
Test case with loading more items (so > 50 items) thoroughly, I had some problems with it (infinite loading of items - after one batch was loaded, it tried to load next one (non-existing) by showing loader. After my fixes I couldn't reproduce these unnecessary loaders, so it should be fixed, but maybe there's still some corner case.
Also - this PR modifies solution from this issues https://issues.ibexa.co/browse/IBX-7839 as that one introduced IBX-8195 bug, so probably should be tested as well (checked that as well, looked that it works as well)
=> IBX-8195: Content items are displayed multiple times in UDW after adding item to bookmarks

src/bundle/DependencyInjection/Configuration/Parser/ContentTypeGroup.php, src/bundle/IbexaAdminUiBundle.php, src/bundle/Resources/config/default_parameters.yaml, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/ui_config/common.yaml, src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig, src/bundle/Templating/Twig/ContentTypeGroupIconExtension.php, src/bundle/Templating/Twig/ContentTypeIconExtension.php, src/lib/UI/Service/ContentTypeGroupIconResolver.php, src/lib/UI/Service/IconResolver.php
| :ticket: Issue | IBX-7808 |
- https://github.com/ibexa/icons/pull/43 - merged
- https://github.com/ibexa/admin-ui/pull/1230 - merged
- https://github.com/ibexa/dashboard/pull/121
- https://github.com/ibexa/corporate-account/pull/242
- https://github.com/ibexa/admin-ui/pull/1256
icons for all Content type groups should be added and used later in the Dashboard type to inform the user about the displayed element
=> IBX-7808: Added possibility to define icons for content type group

src/bundle/DependencyInjection/Compiler/ComponentPass.php
| Doc needed?   | yes?
This PR allows `Ibexa\AdminUi\Component\Renderer\DefaultRenderer::renderSingle` to be used without the knowledge of service ID, by allowing `ibexa.admin_ui.component` tag additional `id` property. This could be used to control the key that is put in the component group, making the following call possible:
```php
$this->renderer->renderSingle(
'<component_id>',
'<group_id>',
$parameters,
);
```
So the new service definition could be:
```diff
ibexa.adminui.content_type.tab_groups:
parent: Ibexa\AdminUi\Component\TabsComponent
arguments: …
```
=> Allowed overwriting component id using tag property for RendererInterface::renderSingle

src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_progress.bar.scss, src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
| :ticket: Issue | IBX-8163 |
Expanded place for uploaded files name (MFU)
=> IBX-8163: Upload modal files display too short file names

src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js, src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| :ticket: Issue | IBX-8392 |
- https://github.com/ibexa/image-picker/pull/66
Added support for sorting clauses in method `searchByQuery`
It is necessary to test DXP and standalone app (DAM)
=> IBX-8392: [Image picker] Sorting by name and date does not work

phpstan-baseline.neon, src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php, src/lib/UI/Config/Provider/Module/DamWidget.php, tests/lib/Siteaccess/AdminSiteaccessPreviewVoterTest.php, tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
| :ticket: Issue | IBX-8399  |
Fixed failing tests due to changed introduced in IBX-8399. For example: 
```
/home/runner/work/admin-ui/admin-ui/tests/lib/UI/Config/Provider/Module/DamWidgetTest.php:95
8) Ibexa\Tests\AdminUi\UI\Config\Provider\Module\DamWidgetTest::testGetConfigThrowInvalidSearchEngine
PHPUnit\Framework\MockObject\ClassIsFinalException: Class "Ibexa\Bundle\Core\ApiLoader\RepositoryConfigurationProvider" is declared "final" and cannot be doubled
```
N/A
N/A
=> IBX-8399: Moved RepositoryConfigurationProvider to Repository layer 

src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
| :ticket: Issue | IBX-8001 |
When the RoleAssignment form is created a checkbox is not selected, the select section filed is disabled and therefore not sent. There is no need to render a form with this field disabled
=> IBX-8001: Fixed section limitation

src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| :ticket: Issue | IBX-8424 |
- https://github.com/ibexa/image-picker/pull/68
It was necessary to getting fieldDefIdentifier value for ImageCriterion from the configuration and support for multiple fieldDefinitionIdentifiers
=> IBX-8424: Fixed criterions build for hook useSearchByQueryFetch

src/bundle/Controller/LocationController.php
| :ticket: Issue | IBX-8485|
It would be a better user experience if a redirect would point to a place from where adding location was done, not to a main location as it can be in a completely different subtree.
=> IBX-8485: Redirect after creating location should point to referer location

.github/workflows/browser-tests.yaml, features/personas/AddLocation.feature, features/personas/SubtreeEditor.feature, src/bundle/Resources/public/js/scripts/sidebar/main.menu.js, src/lib/Behat/BrowserContext/NavigationContext.php, src/lib/Behat/Component/LeftMenu.php
| **JIRA issue**       | [IBX-7558](https://issues.ibexa.co/browse/IBX-7558) |
Added posibiity to close navbar menu
=> IBX-7558: Added posibiity to close navbar menu

src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
| :ticket: Issue | IBX-8477 |
Only in twig it was checked whether the draft belonged to the user and based on this it turned off the edit button or not. anyone with permission to edit content can edit another user's draft (blocking this is a mechanism that is being implemented (or at least was))
=> IBX-8477: Removed check whether the draft belongs to the user

features/personas/AddLocation.feature, features/personas/SubtreeEditor.feature
| :ticket: Issue | IBX-8138 |
[- https://github.com/ibexa/core/pull/1](https://github.com/ibexa/behat/pull/118)
Because tests in https://github.com/ibexa/behat/pull/118 rely on admin-ui bundle, the shall be disabled before https://issues.ibexa.co/browse/IBX-8589 followup is done.
=> [Behat] Added broken tag to addLocation and subtreeEditor features

src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.item.component.js, src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js, src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js, src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
| :ticket: Issue | IBX-8588 |
Error occurs because we don’t have form for edit like in subitems. After discuss with UX/UI team we decided to remove edit button for image picker because we will implement edit in different way in https://issues.ibexa.co/browse/IBX-8110
=> IBX-8588: [Image Picker] Clicking edit button on multi-file upload modal causes an error

src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
| :ticket: Issue | N/A |
Fixed duplicated `ibexa-btn` class in field_definitions.html.twig
N/A
N/A
=> Fixed duplicated CSS class in field_definitions.html.twig

src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
| :ticket: Issue | IBX-7936 |
the `group_name` is created based on the translation of the group field and is used, among other things, to create classes. The change will remove not-allowed characters that can cause problems in the JS
=> IBX-7936: slugify group_name

src/bundle/Resources/public/js/scripts/core/date.time.picker.js
| :ticket: Issue | IBX-8554 |
This PR should be tested with https://github.com/ibexa/admin-ui/pull/1303
=> IBX-8554: Added checks if flatpickrDate and this.flatpickrConfig.minDate exists

src/bundle/Resources/public/js/scripts/core/date.time.picker.js
=> IBX-8527: [Hide later] Error in console when typing the time

phpstan-baseline-7.4.neon, phpstan-baseline-8.0.neon, phpstan-baseline.neon, src/bundle/Controller/Content/ContentTreeController.php
| :ticket: Issue | IBX-8602|
The issue stems from the fact that we are loading the location of ID = `1`. If a user has some limitations on locations or subtrees, even if he selected all of them he won't be able to load the root location of ID = `1`. Another limitation is that we cannot select the root location in limitations.
The following PR proposes to always load the root location using `sudo` and the rest of them using a standard call with policies validation. 
If we won't go with this solution we have probably one option and that is to load multiple tree roots in the frontend simultaneously, it probably requires a lot of work.
=> IBX-8602: Always load root location using `sudo` in the `ContentTreeController`

.github/workflows/browser-tests.yaml, behat_suites.yml, features/standard/UserProfile.feature, src/bundle/Resources/config/services/test/feature_contexts.yaml, src/bundle/Resources/config/services/test/pages.yaml, src/lib/Behat/BrowserContext/NavigationContext.php, src/lib/Behat/BrowserContext/UserProfileContext.php, src/lib/Behat/Page/UserProfilePage.php
| :ticket: Issue | IBX-8638 |
- https://github.com/ibexa/behat/pull/119
This PR adds basic behat coverage to user profile feature. 
I have split oss/headless job into 2 new ones - user profile is enabled from headless edition.
**Note:** There is one bug related to the user profile update form - https://issues.ibexa.co/browse/IBX-8698 For this reason I have not included in the scenario the step of entering the data into the Contact group field. When it is fixed I will add this step.
=> [Behat] IBX-8638: As a QA I want to add behat coverage to user profile

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/js/scripts/helpers/request.helper.js, src/bundle/Resources/translations/messages.en.xliff
=> IBX-8671: Missing notification text when removing required field

src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| :ticket: Issue | IBX-8770 |
- https://github.com/ibexa/image-picker/pull/84
- https://github.com/ibexa/assets-library-widget/pull/36 - build
Standalone versions and DXP should be tested
=> IBX-8770: Image picker tree displays Location folder while content of Images folder is displayed

src/bundle/Controller/Content/ContentTreeController.php, src/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolver.php
| :ticket: Issue | [IBX-8800](https://issues.ibexa.co/browse/IBX-8800) |
Currently `LogicalAnd` criterion is always added to query via `ContentTreeChildrenQueryArgumentResolver` and `ContentTreeController::loadChildrenAction`. When using solr or elasticserach engine and filter parameter is not passed to request, exception about `Invalid aggregation in LogicalAnd criterion` is throw. 
This PR changes type hint of `$filter` parameter from `Criterion` to `?Criterion` in `ContentTreeController::loadChildrenAction`. This allows to yield null value in `ContentTreeChildrenQueryArgumentResolver::resolve` when processed array of filter criteria is empty.
=> IBX-8800: Fixed subitems filtering

composer.json, src/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolver.php
Since PHP 8.3 supports functions added in `ibexa/polyfill-php82`, so this bundle is no longer needed.
=> Dropped ibexa/polyfill-php82

src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js, src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
=> IBX-8789: Fix double handling of file upload on window d&d

src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff, src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab.js, src/lib/Translation/Extractor/JavaScriptFileVisitor.php
=> IBX-8132: [UDW] For object relation field user can remove selected item from bookmarks

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
=> IBX-8829: [Richtext] Distraction free mode button should be disabled when richtext field isn't translatable

phpstan-baseline-7.4.neon, phpstan-baseline-8.3.neon, phpstan-baseline.neon, phpstan-baseline.neon.php, src/bundle/Resources/public/scss/_forms.scss, src/bundle/Resources/translations/validators.en.xliff, src/lib/Form/Data/Language/LanguageCreateData.php, src/lib/Form/Data/Language/LanguageUpdateData.php
| :ticket: Issue | IBX-8525 |
|----------------|----------|
Added language code validation
Mention language code format
=> IBX-8525: Added language code validation

src/contracts/Menu/CopyFormContextMenuBuilder.php, src/contracts/Menu/CreateFormContextMenuBuilder.php, src/contracts/Menu/MenuItemFactoryInterface.php, src/contracts/Menu/UpdateFormContextMenuBuilder.php
1) `Nad` is clearly a typo
2) Usually we write the policies divided with a slash
These things become visible in the PHP API reference, hence why I'm improving them.
=> Improved PHPDoc descriptions

src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js, src/bundle/Resources/public/js/scripts/autogenerate.identifier.js, src/bundle/Resources/public/js/scripts/core/slug.value.input.autogenerator.js, src/bundle/Resources/views/themes/admin/content_type/create.html.twig, src/bundle/Resources/views/themes/admin/content_type/edit.html.twig, src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig, src/bundle/Resources/views/themes/admin/content_type/part/field_definition_form.html.twig
=> IBX-9086 Autogenerated identifiers for content types & field definitions

src/bundle/ui-dev/src/modules/common/popup/popup.component.js, src/bundle/ui-dev/src/modules/common/spinner/spinner.js
| :ticket: Issue | IBX-9135 |
- https://github.com/ibexa/image-picker/pull/92
- https://github.com/ibexa/assets-library-widget/pull/49
=> IBX-9135:[ALW] grayed out effect issue

src/bundle/Resources/public/scss/_buttons.scss, src/bundle/Resources/public/scss/_dropdown.scss, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/_preview-header.scss, src/bundle/Resources/public/scss/_preview.scss, src/bundle/Resources/translations/ibexa_content.en.xliff, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
=> IBX-9056: Redesigned content preview

src/bundle/Resources/public/scss/_tables.scss, src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/toggle-selection/toggle.selection.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection/tree.item.toggle.selection.js, src/bundle/ui-dev/src/modules/universal-discovery/helpers/selected.locations.helper.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedLocationsHelpers.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| :ticket: Issue | IBX-9227 |
- https://github.com/ibexa/image-picker/pull/94
=> IBX-9227: Restore multipleItemsLimit cehcks in UDW

src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
| :ticket: Issue | IBX-9136 |
- https://github.com/ibexa/assets-library-widget/pull/52
- https://github.com/ibexa/image-picker/pull/95
Besides test ALW, this PR needs tests language filter in UDW and Image Picker
=> IBX-9136: [ALW] UI language issue vs content language

phpstan-baseline.neon, src/bundle/Controller/AssetController.php, src/bundle/Controller/Content/ContentTreeController.php, src/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolver.php, src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php, src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php, src/lib/UI/Module/ContentTree/NodeFactory.php, tests/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolverTest.php
| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/456
=> IBX-8534: Replaced Abstract Criterion with CriterionInterface

src/bundle/Resources/public/js/scripts/admin.distraction.free.mode.js
| :ticket: Issue | [IBX-8837](https://issues.ibexa.co/browse/IBX-8837) |
This bug is caused by CKEditor code itself, I've created issue there https://github.com/ckeditor/ckeditor5/issues/17241 but I doubt it will be resolved soon (if ever), judging from my experience, so here's fix for it.
I'm basically temporarly removing styles that breaks supossed correct behaviour, as distraction free mode takes whole page, it doesn't matter what happens beneath, as it's not visible. When closing DFM I restore remove my inline styles/restore previous inline styles
This solves https://issues.ibexa.co/browse/IBX-8965 as well, I think.
=> IBX-8837: Distraction free mode: Text obstruction by toolbar's fixed position

src/lib/Form/DataTransformer/DateTimePickerTransformer.php, tests/lib/Form/DataTransformer/DateTimePickerTransformerTest.php
| :ticket: Issue | N/A       |
Allowed to use \DateTimeInterface (effectively `DateTimeImmutable` and `DateTime`) with `\Ibexa\AdminUi\Form\Type\DateTimePickerType` 
N/A
N/A
=> Allowed to use DateTimeInterface in DateTimePicker form type

src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
I was not able to reproduce the problem on a fresh 4.6, but on a installation just upgraded to 4.6 (was at some point using 2.5 or maybe even older releases) the database had a lot of images with the following "empty" data in `ezcontentobject_attribute.data_text`:
```
<?xml version="1.0" encoding="UTF-8"?>
<ezimage serial_number=""
is_valid=""
filename=""
suffix=""
basename=""
dirpath=""
url=""
original_filename=""
mime_type=""
width=""
height=""
alternative_text=""
alias_key="1293033771"
timestamp="1086942459" />
```
In 4.6, the value will simply be `null` if no image is uploaded. However, in earlier versions it was obviously stored like shown above. And one problem here is that `height` has a value set to empty string. The admin-ui template requires `height` to be numeric or a …
=> Made template for showing image_field in admin-ui more robust

phpstan-baseline.neon, src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
=> IBX-9285: Navigation anchor on content creation/edition not working with diacritical marks

src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
| :ticket: Issue | IBX-9022 |
- https://github.com/ibexa/product-catalog/pull/1203
=> IBX-9022: price tab validation issues

src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| :ticket: Issue | IBX-9313 |
After this and previous changes (from other PRs) that optimized the UDW request, it would be good to perform a thorough checkup to ensure that everything is working correctly with various language settings like the one described in the JIRA ticket.
=> IBX-9313: Fix fetching ContentInfo on select

src/bundle/Resources/public/scss/ui/modules/common/_spinner.scss, src/bundle/ui-dev/src/modules/common/spinner/spinner.js, src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationListDataVisitor.php
| :ticket: Issue | IBX-9274 |
- https://github.com/ibexa/image-picker/pull/97
- https://github.com/ibexa/assets-library-widget/pull/55
Endpoint `/api/ibexa/v2/module/universal-discovery/locations?locationIds=1,2,3` always return permissions only for the last location from the `locationIds` parameter. The problem was method `LocationListDataVisitor->visit` which iterates through the list of locations `$data->getLocationList()`, with each iteration it made a `startList`, which create new list with one element instead of adding location data to it.
=> IBX-9274: Context menu does not show up in 'Location' folder

src/bundle/Resources/public/scss/_grid-view-item.scss, src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss, src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js, src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
| :ticket: Issue | IBX-7484 |
After the changes, the hidden element looks like in the screenshots for different views
=> IBX-7484: unified display of hidden locations in UDW

src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.item.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss, src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff, src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig, src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js, src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab.js, src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection/tree.item.toggle.selection.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedLocationsHelpers.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
=> IBX-9322: ezobjectrelationlist field allows selecting the same content multiple times

src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
| :ticket: Issue | IBX-8945 |
In `errorCallback` we get a `GeolocationPositionError` object, so we need to pass a value from the field message to `showErrorNotification`, which stores information about the error.
=> IBX-8945: Improved display of geolocation errors

src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
| :ticket: Issue | IBX-9370 |
Currently main search and UDW search behave differently:
- UDW search adds a trailing wildcard `*`  to the search term
- Main search does not add a trailing wildcard
This has some pitfalls:
- UDW search and main search will potentially provide different results.
- Wildcard character might be different across search engines or wildcards might not be supported at all.
PR is removing the wildcard.
=> IBX-9370: Aligned UDW-searchterm with main search

src/bundle/Resources/public/js/scripts/admin.input.text.js
=> IBX-9358 Fixed discard button in number input

src/bundle/Resources/public/js/scripts/admin.input.text.js, src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | [IBX-9332](https://issues.ibexa.co/browse/IBX-9332) |
=>  IBX-9332: Add refine text support to eztext fields

src/lib/Form/Type/ChoiceList/Loader/SiteAccessChoiceLoader.php, src/lib/Form/Type/Preview/SiteAccessChoiceType.php, src/lib/Menu/ContentRightSidebarBuilder.php
| :ticket: Issue | IBX-9293|
https://github.com/ibexa/site-context/pull/64
Using the preview route's `languageCode` will narrow down site accesses to ones that use this language. 
Moreover, `defaultLanguageCode` seems better when generating preview URI: https://github.com/ibexa/admin-ui/pull/1421/commits/33a77c1d08b951a7295ce686c17697acdb2d226a
=> IBX-9293: Base site access choice loader on language code

src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection/tree.item.toggle.selection.js
| :ticket: Issue | [IBX-9489](https://issues.ibexa.co/browse/IBX-9489) |
This PR reverts changing order of operations introduced in https://github.com/ibexa/admin-ui/pull/1409/files#diff-bf77db8b51e34024d4e5a4296543fbdca4b437d11f43b61d4de71482b7b5c794R33
That's not perfect solution, as it breaks rules of hooks (early return before hooks), but this check has to be done here, as all these contexts doesn't exist outside UDW. In a perfect world, this `isUDW` check should be done in parent before rendering this component, but parent is class component, so it can't use context from hooks...
=> IBX-9489: [OSS] UncaughtTypeError after entering 'Content structure'

src/bundle/ValueResolver/PolicyValueResolver.php, tests/bundle/ValueResolver/PolicyValueResolverTest.php
| :ticket: Issue | IBX-9511 |
- https://github.com/ibexa/admin-ui/pull/1415
This PR fixes incorrect expectation and usage of object returned by `RoleService::loadRole` API.
I can't find any occurence where that API would return `RoleDraft` instead of `Role`. For that we have a separate API.
So, that means we need more extensive manual QA, because maybe I'm missing something.
Note: Behat fails due to unmerged DXP PRs.
PolicyValueResolver is used for Admin -> Roles:
* update policy
* delete policy
however it would be nice to have here more manual tests around that module, as there's probably a reson the code was written as it was.
=> IBX-9511: Fixed incorrect object type in PolicyValueResolver

src/bundle/Resources/public/scss/_inputs.scss, src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
| :ticket: Issue | IBX-9448 |
- https://github.com/ibexa/discounts/pull/101
=> IBX-9448: Input side label

src/bundle/Resources/public/scss/_custom.tooltip.scss, src/bundle/Resources/public/scss/_mixins.scss, src/bundle/Resources/public/scss/mixins/_tooltips.scss
| :ticket: Issue | IBX-9374 |
- https://github.com/ibexa/share/pull/21
=> IBX-9374: stored copied link clipboard

phpstan-baseline.neon, src/bundle/Controller/TrashController.php
| :ticket: Issue | IBX-9577 |
- https://github.com/ibexa/admin-ui/pull/1415
This is a follow up to Symfony 6 upgrade (#1415). In Symfony 6 we can no longer use `$request->query->get` on non-scalar request query parameters. Resolving here the issue at hand, however I expect some follow-ups.
Steps from JIRA.
=> IBX-9577: Fixed fetching query data for Trash search

src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
| :ticket: Issue | IBX-9333 |
After introducing `requestParamsHaveChanged`, actions did not cause the page to be reloaded and the loading to be hidden, which is why an additional state was introduced
=> IBX-9333: introduced isUpdate to reload sub-items page after actions

src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig, src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig, src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-9463 |
- https://github.com/ibexa/product-catalog-date-time-attribute/pull/21
These changes are likely to affect many field types (they resolve a possible global bug with enabled action buttons for disabled fields). They should be tested not only for attributes, but also for other fields.
=> IBX-9463: Disabled field based on passed attribute

src/bundle/Resources/views/themes/admin/content/tab/policies/limitation_values.html.twig, src/bundle/Resources/views/themes/admin/content/tab/roles/limitation_values.html.twig, src/bundle/Resources/views/themes/admin/limitation/limitation_values.html.twig, src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig, src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
| :ticket: Issue | N/A       |
> The spaceless filter is deprecated as of Twig 3.12 and will be removed in Twig 4.0.
See https://twig.symfony.com/doc/3.x/deprecated.html 
Limitations and field types rendering.
N/A
=> [Twig] Removed usage of deprecated spaceless filter

src/bundle/View/Template/IbexaPagerfantaTemplate.php
| :ticket: Issue | IBX-9636 |
The problem is the lack of `.prev` and `.next` css classes that we use to style the buttons.
Ibexa DXP v5.0 uses `"pagerfant/pagerfant": "^3.6.2"` while in v4.6 `"pagerfant/pagerfant": "^2.7"` the getDefaultOptions method returning defaults paramteres has changed between versions.
Pagerfanta 3.x: 
`css_prev_class` and `css_next_class` return empty string
https://github.com/BabDev/Pagerfanta/blob/3.x/lib/Core/View/Template/TwitterBootstrapTemplate.php#L21-L22
Pagerfanta 2.x: 
`css_prev_class` return css class `prev`
`css_next_class` return css class `next`
https://github.com/BabDev/Pagerfanta/blob/2.x/lib/Core/View/Template/TwitterBootstrapTemplate.php#L16-L17
=> IBX-9636: Pagination arrows not displayed correctly

src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.items.panel.item.scss, src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.items.panel.scss, src/bundle/ui-dev/src/modules/common/middle-ellipsis/middle.ellipsis.js, src/bundle/ui-dev/src/modules/common/popup/popup.component.js, src/bundle/ui-dev/src/modules/universal-discovery/components/selected-items/selected.items.panel.item.js, src/bundle/ui-dev/src/modules/universal-discovery/components/toggle-selection/toggle.item.selection.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/usePaginableFetch.js, src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedItemsReducer.js, src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
| :ticket: Issue | IBX-9449 |
- https://github.com/ibexa/product-catalog/pull/1225
=> IBX-9449: Product Picker base object selection with variants

src/bundle/Resources/translations/ibexa_content_create.en.xliff, src/bundle/Resources/translations/ibexa_content_edit.en.xliff, src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig, src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
=> IBX-9338: Updated buttons label for create content on the fly

src/bundle/Resources/public/js/scripts/fieldType/ezurl.js
| :ticket: Issue | IBX-9217 |
Ad. 9e00eb2 / 5ad899b
In the end modified scenarios for variants in https://github.com/ibexa/product-catalog/pull/1251 ~Added retrying (and mouse over) for switching field groups~ due to random error encountered on Chrome v124 on Headless:
https://github.com/ibexa/headless/actions/runs/13391931955/job/37401422810#step:18:215
https://res.cloudinary.com/ezplatformtravis/image/upload/v1739887300/screenshots/67b492c43b022776389969-vendor_ibexa_product-catalog_features_browser_productvariants_feature_165_whc2qm.png
In this PR tests fail because Chrome 110 is used (without support for `canParse`). 
Tests with Chrome 124 are run https://github.com/ibexa/commerce/pull/1186, https://github.com/ibexa/experience/pull/520, …
=> IBX-9217: Added URL validation

src/bundle/Resources/public/js/scripts/fieldType/ezurl.js, src/bundle/Resources/views/themes/admin/ui/layout.html.twig
| :ticket: Issue | IBX-9723 |
I changed the url validation to a regular expression checking if the string starts with: 
- `http://`
- `https://`
- ` ftp:// `
- ` ftps:// `
- ` sftp:// `
-  `www.`
- `/ `
- `ezlocation://`
- `domain`
- `sub.domain`
And after this has at least one character. The previously solution with `canParse` returns true for e.g. `http:a`
=> IBX-9723: Relative URLs in ezurl field no longer works

src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.search.js
=> IBX-9689: Fixed search icon placing

src/bundle/Resources/public/js/scripts/admin.format.date.js, src/bundle/Resources/public/js/scripts/core/tag.view.select.js, src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js, src/bundle/ui-dev/src/modules/common/thumbnail/thumbnail.tsx
| :ticket: Issue | [IBX-9776](https://issues.ibexa.co/browse/IBX-9776) |
=> IBX-9776: Fix eslint errors on main branches

src/lib/Form/Data/ContentTypeData.php
=> Phpstan fix - ContentTypeData::$isNew in isset() is not nullable nor uninitialized

phpstan-baseline.neon, src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig, src/lib/Form/Type/Location/LocationTrashType.php
> [!CAUTION]
>  - [x] Drop TMP commit before merging
| :ticket: Issue | IBX-8471 |
- #1489 
We have a regression in Symfony Forms handling of "Send to trash" confirmation dialog appearing in Content View.
1. Confirm checkbox was rendered outside of the modal dialog as options were added but were not present during rendering ([rendered on `form_end`](https://github.com/ibexa/admin-ui/blob/a2415ebf1e7b606bf48d84df8c95262e55b55fae/src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig#L53)) - please read further to understand why.
2. `trash_options` didn't receive proper options
Actual behavior
Expected behavior:
Detected by [Behat regression run](https://github.com/ibexa/oss/actions/runs/15021258887/job/42210766591#step:18:64) :tada: …
=> IBX-8471: Fixed 'Send to trash' confirmation modal after Symfony 7 upgrade

rector.php, src/bundle/DependencyInjection/IbexaAdminUiExtension.php, src/bundle/Resources/config/services/form_ui_action_mappers.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/siteaccess.yaml, src/bundle/Resources/views/themes/admin/ui/search/spellcheck.html.twig
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/dependency-injection] Changed !tagged to !tagged_iterators YAML tag
* [symfony/http-kernel] Replaced Symfony\Component\DependencyInjection\Extension instead of Symfony\Component\HttpKernel\DependencyInjection\Extension
```
Sanities.
=> IBX-9968: Resolved Symfony 7.x deprecations

src/bundle/Resources/views/themes/admin/content/tab/policies/limitation_values.html.twig, src/bundle/Resources/views/themes/admin/content/tab/roles/limitation_values.html.twig, src/bundle/Resources/views/themes/admin/limitation/limitation_values.html.twig, src/lib/Limitation/Templating/LimitationBlockRenderer.php, tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_1.html.twig, tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_2.html.twig, tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_3.html.twig, tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_overriden.html.twig
| :ticket: Issue | IBX-8223 |
https://github.com/ibexa/activity-log/pull/126
https://github.com/ibexa/cart/pull/136
https://github.com/ibexa/corporate-account/pull/289
https://github.com/ibexa/order-management/pull/151
https://github.com/ibexa/payment/pull/172
https://github.com/ibexa/permissions/pull/28
https://github.com/ibexa/personalization/pull/369
https://github.com/ibexa/product-catalog/pull/1313
https://github.com/ibexa/segmentation/pull/129
https://github.com/ibexa/shipping/pull/112
https://github.com/ibexa/taxonomy/pull/334
https://github.com/ibexa/user/pull/100
https://github.com/ibexa/workflow/pull/136
Refactored limitation value blocks to use 'ibexa_' prefix
Check if all type of limitations are rendered correctly
=> IBX-8223: Refactored limitation value blocks to use 'ibexa_' prefix

phpstan-baseline.neon, src/lib/Form/ActionDispatcher/ContentTypeDispatcher.php, src/lib/Validator/Constraints/ValidatorConfigurationValidator.php
> [!CAUTION]
> - [x] Remove TMP commit before merging
> - [x] Merge content-forms first 
|----------------|----------|
- https://github.com/ibexa/content-forms/pull/91
ibexa/content-forms#91 fixes several issues found by PHPStan after Symfony 7 upgrade. It also adds some return strict types. Aligning here AdminUI codebase with those changes.
Note: should `\Ibexa\AdminUi\Validator\Constraints\ValidatorConfigurationValidator::validate` accept strict `FieldDefinitionData` as `$value` type instead? That would change the behavior, so didn't touch it, but maybe it's a valid change? Also reported by PHPStan in the baseline.
Alternatively, I could roll back changes causing failure here. It wasn't quite visible when working on content-forms, found only by Behat at the …
=> IBX-9727: Aligned codebase with content-forms changes

dependencies.json, src/bundle/Resources/config/services/ui_config/common.yaml, src/bundle/Resources/views/themes/admin/ui/layout.html.twig, src/bundle/Templating/Twig/SecurityExtension.php, tests/bundle/Templating/Twig/SecurityExtensionTest.php, tests/bundle/Templating/Twig/_fixtures/security/ibexa_get_rest_csrf_token_intention.test
| :ticket: Issue | IBX-9944 |
- https://github.com/ibexa/recipes-dev/pull/183
=> IBX-9944: Add support for stateless CSRF protection in admin-ui

phpstan-baseline.neon, src/bundle/Templating/Twig/ComponentExtension.php, src/bundle/Templating/Twig/FormatIntervalExtension.php, src/bundle/Templating/Twig/TimeDiffExtension.php, src/lib/Translation/Extractor/NotificationTranslationExtractor.php, src/lib/Validator/Constraints/LocationHasChildren.php, src/lib/Validator/Constraints/LocationHaveUniqueAssetRelation.php, src/lib/Validator/Constraints/LocationIsContainer.php, src/lib/Validator/Constraints/LocationIsNotRoot.php, src/lib/Validator/Constraints/LocationIsNotSubLocation.php, src/lib/Validator/Constraints/LocationIsWithinCopySubtreeLimit.php
| :ticket: Issue | n/a |
|----------------|-----|
This PR adds explicit return types.
These changes eliminate PHPStan errors (e.g., missingType.return, missingType.iterableValue) and improve static analysis coverage.
No functional changes were made.
=> Added missing return types

phpstan-baseline.neon, src/lib/Event/Options.php
See https://github.com/ibexa/core/pull/563 
N/A
N/A
=> IBX-9727: Add missing type hints to options contracts

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-10100 |
- https://github.com/ibexa/fieldtype-richtext-rte/pull/19
=> IBX-10100: Collaborator's icons should be displayed above field's label

src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
| :ticket: Issue | IBX-10141 |
=> IBX-10141: Add new icon names for IncludedIcon component

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | IBX-10134 |
- https://github.com/ibexa/connector-ai/pull/135
- https://github.com/ibexa/corporate-account/pull/304
=> IBX-10134: Remove depracated JS/twig code

src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
| :ticket: Issue | IBX-8561 |
During some part of redesign/UX improvment there was added functionality with actions on embedded content. However, non of them took into consideration that we do not always have access to it. As a result, if conditions were not applied to all parts of the view.
As the migration do not pass without some modifications - long story short, there is one content with relation to another one placed inside section to which editor user do not have access to.
=> IBX-8561: Fixed relation list when trying to display unauthorized content

src/lib/Form/DataMapper/ContentMainLocationUpdateMapper.php, tests/lib/Form/DataMapper/ContentMainLocationUpdateMapperTest.php
| :ticket: Issue | n/a |
|----------------|-----|
- https://github.com/ibexa/core/pull/569
Discovered while testing ibexa/core#569 on main. It looks like the bug exists in 4.6.
`\Ibexa\AdminUi\Form\DataMapper\ContentMainLocationUpdateMapper::map` calls `\Ibexa\AdminUi\Form\Data\Content\Location\ContentMainLocationUpdateData::setLocation` with `mainLocationId` while the method expects an instance of a Location. My guess is that the method is not used anywhere, therefore not visible.
Regressions:
- :green_circle:   https://github.com/ibexa/commerce/pull/1366
=> Fixed setting location data in ContentMainLocationUpdateMapper

phpstan-baseline.neon, src/lib/Form/Data/Section/SectionUpdateData.php, src/lib/Form/DataMapper/LanguageCreateMapper.php, src/lib/Form/DataMapper/SectionUpdateMapper.php, tests/lib/EventListener/SetViewParametersListenerTest.php, tests/lib/Form/DataMapper/SelectionUpdateMapperTest.php, tests/lib/Form/Processor/PreviewFormProcessorTest.php, tests/lib/Pagination/Pagerfanta/TrashItemAdapterTest.php
> [!CAUTION]
> Needs to be merged together with ibexa/core#569
> - [x] Drop TMP commit before merging
- https://github.com/ibexa/core/pull/569
Adjusted code after ibexa/core#569 changes with some improvements in the vicinity of changed code.
See the notes in diff comments for reasoning behind the changes.
No QA required.
=> IBX-9727: Aligned codebase after core content VO type hints changes

src/bundle/DependencyInjection/Configuration/Parser/Assets.php, src/bundle/Resources/config/icons_aliases.yaml
| :ticket: Issue | IBX-10168 |
- https://github.com/ibexa/dashboard/pull/155
- https://github.com/ibexa/page-builder/pull/449
- https://github.com/ibexa/personalization/pull/382
- https://github.com/ibexa/product-catalog/pull/1352
- https://github.com/ibexa/version-comparison/pull/106
There's bigger issue in resolving config, also in other bundles, so someone from backend will need to look into it. Without this check site access resolver was always returning empty array therefore it didn't resolved default one. @Steveb-p looked into it, so he'll be able to tell more.
=> IBX-10168: Fixed missing assets icons

phpstan-baseline.neon, src/lib/Form/Data/TrashItemData.php, tests/lib/Form/Data/TrashItemDataTest.php
| :ticket: Issue | IBX-8638 |
Ensured last ancestor is valid before comparing paths in TrashItemData
Check if after removing folder which is root in tree via API, we can open trash without problems
=> IBX-8638: Ensured last ancestor is valid before comparing paths in TrashItemData

src/bundle/Controller/AssetController.php, src/bundle/Resources/public/js/scripts/helpers/request.helper.js
| :ticket: Issue | IBX-10125 |
Two things:
- JsonResponse should not succeed with status 200 if it fails.
- JS improperly handles such a failed request. The`jsonResponse.ErrorMessage` call was giving empty results. Shouldn't we rather fallback to full response?
=> IBX-10125: Handled image upload failed request

composer.json, phpstan.neon, src/lib/Menu/ContentRightSidebarBuilder.php, src/lib/Specification/Location/IsContentStructureRoot.php, src/lib/Specification/Location/IsInContextualTreeRootIds.php, src/lib/Specification/Location/IsRoot.php, tests/lib/Specification/Location/IsContentStructureRootTest.php, tests/lib/Specification/Location/IsInContextualTreeRootIdsTest.php, tests/lib/Specification/Location/IsRootTest.php, tests/lib/Validator/Constraint/LocationIsNotRootValidatorTest.php
| :ticket: Issue | IBX-10221 |
Fix 500 error when attempting to trash root-level or contextual root locations
- Fixed a 500 error that occurred when attempting to send a Site skeleton to trash, caused by incorrect handling of contextual root locations.
- Introduced the IsInContextualTreeRootIds specification, which checks whether a location belongs to the configured contextual root locations via the
- The "Send to Trash" menu item is now hidden when the selected location is either the root or a contextual root location.
=> IBX-10221: Fixed 500 error when removing Site skeletons by improving location root checks

src/bundle/Resources/public/scss/_trash-search-form.scss
| :ticket: Issue | IBX-10240 |
=> IBX-10240: Fixed font color in trash creator filter

src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
=> IBX-6770: "All functions" policy spelling fix

phpstan-baseline.neon, src/bundle/Controller/ContentController.php, src/contracts/Event/ContentEditEvent.php
| :ticket: Issue | IBX-10265 |
=> IBX-10265: Fixed wrong edit view for product

src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
| :ticket: Issue | N/A |
|----------------|-----|
Replaces the deprecated Twig function `ibexa_render_component_group` with `ibexa_twig_component_group` as recommended since ibexa/admin-ui 4.6.19.
This removes deprecation warnings triggered in templates such as `form_fields.html.twig`.
=> Replaced `ibexa_render_component_group` with `ibexa_twig_component_group` in form fields template.

src/bundle/Resources/public/scss/ui/modules/common/_draggable.dialog.scss
| :ticket: Issue | IBX-10358 |
Increased z-index for tooltips in component c-draggable-dialog, which has z-index itself on 10000
=> IBX-10358: Close icon in AI Assistant is barely visible

src/bundle/Resources/public/scss/_inputs.scss
| :ticket: Issue | IBX-10145 |
This change affects all toggles in the system, not only in discounts.
=> IBX-10145: Fix ibexa-toggle clickable area

src/bundle/Controller/User/ProfileEditController.php, src/bundle/Controller/UserOnTheFlyController.php
- https://github.com/ibexa/content-forms/pull/95
Adapted to deprecations introduced via https://github.com/ibexa/content-forms/pull/70.
=> Adapted to deprecated `null` value for content structs in `BaseContentType`

phpstan-baseline.neon, src/bundle/Controller/ContentOnTheFlyController.php, src/lib/EventListener/UserProfileListener.php, src/lib/FieldType/Mapper/AuthorFormMapper.php, src/lib/Form/Data/ContentTranslationData.php, src/lib/Form/Processor/PreviewFormProcessor.php, src/lib/Form/Processor/TranslationFormProcessor.php
| :ticket: Issue | - |
Followup after dropping deprecation described here: https://github.com/ibexa/content-forms/pull/70. Apart from this, I got rid of magic properties' accessing here and there in favour of proper getters.
=> Fixed editing content from UDW after dropping non-nullable `struct` parameter from parent form

src/bundle/Resources/translations/ibexa_content_edit.en.xliff, src/bundle/Resources/translations/ibexa_user_create.en.xliff, src/bundle/Resources/translations/ibexa_user_edit.en.xliff, src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig, src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig, src/bundle/Resources/views/themes/admin/user/create.html.twig, src/bundle/Resources/views/themes/admin/user/edit.html.twig
| :ticket: Issue | IBX-10417 |
In this PR I updated create/edit header for content on the fly and create user header and the user creation header.
Content on the fly 
User create
=> IBX-10417: Removed redundant information in header create/edit

src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
| :ticket: Issue | IBX-8111 |
If the location doesn't have a mapping assigned to it (by default it doesn't) maybe we should reuse the default mapping and validate a file's type only by the default mime types mapping. I'm not sure about this one to be honest. How should we validate file if location mapping is not there? Backend already does its validation properly, but what should we depend on when it comes to frontend?
=> IBX-8111: Validated file mime type for multi file upload without specified location mapping

src/bundle/Resources/public/scss/_modals.scss, src/bundle/Resources/views/themes/admin/ui/component/modal/modal.html.twig
| :ticket: Issue | IBX-10398 |
=> IBX-10398: Modal close btn styles update

src/bundle/Resources/public/js/scripts/admin.picker.js, src/bundle/Resources/public/js/scripts/core/date.time.picker.js
=> IBX-6662: Handled re-positioning date picker on scroll

src/bundle/Command/CompileAssetsCommand.php
| :ticket: Issue | IBX-10558 |
Allow to have `yarn encore dev --watch` feature without changing habitual command.
`php bin/console ibexa:encore:compile --watch` runs until killed, it watches the assets, and rebuilds them on change.
About errors:
* `php bin/console ibexa:encore:compile --watch --timeout 123` throws error `Watch mode can't be used with a timeout.` 
* `php bin/console ibexa:encore:compile --timeout` still throws error `The "--timeout" option requires a value.`
* `php bin/console ibexa:encore:compile --timeout abc` still throws error `Timeout value has to be an integer.`
=> Added --watch option to ibexa:encore:compile

phpstan-baseline.neon, src/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriber.php, src/lib/Form/Type/Extension/ModifyFieldDefinitionsCollectionTypeExtension.php, tests/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriberTest.php
| :ticket: Issue | IBX-10617 |
=> IBX-10617: Allowed nullable field type identifier within `ModifyFieldDefinitionsCollectionTypeExtension`

phpstan-baseline.neon, src/bundle/Controller/ContentController.php, src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/forms.yaml, src/bundle/Resources/config/services/preview.yaml, src/bundle/Resources/views/themes/admin/content/content_preview.html.twig, src/contracts/Event/ResolveVersionPreviewUrlEvent.php, src/contracts/Exception/UnresolvedPreviewUrlException.php, src/contracts/PreviewUrlResolver/VersionPreviewUrlResolverInterface.php, src/lib/EventListener/SystemVersionPreviewUrlSubscriber.php, src/lib/Form/Type/ChoiceList/Loader/SiteAccessPreviewChoiceLoader.php, src/lib/Form/Type/ChoiceList/Loader/VersionPreviewUrlChoiceLoader.php, src/lib/Form/Type/Preview/SiteAccessChoiceType.php, src/lib/Form/Type/Preview/VersionPreviewUrlChoiceType.php, src/lib/PreviewUrlResolver/VersionPreviewUrlResolver.php, tests/lib/EventListener/SystemVersionPreviewUrlSubscriberTest.php, tests/lib/PreviewUrlResolver/VersionPreviewUrlResolverTest.php
Introduced `Ibexa\Contracts\AdminUi\PreviewUrlResolver\VersionPreviewUrlResolverInterface` which is responsible for determine preview URL of given content version (inc. content drafts).
```php
interface VersionPreviewUrlResolverInterface
{
public function resolveUrl(
VersionInfo $versionInfo,
Location $location,
Language $language,
SiteAccess $siteAccess
): string;
}
```
Resolver also dispatches `\Ibexa\Contracts\AdminUi\Event\ResolveVersionPreviewUrlEvent` event allowing to custom preview URL generation from 3rd party extensions. Use cases:
* Added pre-auth token for generating public link
* Delegate preview rendering to 3rd party service e.g. Single Page Application 
N/A
New service and extension point.
=> Added extension point to resolve preview URL

phpstan-baseline.neon, src/bundle/Controller/LocationController.php, src/lib/EventListener/ViewTemplatesListener.php, tests/bundle/DependencyInjection/Configuration/Parser/SubtreeOperationsTest.php
https://github.com/ibexa/admin-ui/compare/4.6...fix-phpstan?expand=1#diff-995edee38ad4f8387e58ebd52c31bcc04c56cc2448d331b1cf5e0b35c57b9efaR13420
That one was added to the baseline as the issue comes from `\Ibexa\Contracts\Core\Repository\Values\Content\Relation::$sourceFieldDefinitionIdentifier`
where our glorious VO claimes that this can be only string in phpdoc, but we all know that it can be null as well when unitialized.
=> [CI] Fixed new phpstan issues
